### ISSUE TITLE
AttributeError: 'TextBlock' object has no attribute 'aabb'

### ISSUE THREAD

**Issue by shkds** [zyddnys/manga-image-translator#103]
我尝试修改代码在处理照片的exe，但遇到了这个问题
File "C:/ipython/image/aaaaaaaaaaaa.py", line 284, in <module>
    loop.run_until_complete(main())
  File "C:\Users\19378\.conda\envs\pytorch\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:/ipython/image/aaaaaaaaaaaa.py", line 278, in main
    await infer(img, mode, '', alpha_ch = alpha_ch)
  File "C:/ipython/image/aaaaaaaaaaaa.py", line 137, in infer
    await dispatch_ocr(img, text_regions, True, model_name="32px", verbose=True)
  File "C:\ipython\image\ocr\__init__.py", line 276, in dispatch
    return run_ocr_32px(img, cuda, list(generate_text_direction(textlines)), batch_size, verbose=verbose)
  File "C:\ipython\image\ocr\__init__.py", line 254, in generate_text_direction
    if quadrilateral_can_merge_region(ubox, vbox):
  File "C:\ipython\image\utils.py", line 1685, in quadrilateral_can_merge_region
    b1 = a.aabb
  File "C:\ipython\image\textblockdetector\textblock.py", line 185, in __getattribute__
    return object.__getattribute__(self, name)
AttributeError: 'TextBlock' object has no attribute 'aabb'
aabb是在Quadrilateral类中，但他会调用textblockdetector\textblock.py导致错误，应该如何解决呢

**Comment by thatDudo** [comment]
please try to be clearer with your issues

**Comment by thatDudo** [comment]
its because you are dealing with the TextBlock class that coexists with Quadrilateral because the author didnt want to use one unified interface and mess up the codebase...

**Comment by thatDudo** [comment]
its because you are dealing with the TextBlock class that coexists with Quadrilateral. I think it might be fruitful to somehow try and replace all references of textblocks with quadrlateral to make things clearer...

**Comment by shkds** [comment]
What should I do?

**Comment by dmMaze** [comment]
There's nothing we can help with if we don't know what have you modified and what you want to achieve.

**Comment by shkds** [comment]
I want to modify it to a small piece of software, not to request your server

**Comment by shkds** [comment]
textlines = await dispatch_ocr(img, textlines,True, model_name="48px_ctc", verbose=True)

You'll get an error when you run this，what should  ido?

**Comment by thatDudo** [comment]
Usually the server does all the steps itself, you cannot to one of the things yourself and tell the server to do the rest.
I suggest running it locally...
And if you have the knowledge to program in python why not use it? Why do you ask these basic python questions here? Just read the error messages

**Comment by shkds** [comment]
I'm very sorry. I found out that the path import problem has been resolved. Thank you.
