### ISSUE TITLE
Google OCR

### ISSUE THREAD

**Issue by rspreet92** [zyddnys/manga-image-translator#104]
I wanted to use Google Cloud Vision for OCR for better OCR results. Will it cause any problem with the inpainting ? or is there anything that I should keep in mind before implementing it?

Google Vision OCR
https://cloud.google.com/vision/docs/ocr

**Comment by thatDudo** [comment]
Do you mean to implement the api cause there is apparently no possibility to run that offline?. And not only do you have to pay them real money but you also have to make a google account...

**Comment by rspreet92** [comment]
@thatDudo yes that's what I mean. I am not requesting to add it in this project, just asking if implementing it will cause any problem, like I'm worried that Inpainting will break. If so then it's better to start something new.

**Comment by thatDudo** [comment]
I think before we add that we would probably need to add some structural improvements such as what the translators have. By doing that it will become more apparent what exactly the ocr method will have to return and what inputs it should accept, basically a common interface.
If you want i can try to make some work in that direction.

**Comment by rspreet92** [comment]
It will be really good if we can do that. It will make the future progress more smoother.

**Comment by rspreet92** [comment]
I also an idea for improvement:
If we can make each module work independently from each other then we can que task in different stages.

Like currently in batch mode it takes multiple images and perform ocr -> translation -> Inpainting on each image in sequence and doesn't start working on next image until the translation output of first image is completed (that's why it doesn't make full use of the resources).

By separating modules we can immediately start ocr/translation/Inpainting after finishing previous task.

I don't if I put it in right words but I hope you get what I'm saying.

**Comment by thatDudo** [comment]
I dont think that running detection, ocr, ... concurrently with translators is good idea due to some translators being based on offline models themselves, if that is what you meant. Doing so might cause memory problems and crashes without some kind of checks.

But yes the project is not very well structured or rather it didnt grow appropriately with all the new features that were added such as the web/batch mode and ctd/manga2eng.
