### ISSUE TITLE
How to make ocr recognize only Chinese and English, but not numbers.

### ISSUE THREAD

**Issue by shkds** [zyddnys/manga-image-translator#109]
How to make ocr recognize only Chinese and English, but not numbers.

**Comment by rspreet92** [comment]
I think you have to change the model data for that.

**Comment by zyddnys** [comment]
If the problem is that the program recognize and translate page number (or some other pure numbers) in your image, and you don't want that to happen, than the problem is trivial to solve. Or you want it to not recognize numbers for some other reason?

**Comment by rspreet92** [comment]
How about replacing numbers with " " (blank space) in raw text before sending to translator?

**Comment by thatDudo** [comment]
I guess a filter could be added after ocr that removes textblocks with text that doesnt need to be translated to the target language.

**Comment by thatDudo** [comment]
Feature added in 0d18e6091f2827d8d7b201dbff42ed7a60424098
