### ISSUE TITLE
Rename null translator

### ISSUE THREAD

**Issue by thatDudo** [zyddnys/manga-image-translator#110]
None and null are too similar. Maybe original is a better name for the null translator.

**Comment by rspreet92** [comment]
I don't think it's that big of a deal. Not many people are going use it and the use is clearly mentioned in the readme so it shouldn't cause any confusion.

**Comment by thatDudo** [comment]
No, a name is supposed to convey what it is used for

**Comment by rspreet92** [comment]
> No, a name is supposed to convey what it is used for

Well then I think **raw** would be better instead of **original**

**Comment by thatDudo** [comment]
Im not sure, raw is kind of still too ambiguous. Maybe unchanged or unvaried is better?

**Comment by zyddnys** [comment]
how about renaming `null` to `disabled`

**Comment by thatDudo** [comment]
No disabled sounds more fitting for none, but there we already have none. What does the null translator do? It takes gives back the original text.. So maybe `original` or `unvaried` is best.

**Comment by thatDudo** [comment]
Thanks!
