### ISSUE TITLE
希望添加图片放大功能

### ISSUE THREAD

**Issue by lumiamilk** [zyddnys/manga-image-translator#111]
一些日语插图翻译后的字体太小，即使将图片放大，汉字也会变模糊。
希望增加图片放大功能，在将汉化文本嵌入图片前，将原始图片的分辨率放大[640p -> 1080p]，之后再嵌入汉化文本，以实现文字高清化。
谢谢！

**Comment by thatDudo** [comment]
Would that not necessitate adding an upscaler? Im currently working on adding waifu2x anyway so that should probably help.

**Comment by lumiamilk** [comment]
> 

感谢！
请问有考虑添加给黑白漫画的上色功能吗？
将黑白漫画翻译后自动上色为彩色漫画。(*^_^*)
——————————————————
grateful!
Have you considered adding a coloring function to black and white comics?
Translate black and white comics into color comics automatically. (*^_^*)

**Comment by lumiamilk** [comment]
> Would that not necessitate adding an upscaler? Well, it doesnt matter since im currently working on adding waifu2x anyway..

感谢！
请问有考虑添加给黑白漫画的上色功能吗？
将黑白漫画翻译后自动上色为彩色漫画。(^_^)
——————————————————
grateful!
Have you considered adding a coloring function to black and white comics?
Translate black and white comics into color comics automatically. (^_^)

**Comment by thatDudo** [comment]
Not yet but that seems like a pretty good idea. Maybe me or someone else will add that later :thinking:
