### ISSUE TITLE
what is 'train.flist' file in training code?

### ISSUE THREAD

**Issue by ji-in0615** [zyddnys/manga-image-translator#112]

**Comment by ji-in0615** [comment]
where do I get file?

**Comment by zyddnys** [comment]
that file contains list of image file paths, it is useless by itself without the images.

**Comment by ji-in0615** [comment]
where exactly can I get file?

**Comment by ji-in0615** [comment]
traning code isn't running without 'train.flist' file.

**Comment by QiroNT** [comment]
Just write it yourself, list a file path for each line.
