### ISSUE TITLE
i can't install 'fairseq'

### ISSUE THREAD

**Issue by trananh158** [zyddnys/manga-image-translator#114]
Có cách nào tôi có thể cài đặt fairseq không ?
![image](https://user-images.githubusercontent.com/78089581/201452076-b1b6a179-7e61-4244-b961-33a3016382dd.png)

**Comment by rspreet92** [comment]
You need to install "Microsoft C++ Build Tools" first.

Download : https://visualstudio.microsoft.com/vs/

Instructions: https://learn.microsoft.com/en-in/visualstudio/install/modify-visual-studio?view=vs-2022#change-workloads-or-individual-components

**Comment by trananh158** [comment]
after downloading 'visual', i just need to download c++14 right ?
