### ISSUE TITLE
ERROR: Failed building wheel for fairseq ERROR: Could not build wheels for fairseq, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#115]
![2022-11-12_13-02-42](https://user-images.githubusercontent.com/49092250/201469090-25d1c7ff-aae6-4f6d-b3e8-43c5df3af3af.png)
how to fix it?

**Comment by thatDudo** [comment]
Please learn to read the error messages. Also someone literally opened the same issue right before you...

**Comment by rspreet92** [comment]
Same issue :
https://github.com/zyddnys/manga-image-translator/issues/114#issuecomment-1312325605
