### ISSUE TITLE
Preserve original image size after translating

### ISSUE THREAD

**Issue by mamatom** [zyddnys/manga-image-translator#125]
Preserve original image size after translating

**Comment by thatDudo** [comment]
You can force the to omit the upscaler with `--upscale-ratio=1`. Small images get upscaled automatically because the textdetector isnt very good at working on these resolutions.

**Comment by mamatom** [comment]
Is there a way to automatically downscale those small images?

**Comment by thatDudo** [comment]
No, why would you want that... Just do it yourself with ffmpeg.

**Comment by mamatom** [comment]
i guess imageMagick could do the trick then, thank you very much!
