### ISSUE TITLE
Web version not working after update

### ISSUE THREAD

**Issue by purpleraven** [zyddnys/manga-image-translator#128]
Looks like after https://github.com/zyddnys/manga-image-translator/commit/564733255266ed95959e80e79d0226206adc11fb commit image argument become mandatory

```
translate_demo.py: error: the following arguments are required: -i/--image
usage: translate_demo.py [-h] [-m {demo,batch,web,web2}] -i IMAGE
```

**Comment by QiroNT** [comment]
I can launch it just fine. Could you prove to me that you're definitely using a version after the commit? That commit is actually supposed to fix this.

**Comment by purpleraven** [comment]
@QiroNT i have pulled image from docker hub. Will wait for publishing of new version on docker hub
