### ISSUE TITLE
颜色形象是...

### ISSUE THREAD

**Issue by kdrkdrkdr** [zyddnys/manga-image-translator#13]
或许，彩色图像无法通过translate_demo.py文件显示吗？
在https://touhou.ai/imgtrans/  上很顺利..

**Comment by zyddnys** [comment]
不是很明白你的意思，你是在使用机器翻译提交issue吗，如果可以的话英语交流也可以。

**Comment by kdrkdrkdr** [comment]
Sorry! I didn't use --use-inpainting arguments!
It solved!
