### ISSUE TITLE
Exception: CUDA compatible device could not be found while --use_cuda args was set...

### ISSUE THREAD

**Issue by dunjionglin** [zyddnys/manga-image-translator#138]
I have download CUDA from nvidia but the CUDA compatible device still not found

**Comment by thatDudo** [comment]
Please follow the instructions from https://pytorch.org/
For example if youre on windows you have to have cuda 11.7 installed (uninstall other version) and put in the command from the website, with the `--force-reinstall` flag.
![Capture](https://user-images.githubusercontent.com/58403773/207597296-f4ed88e5-0224-41c5-ba1b-6bb34613f39d.PNG)
