### ISSUE TITLE
Error logging in web mode

### ISSUE THREAD

**Issue by purpleraven** [zyddnys/manga-image-translator#140]
Currently, in web mode during batch images processing very difficult to find logs for non processed images.
Will be much easyly, with error log for the image in same folder with it.

Now for every task working dirrectory created. Something like this 
```
result/89d8b9b34198b23753309232f60fc118feab2c9cde671bdcb6467f801c4f6589--deepl-RUS-default-auto/
``` 
the logs for one image processing can be storred in the same folder in log.txt

In that case I can create bug reports very fast =)

**Comment by thatDudo** [comment]
When the --verbose flag is set, log files will be created in the corresponding result/task_id folder.
