### ISSUE TITLE
Did not delete some of the source code. How to fix it?

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#142]
Did not delete some of the source code. How to fix it?
![2022-12-24_15-09-30](https://user-images.githubusercontent.com/49092250/209435587-712ababb-21fe-49c6-b3ef-e17dbd0b5c99.png)
![2022-12-24_14-52-55](https://user-images.githubusercontent.com/49092250/209434938-173c4407-bbd1-4006-b9da-bd2a317841a2.png)

**Comment by zyddnys** [comment]
try adding `--use-ctd` argument

**Comment by My12123** [comment]
@zyddnys 
Yeah, it worked out.
Can I ask what this gives  --use-ctd?

**Comment by QiroNT** [comment]
> Can I ask what this gives --use-ctd?

It's to use [CTD](https://github.com/dmMaze/comic-text-detector), which is an alternative text detector made by dmMaze, instead of the default one.
