### ISSUE TITLE
Could not recognize text. How to fix this?

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#143]
Could not recognize text. How to fix this?
![5041b267d90e5d187e445ebe4683d6aa](https://user-images.githubusercontent.com/49092250/209435351-186af25b-e3db-421f-9014-d5406bb41c90.png)

**Comment by QiroNT** [comment]
I'd recommend bumping `--detection-size` relatively, but I can't guarantee it will work. The default parameters are most suitable for single page comics, not combined ones where texts are smaller. See #96 for a similar case. In some extreme cases the detection is just not suitable to process, then I'd recommend splitting the image yourself.

**Comment by My12123** [comment]
![2022-12-26_19-37-02](https://user-images.githubusercontent.com/49092250/209568274-8fc0e41b-7ed9-4d27-8660-d1f7b30869c5.png)
