### ISSUE TITLE
Tall images not translated at all

### ISSUE THREAD

**Issue by purpleraven** [zyddnys/manga-image-translator#145]
For tall images text not translated at all

![0003](https://user-images.githubusercontent.com/20344446/209716520-d4d4484c-b7e3-49e5-b8c0-effa7e214f5d.jpeg)

I have tested it on 10+ images

**Comment by zyddnys** [comment]
Text detector is not designed for extreme aspect ratio images, you can split the image before translating them

**Comment by thatDudo** [comment]
That is because the detector scales the image to a square with a specific side length. Either try to cut the image in pieces or increase `--detector-size` argument. Perhaps in the future some kind of other solution could be found.
