### ISSUE TITLE
Error: (-215:Assertion failed) in function 'warpPerspective' 

### ISSUE THREAD

**Issue by crotron** [zyddnys/manga-image-translator#147]
I am getting the error in the title on some image files. Here is an example.

![example](https://user-images.githubusercontent.com/34594223/210011169-4f0ad4ce-1c51-4c71-b496-6763ae30b43b.png)

I tried the online demo in case it was a problem local to my machine, and it also produced an error.

**Comment by My12123** [comment]
I did it.
![2022-12-30_11-40-27](https://user-images.githubusercontent.com/49092250/210051248-604126c0-ea0f-496e-ba37-9988f80c4491.png)
![2022-12-30_11-44-03](https://user-images.githubusercontent.com/49092250/210051508-3fff4d09-0464-4770-be85-e0d2c3c21a2c.png)

**Comment by crotron** [comment]
Strange, I just tried it on https://touhou.ai/imgtrans/ and it is still giving me the error:

![image](https://user-images.githubusercontent.com/34594223/210086780-680d69fe-ef0e-427a-b480-6d44c5b07024.png)

**Comment by My12123** [comment]
I changed the other parameter.
![2022-12-30_19-01-42](https://user-images.githubusercontent.com/49092250/210089507-2e88e970-91ba-47ed-b7af-c49106db244c.png)

**Comment by thatDudo** [comment]
I have pushed a fix. @crotron can you test whether it is fixed now?

**Comment by thatDudo** [comment]
It would appear that all it took was decreasing the aspect ratio tolerance when merging.
Please verify for yourself that it works now :laughing:

**Comment by My12123** [comment]
![0f5ea250-bf98-488e-a833-ca49247c8484](https://user-images.githubusercontent.com/49092250/210128754-60224822-08e7-4140-b61f-9a494d2c1d96.png)
![d37415e4-092e-4479-9f7e-c0ecb6d31cef](https://user-images.githubusercontent.com/49092250/210128772-b9f1aeae-0dc0-456a-899b-131ae873704c.png)

**Comment by My12123** [comment]
The original text was not completely deleted. How do I fix this?

**Comment by My12123** [comment]
![2022-12-31_10-22-03](https://user-images.githubusercontent.com/49092250/210128872-1010327f-76a2-442b-b62d-13103c51fafd.png)

**Comment by My12123** [comment]
![2022-12-31_10-22-53](https://user-images.githubusercontent.com/49092250/210128902-6edc9ba0-2ae4-44be-ae14-d6a7968ad8bf.png)

**Comment by crotron** [comment]
> It would appear that all it took was decreasing the aspect ratio tolerance when merging. Please verify for yourself that it works now laughing

Thank you! Yes, the error is gone now. I have also tested a bunch of other images that were previously giving me the same error and it is no longer crashing anymore.

**Comment by thatDudo** [comment]
@My12123 have you ran `git pull`? These artifacts stems from your chosen detector. Remove `--use-ctd` to get rid of them (always try both).
