### ISSUE TITLE
The online version is different from the local one. Will this be corrected?

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#148]
The online version is different from the local one. Will this be corrected?
![2022-12-30_11-29-30](https://user-images.githubusercontent.com/49092250/210050782-2265a18f-1363-4b27-80e1-2d2346d4b49d.png)
![2022-12-30_11-22-40](https://user-images.githubusercontent.com/49092250/210050792-d31ff01d-f450-4554-ab39-4a0389e521bf.png)

**Comment by ryanolee** [comment]
The deployed version is likely behind active changes to the project. This will likely be resolved in the next version release. Might be worth reraising an issue to check that all of the changes we have made have not broken the hosted version 🤔 @zyddnys  @thatDudo

**Comment by thatDudo** [comment]
New docker image is being built. @zyddnys will have to pull it on his server then.

**Comment by zyddnys** [comment]
The online demo is always behind, i will fix this tonight.
