### ISSUE TITLE
Translation into Russian deepl does not work. How to fix it?

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#155]
Translation into Russian deepl does not work. How to fix it?
![2022-12-30_13-12-30](https://user-images.githubusercontent.com/49092250/210059243-1d857c89-1e79-42ff-baa5-e779de64e5ed.png)

**Comment by thatDudo** [comment]
To debug the problem you would need to have an API key (I dont have one). I'm afraid for the time being you will have to use another translator.

**Comment by purpleraven** [comment]
@thatDudo for me everithing works fine.
Probably @My12123 using trial account with different endpoint

**Comment by thatDudo** [comment]
Ah ok then I will close it. Thanks for letting me know :blush:
