### ISSUE TITLE
可以考虑下添加批量翻译和东南亚语种

### ISSUE THREAD

**Issue by iseeyo** [zyddnys/manga-image-translator#16]
可以考虑下添加批量翻译和东南亚语种

**Comment by zyddnys** [comment]
东南亚语种支持指的是识别东南亚语种还是翻译到东南亚语种
至于批量翻译可以使用web模式然后提交多个图片就可以实现自动批量翻译了，不过要实现批量翻译加速目前还做不到，这要等到使用TensorRT加速的C++版本出来就可以做到
