### ISSUE TITLE
ConnectionResetError: [WinError 10054] Remote host forcibly terminates an existing connection

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#164]
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
![2023-01-01_11-58-47](https://user-images.githubusercontent.com/49092250/210165710-bfa1da2c-687d-41eb-bc14-8517e36f98d9.png)

**Comment by thatDudo** [comment]
You probably got ratelimited by google, if I had to guess. Or maybe its just some temporary problem with your internet.
