### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (2,1023,341) (2,1024,341) (2,1023,341)

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#166]
ValueError: operands could not be broadcast together with shapes (2,1023,341) (2,1024,341) (2,1023,341)
![2023-01-02_10-13-05](https://user-images.githubusercontent.com/49092250/210202957-f6bc13ea-f102-4645-afe2-a5a7ce043250.png)

**Comment by My12123** [comment]
how to fix it?

**Comment by dmMaze** [comment]
can you provide the input image?

**Comment by My12123** [comment]
![input](https://user-images.githubusercontent.com/49092250/210225980-0b3a5bdf-9c80-4a41-af87-ef40cf723be5.png)
![2023-01-02_14-33-56](https://user-images.githubusercontent.com/49092250/210225973-b73ac62f-f4f1-4257-9393-3035d789ea43.png)

**Comment by My12123** [comment]
![2023-01-02_14-34-39 (2)](https://user-images.githubusercontent.com/49092250/210226508-26305473-56f1-4b13-b674-790737027862.png)

**Comment by dmMaze** [comment]
The ValueError shall be resolved after [9b5b18f](https://github.com/zyddnys/manga-image-translator/pull/167/commits/9b5b18f870ac7f54cd5b1ae4c2c59f1d65e8a30d) is merged.
And I recommend set resolution to 1024~1536px for this image.
