### ISSUE TITLE
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\imgwarp.cpp:1724: error: (-215:Assertion failed) dst.cols < SHRT_MAX && dst.rows < SHRT_MAX && src.cols < SHRT_MAX && src.rows < SHRT_MAX in function 'cv::remap'

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#168]
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\imgwarp.cpp:1724: error: (-215:Assertion failed) dst.cols < SHRT_MAX && dst.rows < SHRT_MAX && src.cols < SHRT_MAX && src.rows < SHRT_MAX in function 'cv::remap'
![2023-01-02_14-01-45](https://user-images.githubusercontent.com/49092250/210222804-1ad025b4-a226-4610-a635-caee99dd8d58.png)
how to fix it?
![2023-01-02_14-05-35](https://user-images.githubusercontent.com/49092250/210223177-b073ae50-9a13-4201-8fcf-dadea2a3043d.png)
![134710_26284520](https://user-images.githubusercontent.com/49092250/210223193-9f64ce16-cfec-489f-bd15-0d1937ffd886.jpg)

**Comment by thatDudo** [comment]
Resolved in #167
