### ISSUE TITLE
ModuleNotFoundError: No module named 'readline'

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#171]
![2023-01-05_14-59-48](https://user-images.githubusercontent.com/49092250/210775694-387fb071-92b9-4159-8e00-323744128d6d.png)
How to fix?

**Comment by thatDudo** [comment]
Ughh, Apparently the readline module isnt supported on windows,,,
If have pushed a temporary error catch thanks for letting me know.

**Comment by My12123** [comment]
My team helped me  `python -m pip install pyreadline` but then a new mistake came along #172
