### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'Callable'

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#172]
![2023-01-05_16-02-59](https://user-images.githubusercontent.com/49092250/210786341-509125dd-d992-4b52-8809-be3567e264a0.png)
How to fix?

**Comment by thatDudo** [comment]
Was it fixed with the previous commit?

**Comment by My12123** [comment]
![2023-01-05_17-04-39](https://user-images.githubusercontent.com/49092250/210798469-97765f86-13a1-4798-9a9c-5bf83dcadb5a.png)
![2023-01-05_17-04-47](https://user-images.githubusercontent.com/49092250/210798491-4ffa86dd-dac4-4ce0-8527-029319905366.png)

**Comment by thatDudo** [comment]
The pyreadline seems to not have the needed capabilities. I will have to find an alternative method for windows.
