### ISSUE TITLE
IndexError: boolean index did not match indexed array along dimension 0; dimension is 3340 but corresponding boolean dimension is 1024 How to fix?

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#175]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 3340 but corresponding boolean dimension is 1024
![2023-01-05_22-32-51](https://user-images.githubusercontent.com/49092250/210865206-d3c1ca7e-0772-405d-b718-62694ff9065d.png)
![2023-01-05_22-33-04](https://user-images.githubusercontent.com/49092250/210865224-e2eaa5e6-4b33-4903-aa28-87696435d76b.png)

**Comment by My12123** [comment]
![210851559-d919c3f0-ff05-4bb1-8b40-dbce9c5be538](https://user-images.githubusercontent.com/49092250/210876364-54803d49-0f71-4f4b-9b2e-416ef2d22e3d.png)

**Comment by thatDudo** [comment]
Cant reproduce. What are your command line options?

**Comment by My12123** [comment]
![2023-01-06_00-02-40](https://user-images.githubusercontent.com/49092250/210879486-43bf8967-85eb-41a5-868a-9f56ae383aff.png)
![2023-01-06_00-04-07](https://user-images.githubusercontent.com/49092250/210879588-3d6ef6e4-afb3-4d02-9a84-4d8cfa5bb945.png)

**Comment by thatDudo** [comment]
I have found the error, apparently I have made a mistake in the detector refactoring, in that the detector the gets executed is always the default detector, not the ctd detector, regardless of what the website option is. Thanks for your help ^w^
