### ISSUE TITLE
Will an API be created for queries?

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#177]
Will an API be created for queries?

**Comment by thatDudo** [comment]
The web mode instantiates two http servers that can act as your API endpoints. The current implementation might need some reworking though, if you have looked at our current API and have any suggestions feel free to share them with us here.

If this answers your question you can close the issue.

**Comment by My12123** [comment]
How to fix?
![2023-01-07_10-56-24](https://user-images.githubusercontent.com/49092250/211140358-89880dc7-0547-4212-a957-da356bba6495.png)
