### ISSUE TITLE
Can you add support of ct2 models?

### ISSUE THREAD

**Issue by bolon667** [zyddnys/manga-image-translator#178]
Not really a issue, just want to see this in original program.
Here a mod: https://drive.google.com/file/d/1qfnJYi8-e6VNCLLeKaEueJcgPfcTa_Og/view?usp=share_link

**Comment by thatDudo** [comment]
if using ct2 is any faster than pytorch we might consider replacing what we have for the sugoi translator. Have you written that code yourself?

**Comment by bolon667** [comment]
Almost. I used your code as a reference and copied part of translation function code from the [yojet server](https://github.com/dreamsavior/yojet-server/blob/main/pys/yojetServerCT2.py) function doTranslate. About performance, ct2 just better, checked ct2 model and JParaCrawl big fairseq model, ct2 - 71s, fairseq 116s.

**Comment by thatDudo** [comment]
Youre right, its so much faster. Thanks for making this :laughing: 
I will merge once I have it ready~
