### ISSUE TITLE
Langdetect isn’t accurate

### ISSUE THREAD

**Issue by singersbalm** [zyddnys/manga-image-translator#184]
Langdetect isn’t accurate with short texts and can detect the wrong language. I would suggest to use langrid.

langid.classify(text)[0] would be the equivalent for detect(text)

**Comment by thatDudo** [comment]
Thanks for the suggestion, after testing it indeed seems to be more accurate. :+1:

**Comment by thatDudo** [comment]
I am just a little bit worried about the langid repo not having gotten any updates since 2017

**Comment by singersbalm** [comment]
Grammar doesn’t change that fast ;D

**Comment by thatDudo** [comment]
Youre right xD just expected thing to evolve to increase the accuracy. Another thing is that it doesnt distinguish between traditional and simplified chinese, but whatever.
If some new better library appears we'll just switch to that.
