### ISSUE TITLE
No text regions were detected - Skipping How to fix?

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#185]
How to fix?
![2023-01-11_12-29-07](https://user-images.githubusercontent.com/49092250/211770338-bf947eb1-ff80-49ea-9f1d-73193e7067b4.png)

**Comment by thatDudo** [comment]
The detector isnt trained on such small sized images, it is specifically for translating mangas. If you want to get better translation results you will probably have to turn to alternatives.
Maybe in the future we could try to employ detectors trained specifically for such small sizes.

**Comment by JustFrederik** [comment]
You could add white borders to each site, translate it and crop the image.

**Comment by thatDudo** [comment]
Yea I had that idea as well, Im currently testing that approach and its working much better

**Comment by thatDudo** [comment]
Ok I made a fix in [3db7248](https://github.com/zyddnys/manga-image-translator/commit/3db7248757eb8dcbb8fd5c816ee2c9e4389b30e5). Small-sized image detection should have improved a little bit.

**Comment by JustFrederik** [comment]
manual input of the coordinates, width, height and text direction of a TextBlock could be usefull.

**Comment by thatDudo** [comment]
That would probably warrant a custom editor gui

**Comment by My12123** [comment]
![2023-01-22_09-41-49](https://user-images.githubusercontent.com/49092250/213904051-3ab94be5-a5ee-4401-a38f-867786548dd9.png)

**Comment by thatDudo** [comment]
Seems like on this specific image the default detector decided that there are no textlines. The ctd detector a little better.
![final](https://user-images.githubusercontent.com/58403773/213908044-03a7864c-6430-4a22-b11f-4d0c8e1d1788.png)

**Comment by My12123** [comment]
![bboxes](https://user-images.githubusercontent.com/49092250/213923860-3974b8eb-c056-42e9-a5f6-210b261ecef3.png)
