### ISSUE TITLE
PIL.UnidentifiedImageError: cannot identify image file 'C:\\Users\\***\\AppData\\Local\\Temp\\tmpd2lw1qsf\\0.png'

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#186]
How to fix?
![2023-01-11_15-13-06](https://user-images.githubusercontent.com/49092250/211803639-430bc3c4-d294-45d4-849f-5a67874922d9.png)

**Comment by thatDudo** [comment]
Maybe this is because of an outdated pillow version (Run `pip install --upgrade pillow`).
If this doesnt fix it can you share the image file used?
