### ISSUE TITLE
Error response from daemon: manifest for zyddnys/manga-image-translator:latest not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#187]
Error response from daemon: manifest for zyddnys/manga-image-translator:latest not found: manifest unknown: manifest unknown
How to fix?
![2023-01-11_16-03-56](https://user-images.githubusercontent.com/49092250/211813466-35e67a2b-0b61-4229-8a28-f33012dbe8b9.png)

**Comment by thatDudo** [comment]
I had recently updated the readme regarding that. Use  `zyddnys/manga-image-translator:main`
