### ISSUE TITLE
Speedup project with numba

### ISSUE THREAD

**Issue by singersbalm** [zyddnys/manga-image-translator#188]
You could speed up the project by using just in time compilation. @jit(nopython=True, parallel=True, Cache=True) over a def can be used to speedup code. 

[numba(https://numba.pydata.org/numba-doc/latest/user/jit.html)

**Comment by ryanolee** [comment]
I am not sure how much this would help unfortunately. From what I am aware most of the time consuming components don't actually involve executing Python code but calls to lower level ML libraries that run outside the python context (/ Don't rely on directly interpreting python code to execute). Not sure how significant the speed advantages of using a JIT compiler would work in that case given it would not really target where most of the execution time comes form. Though I do stand to be corrected on that front if that is not the case :laughing:
