### ISSUE TITLE
Text with multiple lines starts with the text in the lowest line and works upwards

### ISSUE THREAD

**Issue by JustFrederik** [zyddnys/manga-image-translator#191]
I got this an result for the text in the image: 么？……是什 啊？前面
It starts to add the sentences from the bottom at the beginning and going up instead of down. Any ideas why it does that? Im not familiar with the chinese grammer so i dont know if this is usually common or why it does that. I would fix it in a few days, but dont know in which file i find it. My guess is that its in textline_merge/__init__.py in the merge function. If i just switch that arround for horizontal text, will i break something. Can someone explain if there is a reason for this bug.
<img width="107" alt="Screenshot 2023-01-12 at 9 01 15 PM" src="https://user-images.githubusercontent.com/121750393/212172743-2644eca9-b7d1-4dc8-a975-398021918705.png">

**Comment by thatDudo** [comment]
You mean that that is the output image you get? The text renderer is automatically determining the text direction of chinese languages from the ratio (width/height) of their detected TextBlock.
Wdym with the text is being rendered from bottom to top? Could be a bug with an incorrect angle...

**Comment by JustFrederik** [comment]
Line 3: 么？
Line2: ……是什
Line1:啊？前面

OUTPUT:么？……是什 啊？前面
Expected output: 啊？前面 ……是什 么？

The image above is the input image. Im not completly certain how your ocr works, but my guess is that you first detect every single char and than concat them. I thought the problem might be caused when the chars are merged to a string. What do you think

**Comment by JustFrederik** [comment]
I found the position where the lines are joined and the problem is that that in model_48px_ctc.py the variable texts(line 90) isnt sorted or there is a bug in the sort.

**Comment by thatDudo** [comment]
If the text is rendered in reverse maybe this is a problem with the textrendering. Can you send me the input image that would speed thing up

**Comment by thatDudo** [comment]
I cant reproduce your problem with the example images from demo/images/ and `-l JPN`.

**Comment by JustFrederik** [comment]
the language is chinese and i cant find the point where the textlines in the texblock are sorted

**Comment by thatDudo** [comment]
Like i said the problem is in the detector.

**Comment by JustFrederik** [comment]
can you tell me where they are sorted?

**Comment by thatDudo** [comment]
There is no specific sorting per se (have a look at detection/default.py:90)
I think the problem lies not in any sorting but in the textlines being too small.

**Comment by JustFrederik** [comment]
i found the code for the sort and the sort works, but is never used. in detetion/textline:merge/__init__.py in merge_bboxes_text_region the nodes variable sets the sorted order, but is never used to sort the textlines. I will make a pull request that changes that

**Comment by zyddnys** [comment]
can you share the image used and arguments?

**Comment by JustFrederik** [comment]
<img width="531" alt="image" src="https://user-images.githubusercontent.com/121750393/212357034-6df31ff5-fc24-4467-9eb1-d97c8f052e70.png">
python translate_demo.py --verbose --use-cuda --translator=offline -l ENG -i /home/user/code/manga-image-translator/image.png  


 -- Rendering translated text
text: 的尾灯而已！那只是汽车 


expected Text: 那只是汽车  的尾灯而已！

**Comment by thatDudo** [comment]
Would have been nice if you had sent it right away when I first asked. Doesnt feel very great to be ignored this way...

**Comment by singersbalm** [comment]
Sorry

**Comment by JustFrederik** [comment]
did i overlook something or was i right?

**Comment by thatDudo** [comment]
Seems like youre solution works well :+1:
