### ISSUE TITLE
what is the detection-size arg

### ISSUE THREAD

**Issue by JustFrederik** [zyddnys/manga-image-translator#194]
what does the detection-size arg stand for. The description says size of image. Does that mean width, height or amount of pixels and why is it needed in the firstplace. Couldnt python just figure out the size itself? Or is it the size of the text?

**Comment by zyddnys** [comment]
It limits the maximum side of an image fed into detection module to `detection-size`

**Comment by JustFrederik** [comment]
Why don’t you replace the value with max(width, height)

**Comment by zyddnys** [comment]
detection module is trained with a range of detection resolution, from 1024 to 2560, if i use `max(width, height)`, what happens if some one put in an image with 100000x1000000 resolution?

**Comment by JustFrederik** [comment]
Is it only trained for 1024,153, 2048 and 2560 or 1024-2560. If it’s trained on the range you could use something like this min(max(1024, max(width, height)),2560)

**Comment by JustFrederik** [comment]
What would happen if you use a 100000x1000000 image with the settings of only 2560?

**Comment by QiroNT** [comment]
> What would happen if you use a 100000x1000000 image with the settings of only 2560?

@JustFrederik It would be scaled down to 256x2560 before being fed into detection.

**Comment by QiroNT** [comment]
The detection size should be relevant to the proportion of the texts to the image. Eg. larger detection size for relatively small fonts and smaller size for relatively large fonts. So a "width of image" wouldn't do you a favor in some cases.

**Comment by JustFrederik** [comment]
Wouldnt it make sense to run it for all sizes and merge it then? Texts could have different sizes even within one image

**Comment by JustFrederik** [comment]
the image isn’t scaled down in the code and it couldn’t detect anything if it would be scaled down. If you take an extremely long image for example. If it would be scaled down it would have a tiny width and the chars wouldn’t be redible. Is the detection size linked linked to the image width and height or would it behave completely the same when you would add 10000px to each site of an image?

**Comment by thatDudo** [comment]
@JustFrederik To your first question, no because you would have no way to filter out the garbage output of the detector.
About your second question, we had a pull request that fixed extreme aspect ratios here: #146 .
Also as it was already mentioned the image is scaled down in the detector so it wouldnt work very well with extreme image sizes.

 I dont understand why you ask these questions here if you could just look it up in the code?
