### ISSUE TITLE
Manual Translate UI with manga2eng cannot render special characters

### ISSUE THREAD

**Issue by TCO-Github** [zyddnys/manga-image-translator#195]
When using the Manual Translate UI in web mode with manga2eng enabled, text rendering cannot render special characters like hearts  ♥.

Original2.jpg Input:
![image](https://user-images.githubusercontent.com/122240660/212552605-87b2de5e-f959-4341-b441-cdfe19666064.png)

Original2.jpg Output:
![image](https://user-images.githubusercontent.com/122240660/212552657-4d515957-05f2-48ea-b57d-a9f08a807798.png)

Original2.jpg Output **with manga2eng disabled**:
![image](https://user-images.githubusercontent.com/122240660/212552902-8785507e-473e-4c6c-999e-b978f014455c.png)

**Comment by thatDudo** [comment]
Sorry it took so long. I had to change quite a lot of things.
