### ISSUE TITLE
Can you do automatic upgrade?

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#196]
Can you do automatic upgrade?
So that every time you change, you do not have to clone the repository and maintain the current version.

**Comment by thatDudo** [comment]
Implementing an automatic updater would not make much sense at the current state of the project.
First of all there is limited use for something like that considering that using git pull is fairly convinient and we dont have nor maintain a release schedule.
Secondly, I would prefer integrating this project into pip to making an updater as it requires less work and provides as a sideeffect a simpler way for developers to interface with the library.

**Comment by My12123** [comment]
@thatDudo Can I ask when you will do it through pip?

**Comment by thatDudo** [comment]
Once Im finished with #195 I can try to work on it

**Comment by My12123** [comment]
#195 already closed 3 days ago, did you forget about the automatic update?

**Comment by thatDudo** [comment]
im still working on it senpai

**Comment by thatDudo** [comment]
Pip is not going to automatically update your version you will still have to manually run the command.
You can use run.bat instead which will call `git pull` before every time you run the translator.

**Comment by My12123** [comment]
#212
