### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#197]
Namespace(mode='demo', image='', image_dst='', target_lang='CHS', verbose=False, host='127.0.0.1', port=5003, log_web=False, detector='default', ocr='48px_ctc', inpainter='lama_mpe', translator='google', mtpe=False, use_cuda=False, use_cuda_limited=False, detection_size=1536, det_rearrange_max_batches=4, inpainting_size=2048, unclip_ratio=2.3, box_threshold=0.7, text_threshold=0.5, text_mag_ratio=1, font_size_offset=0, force_horizontal=False, force_vertical=False, upscale_ratio=None, manga2eng=False, font_path='')
 -- Preload Checks
Traceback (most recent call last):
  File "/app/translate_demo.py", line 375, in 
    loop.run_until_complete(main(args.mode))
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/translate_demo.py", line 278, in main
    raise FileNotFoundError(args.image)
FileNotFoundError

**Comment by thatDudo** [comment]
You have not supplied the `-i` argument. Please read the error message next time.

**Comment by thatDudo** [comment]
Though I admit that it is not completely obvious, because the argument is optional even in demo mode.
