### ISSUE TITLE
TypeError?

### ISSUE THREAD

**Issue by kdrkdrkdr** [zyddnys/manga-image-translator#20]
![image](https://user-images.githubusercontent.com/49074597/130096523-54331ea9-2f2a-41d3-8b95-50fc80172ade.png)

This problem solved with '--size 1024'. 
The recognition rate is low. The same error occurs in some other images.
Is there a way not to get this error without "--size 1024" option?
I attached the used image.

![proseka](https://user-images.githubusercontent.com/49074597/130096687-ea6120df-55fc-45e7-b493-806602a8240a.jpg)

**Comment by kdrkdrkdr** [comment]
Thank you for fixing it.
I've found one more error.
This is the 'original4.jpg' file.

My Command line -->  translate_demo.py --mode web --use-inpainting --use-cuda

I don't know what to do, but can you check it one more time?
![image](https://user-images.githubusercontent.com/49074597/130173649-48d6d982-b13f-4893-aa36-590b44114340.png)

**Comment by zyddnys** [comment]
I was unable to reproduce this, does this happen every time? does it only happen to 'original4.jpg'?

**Comment by kdrkdrkdr** [comment]
At least that's one of the pictures I tested. This was also solved with the '--size 1024' option.

**Comment by zyddnys** [comment]
I have updated the code, let me know if the problem still persists.

**Comment by kdrkdrkdr** [comment]
Thanks to solve this problem:)
