### ISSUE TITLE
IndexError: index 6 is out of bounds for axis 0 with size 6

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#202]
![2023-01-28_16-40-44](https://user-images.githubusercontent.com/49092250/215269567-6ff52b91-5aba-433a-9703-ea705d1a3a7f.png)

**Comment by zyddnys** [comment]
can you provide the image and argument you are using so we can reproduce this error?

**Comment by My12123** [comment]
![2023-01-28_18-29-26](https://user-images.githubusercontent.com/49092250/215274989-09e0cf1b-a4ba-4324-8337-2acc55524d72.png)
![2023-01-28_18-30-28](https://user-images.githubusercontent.com/49092250/215275035-e2212f10-b401-42d9-82b7-961f75a556f0.png)

![138032_26632034](https://user-images.githubusercontent.com/49092250/215275190-2ea10452-e25e-400e-80b1-86330566715b.jpg)

**Comment by thatDudo** [comment]
Seems like a problem with the line sorting in the default text detector. Will add a fix soon.
