### ISSUE TITLE
dataset for detection

### ISSUE THREAD

**Issue by singersbalm** [zyddnys/manga-image-translator#205]
What dataset did you use for the detection?

**Comment by dmMaze** [comment]
You may refer to #25 or https://github.com/dmMaze/comic-text-detector
Known issue: #96

**Comment by JustFrederik** [comment]
thanks, but i meant the images, etc that where used. Its said that danbooru2020, coco and imagenet, and manga109 were used. manga109 makes sense, danbooru2020 doenst have any text(only art) so i dont know how it could be used for ocrs and coco and imagenet are only objects and not manga/anime related

**Comment by singersbalm** [comment]
thanks, but i meant the images, etc that where used. Its said that danbooru2020, coco and imagenet, and manga109 were used. manga109 makes sense, danbooru2020 doenst have any text(only art) so i dont know how it could be used for ocrs and coco and imagenet are only objects and not manga/anime related

**Comment by dmMaze** [comment]
They serve as background with text rendering upon them, as mentioned in #25
