### ISSUE TITLE
After 21/01 updates many tasks returns error status 

### ISSUE THREAD

**Issue by purpleraven** [zyddnys/manga-image-translator#207]
After 21/01  many tasks returning wrong status after completion (around 80%)

In the file system I see translated task_id/final.png file , nothing in the log, but /task-state?taskid=XXX returns
 ```
{"state": "error"}
```

**Comment by thatDudo** [comment]
Cant reproduce your bug, can you send and input image that fails?

**Comment by purpleraven** [comment]
Can it be a problem with resubmitted same file? I see, task id is a hash of file content.

**Comment by thatDudo** [comment]
Thats what i tested for when trying to reproduce. Maybe try to delete the saved folder with final.png and see if it reappears...

**Comment by purpleraven** [comment]
I have added check, for ERROR status I looking to file system. At result, only 8 from 450 has no file. 
I have added logs, cleaned up file system and will wait for the problem in the future.

How you are checking status of task? Maybe you will change it to file system check? File exist and not empty.

**Comment by thatDudo** [comment]
We are checking if final.png exists if not run translation. Like I said it works on my system

**Comment by purpleraven** [comment]
Some how I have seen many false negativs on my setup. More then 400 cases.

Will check on fresh installation

**Comment by thatDudo** [comment]
Is the web mode fixed for you now? We have changed some parts of the code so it might be better.
Then I can close this issue..

**Comment by purpleraven** [comment]
@thatDudo with current docker image problem still exist

**Comment by thatDudo** [comment]
I published a new docker image.

**Comment by purpleraven** [comment]
will check. by the way, the image size again more then 15G

**Comment by thatDudo** [comment]
I have analyzed the disk usage of the docker image and most of it seems to stem from torch, cuda and some conda packages.
The models we use only are like 7 gb.

**Comment by purpleraven** [comment]
looks like fixed. Thx
