### ISSUE TITLE
请教关于尺码图的优化建议

### ISSUE THREAD

**Issue by jaric** [zyddnys/manga-image-translator#21]
你好。

尝试翻译几张尺码图(简转繁)，但效果仍不够好(特别是表格内的文字容易跑版)。请问有什么建议吗？

如果需要是加强模型的辨识能力，可否提供文件指引，我可以收集训练集及训练模型在反馈给这个专案。

谢谢

原图:
<a href="https://imgur.com/RCAVa1V"><img src="https://i.imgur.com/RCAVa1V.jpg" title="source: imgur.com" /></a>

处理过后的：
<a href="https://imgur.com/Ny4Iov3"><img src="https://i.imgur.com/Ny4Iov3.jpg" title="source: imgur.com" /></a>

**Comment by jaric** [comment]
更多例子:

- 原图:
<a href="https://imgur.com/ovivIMu"><img src="https://i.imgur.com/ovivIMu.png" title="source: imgur.com" /></a>
- 处理过后的
<a href="https://imgur.com/G8Ubh0D"><img src="https://i.imgur.com/G8Ubh0D.png" title="source: imgur.com" /></a>


- 原图:
<a href="https://imgur.com/a70OuDZ"><img src="https://i.imgur.com/a70OuDZ.jpg" title="source: imgur.com" /></a>
- 处理过后的
<a href="https://imgur.com/RVHVdBZ"><img src="https://i.imgur.com/RVHVdBZ.png" title="source: imgur.com" /></a>

- 原图:
<a href="https://imgur.com/Vv4KSVr"><img src="https://i.imgur.com/Vv4KSVr.jpg" title="source: imgur.com" /></a>
- 处理过后的
<a href="https://imgur.com/ajPpx2w"><img src="https://i.imgur.com/ajPpx2w.png" title="source: imgur.com" /></a>

**Comment by zyddnys** [comment]
这个程序主要针对漫画设计，所以会出现多行文本被合并。你这个情况可以完全不需要文本行合并。
为了尽量保留背景内容，可能会导致部分文本不被涂干净。你这个情况可以完全涂改整个文字区域。
我开个新分支给你看下效果。

**Comment by jaric** [comment]
理解，感谢回覆。

我可以准备需要的训练资料及准备合适的文本检测器。请问该如何重新训练文本检测器呢？可不可以给我一些指引呢？

完成之后，会提供给大家一起开源使用。

谢谢

**Comment by zyddnys** [comment]
目前检测器训练使用的是纯合成数据，代码比较混乱，之所以没检测到列出的文字是因为合成数据时所有文字均类似漫画那样大块出现。
重构和写训练文档要一段时间。
如果你这边比较急着我可以试着把其他现成的开源的中文检测器整合进项目作为一个选项。例如https://github.com/DayBreak-u/chineseocr_lite

**Comment by jaric** [comment]
好的，非常谢谢你的帮忙。

顺着你提供的 github 链结找到了 [chinese_ocr](https://github.com/YCG09/chinese_ocr)，请问透过这个 repo 指引的方式，训练出来的模型能够直接搭配使用吗？如果可以的话，我也可以同步进行，提供一些帮助。

- 提供训练文档
- 提供更新之后的文本检测器

**Comment by zyddnys** [comment]
我重构了项目，我正在尝试将现成的https://github.com/DayBreak-u/chineseocr_lite整合进项目，这样你就可以使用别人训练好的检测器而不用自己花时间训练了。

**Comment by zyddnys** [comment]
> 好的，非常谢谢你的帮忙。
> 
> 顺着你提供的 github 链结找到了 [chinese_ocr](https://github.com/YCG09/chinese_ocr)，请问透过这个 repo 指引的方式，训练出来的模型能够直接搭配使用吗？如果可以的话，我也可以同步进行，提供一些帮助。像是提供训练文档及不同情境的文本检测器。

这边确认了以下， [chinese_ocr](https://github.com/YCG09/chinese_ocr)提供的训练方式确实可行，未来我会把他的模型整合进项目里。

**Comment by jaric** [comment]
感谢帮忙。那我先等整合进项目之后，再来继续测试。
