### ISSUE TITLE
I can't use the CPU instead of CUDA

### ISSUE THREAD

**Issue by Lufims** [zyddnys/manga-image-translator#213]
I tried this command `python -m manga_translator -v --use-cpu --translator=google -l ENG -i` but it didn't work because it didn't recognized the "--use-cpu" flag, and I can't use cuda becuase I don't have a graphic card, and I thought that I could use the cpu because pytorch has a cpu option.

**Comment by thatDudo** [comment]
If --use-cuda is not set it means cpu.
