### ISSUE TITLE
How I limit the cpu memory allocation?

### ISSUE THREAD

**Issue by Lufims** [zyddnys/manga-image-translator#214]
I'm running it with the terminal and it says an error because my pc sucks,
`[demo] Namespace(mode='demo', input='../../Desktop/imagem.jpg', dest='', target_lang='ENG', verbose=True, detector='default', ocr='48px_ctc', inpainter='lama_mpe', translator='offline', use_cuda=False, use_cuda_limited=False, detection_size=1536, det_rearrange_max_batches=4, inpainting_size=2048, unclip_ratio=2.3, box_threshold=0.7, text_threshold=0.5, text_mag_ratio=1, font_size_offset=0, force_horizontal=False, force_vertical=False, upscale_ratio=None, manga2eng=False, mtpe=False, font_path='', host='127.0.0.1', port=5003, log_web=False, ws_url='ws://localhost:5000')
[demo] Running in demo mode
[demo] Loading models
[demo] -- Running text detection

ERROR: [demo] RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 14155776 bytes.`

and I wanted to know if have some way to use less memory.

**Comment by Lufims** [comment]
Nevermind, I used --detection-size flag with the value of 1 and even with this value it didn't work

**Comment by thatDudo** [comment]
If you were on linux you could probably increase you swap size so at least it wouldnt crash, but i dont see much point in that if your computer is too slow.
