### ISSUE TITLE
Why are the lyrics so different? 

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#215]
original
![input](https://user-images.githubusercontent.com/49092250/219581612-9d146425-a125-49b0-a943-303a3b419132.png)
bboxes
![bboxes](https://user-images.githubusercontent.com/49092250/219581703-cb1dee28-6e51-4b97-8062-5d2497391d33.png)
final
![final](https://user-images.githubusercontent.com/49092250/219581790-d7f7e28f-4d13-4c5d-b33e-b048b65af1b3.png)

![2023-02-17_10-43-19](https://user-images.githubusercontent.com/49092250/219581905-9a4f2639-0e52-4b87-8c0f-2bd11dafd4fd.png)

**Comment by thatDudo** [comment]
What do you mean lyrics? It looks fine to me.

**Comment by My12123** [comment]
![2023-02-17_22-46-08](https://user-images.githubusercontent.com/49092250/219775808-4169c5cd-a9ac-45bb-bb6e-7283f70b7b66.png)
![2023-02-17_22-46-55](https://user-images.githubusercontent.com/49092250/219775853-95e24e2a-61e2-4527-bb5e-a84f52b1c120.png)
Far from the text
