### ISSUE TITLE
Why does the image not increase waifu2x?

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#216]
![2023-02-17_10-49-29](https://user-images.githubusercontent.com/49092250/219583685-72e97009-9108-4890-bfa3-f882b6720414.png)
![2023-02-17_10-49-57](https://user-images.githubusercontent.com/49092250/219583728-e15793e4-2a1d-4bc9-8dd5-e1131a4437e4.png)
![2023-02-17_10-50-28](https://user-images.githubusercontent.com/49092250/219583741-725d0334-b20b-43bd-877d-f963d3d701a7.png)

**Comment by thatDudo** [comment]
Try --upscale-ratio 2

**Comment by My12123** [comment]
I use -mode web

**Comment by thatDudo** [comment]
It works together with --mode web if that was what you were wondering about.
