### ISSUE TITLE
Can't start new docker image

### ISSUE THREAD

**Issue by purpleraven** [zyddnys/manga-image-translator#217]
Just pulled the new version, but web server not started. I see in the logs:
```
/opt/conda/bin/python: No module named /app/manga_translator
/opt/conda/bin/python: No module named /app/manga_translator
```

**Comment by thatDudo** [comment]
Thanks for telling. I think I have fixed it with the new current build. (You can probably tell I dont use docker too much myself .-.)

**Comment by purpleraven** [comment]
@thatDudo works. Thx
