### ISSUE TITLE
cv2.error : OpenCV(4.5.3): error (-5:Bad argument) in function 'warpPerspective'

### ISSUE THREAD

**Issue by kdrkdrkdr** [zyddnys/manga-image-translator#23]
This has been happening for a few days now, 
What version is opencv-python?

![image](https://user-images.githubusercontent.com/49074597/131423931-baa850de-0bda-4dba-9e6a-0c2fdf29d3cb.png)

**Comment by zyddnys** [comment]
I tried to fix it in d490196802ad907f05e37017c13fbdd0964144fa, let me know if the problem persists

**Comment by kdrkdrkdr** [comment]
I solved this problem.. it was numpy version update problem.
