### ISSUE TITLE
WARNING: [web] No text regions with text! - Skipping

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#230]
![2023-02-26_17-36-55](https://user-images.githubusercontent.com/49092250/221417166-2de2b63f-c063-4161-a7d1-42eda841a1f7.png)
![2023-02-26_17-38-53](https://user-images.githubusercontent.com/49092250/221417239-893d12d0-74d8-4770-a8c4-59280510a7f0.png)
![608f1226f579e1af9f95e3cdfb42685d](https://user-images.githubusercontent.com/49092250/221417114-d9b8567e-79c9-457d-84e6-abbd36f8bf36.jpeg)

**Comment by thatDudo** [comment]
Try --upscale-ratio 2. Our ocr has problems with low res text.
If you want to keep the image size you can use --downscale to remove the upscaling.
