### ISSUE TITLE
ERROR: [batch] AttributeError: module 'shapely' has no attribute 'affinity'

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#235]
![2023-03-04_18-01-30](https://user-images.githubusercontent.com/49092250/222913319-29717cfc-3bc1-430e-a203-16cf6065e2c8.png)

**Comment by TheLastCreation** [comment]
also getting the above error, can confirm its something in the latest commit as reverting once to commit 4f9b99ce9087bb799018c2b753bced76b9f4c553 I don't receive the error

**Comment by thatDudo** [comment]
Sorry about that. Seems like shapely is a little unreliable to install so I will remove the dependency.
