### ISSUE TITLE
Small Image Detection Error..?

### ISSUE THREAD

**Issue by kdrkdrkdr** [zyddnys/manga-image-translator#24]
![image](https://user-images.githubusercontent.com/49074597/131544525-c16b88b6-6bbf-436a-916b-a8d099ba067a.png)

I attach the two pictures that I used when this error occurred in url below.

http://comiciwate.jp/comic/images/profile_title.gif
http://comiciwate.jp/img/common/bnr_iwateken.jpg

**Comment by zyddnys** [comment]
It wouldn't work on too small images, please resize it to at least 128x128
