### ISSUE TITLE
manga_translator: error: unrecognized arguments

### ISSUE THREAD

**Issue by Harese** [zyddnys/manga-image-translator#248]

**Comment by thatDudo** [comment]
You can read the usage section in the readme

**Comment by Harese** [comment]
Thank you. I've replaced this with my path. 'python -m manga_translator --verbose --use-cuda --translator=google --target-lang=CHS --image <path_to_image_file>'. But an error is reported. 'manga_translator: error: unrecognized arguments'.

**Comment by thatDudo** [comment]
Replace <path_to_image_file> with an actual path.

**Comment by Harese** [comment]
是的，我已经替换成了真实路径，尝试了各种格式，但是依然报错

**Comment by Harese** [comment]
Yes, I have replaced the real path, tried various formats, but still got an error

**Comment by thatDudo** [comment]
It seems the chinese readme was outdated, thanks for pointing that out. You have to use -i not --input

**Comment by Harese** [comment]
Oh, I'll try. Thank you!
