### ISSUE TITLE
Feature Request: New Facebook Translation Model

### ISSUE THREAD

**Issue by oromis995** [zyddnys/manga-image-translator#249]
I am not familiar with your codebase enough to make the change myself yet, I'm sorry. I don't know if you are interested, but Facebook has released open source models for translation:

https://github.com/facebookresearch/fairseq/tree/main/examples/m2m_100

Thank you for your hard work!

**Comment by thatDudo** [comment]
Thanks for the suggestion, seems like this is the superior version of nllb. Ill work on adding it.
