### ISSUE TITLE
 cannot write mode RGBA as JPEG

### ISSUE THREAD

**Issue by AiYouWei** [zyddnys/manga-image-translator#250]
![image](https://user-images.githubusercontent.com/6127240/224642883-047dd179-1ff2-4634-91b0-8846cc7ea8d5.png)

**Comment by zyddnys** [comment]
jpeg本来就不支持alpha通道啊

**Comment by AiYouWei** [comment]
能不能兼容一下呀 出现这个 batch任务就退出了 想继续执行后面的任务
