### ISSUE TITLE
Image not translated. How to fix?

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#251]
![010](https://user-images.githubusercontent.com/49092250/224767916-61382840-05ad-45cf-8ae7-7f6635182b7a.jpg)
![2023-03-13_19-41-41](https://user-images.githubusercontent.com/49092250/224768395-34de9503-c447-48fa-909a-fc6f8bb263e5.png)

**Comment by thatDudo** [comment]
Both of our detectors arent picking up much of anything here, even with different configurations I tried..

**Comment by My12123** [comment]
Can this be fixed, or do you need a new detector model?

**Comment by thatDudo** [comment]
New detector models

**Comment by My12123** [comment]
When’s the new model coming?

**Comment by thatDudo** [comment]
I myself dont have enough experience yet to create my own models.

**Comment by Omicronlawful** [comment]
@thatDudo why don’t you close the spam of @My12123

**Comment by thatDudo** [comment]
You got to admit it is quite hillarious

**Comment by Omicronlawful** [comment]
Yeah, he created 80 of 220 issues. Like how. do you use is:issue is:open -author:my12123 to see relevant issues?

**Comment by thatDudo** [comment]
I mean it would probably be nice to have them all at one point instead of spread out to different issues... I will close the duplicates for now.
