### ISSUE TITLE
ERROR: [batch] OSError: cannot write mode P as JPEG

### ISSUE THREAD

**Issue by AiYouWei** [zyddnys/manga-image-translator#253]
When this error appears,the bach task will be interruptted,is there a way to let the task continue?

**Comment by AiYouWei** [comment]
能不能兼容一下呀 出现这个 batch任务就退出了 想继续执行后面的任务

**Comment by thatDudo** [comment]
I shouldve fixed it in the linked commit

**Comment by AiYouWei** [comment]
![image](https://user-images.githubusercontent.com/6127240/232170193-662320cc-f686-45b1-a3c9-6db3d51710f7.png)
![image](https://user-images.githubusercontent.com/6127240/232170332-6b3d6db1-d619-4b47-b8d3-656a7c09473f.png)
这个也兼容一下呗
