### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#259]
(mt) F:\manga-image-translator>pip install git+https://github.com/lucasb-eyer/pydensecrf.git
Collecting git+https://github.com/lucasb-eyer/pydensecrf.git
  Cloning https://github.com/lucasb-eyer/pydensecrf.git to c:\users\tchot\appdata\local\temp\pip-req-build-iz4m23dc
  Running command git clone --filter=blob:none --quiet https://github.com/lucasb-eyer/pydensecrf.git 'C:\Users\tchot\AppData\Local\Temp\pip-req-build-iz4m23dc'
  Resolved https://github.com/lucasb-eyer/pydensecrf.git to commit 0d53acbcf5123d4c88040fe68fbb9805fc5b2fb9
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pydensecrf
  Building wheel for pydensecrf (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pydensecrf (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\pydensecrf
      copying pydensecrf\utils.py -> build\lib.win-amd64-cpython-310\pydensecrf
      copying pydensecrf\__init__.py -> build\lib.win-amd64-cpython-310\pydensecrf
      running build_ext
      building 'pydensecrf.eigen' extension
      creating build\temp.win-amd64-cpython-310
      creating build\temp.win-amd64-cpython-310\Release
      creating build\temp.win-amd64-cpython-310\Release\pydensecrf
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Ipydensecrf/densecrf/include -Ipydensecrf -IF:\1\envs\mt\include -IF:\1\envs\mt\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /EHsc /Tppydensecrf/eigen.cpp /Fobuild\temp.win-amd64-cpython-310\Release\pydensecrf/eigen.obj
      eigen.cpp
      F:\1\envs\mt\include\pyconfig.h(59): fatal error C1083: ЌҐ г¤ Ґвбп ®вЄалвм д ©« ўЄ«озҐ­ЁҐ: io.h: No such file or directory,
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pydensecrf
Failed to build pydensecrf
ERROR: Could not build wheels for pydensecrf, which is required to install pyproject.toml-based projects

**Comment by Snowad14** [comment]
Download wheel from `https://www.lfd.uci.edu/~gohlke/pythonlibs/#pydensecrf` then pip install <path to .whl>

**Comment by JustFrederik** [comment]
Use docker!!!
