### ISSUE TITLE
OMP: Error

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#262]
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

**Comment by My12123** [comment]
@thatDudo

**Comment by thatDudo** [comment]
What was the command you ran?

**Comment by My12123** [comment]
![2023-03-21_11-44-45](https://user-images.githubusercontent.com/49092250/226555797-e591e08d-f0b6-47d3-a82e-b58f516693c9.png)
`python -m manga_translator -v --mode web --use-cuda --font-size-offset=10 --font-path=fonts/anime_ace.ttf`

**Comment by thatDudo** [comment]
Maybe try reinstalling the dependencies with `pip install -r requirements.txt -U --force-reinstall`

**Comment by My12123** [comment]
didn't help

**Comment by My12123** [comment]
How to fix it?
@thatDudo @zyddnys

**Comment by JustFrederik** [comment]
my suggestion would be remove the venv and reinstall all dependencies. 

[This error occurs when there are multiple "libiomp5.dll" files within a python interpreter. I fixed it by deleting all of the versions of the file that were not within the module I was using (PyTorch). I would like to point out that this could cause a lot of multiprocessing issues down the road if you don't know what you are doing but I am sure it is nothing that can't be solved by looking it up on StackOverflow.](https://stackoverflow.com/questions/64209238/error-15-initializing-libiomp5md-dll-but-found-libiomp5md-dll-already-initial)
