### ISSUE TITLE
Can't get --manga2eng parameter working under Windows

### ISSUE THREAD

**Issue by raziel2001au** [zyddnys/manga-image-translator#266]
Hi all, I've been testing manga-image-translator on my Mac and it's really awesome, but does run quite slow, so I installed it on my Windows machine (which has an RTX4080 so it's much faster for AI).

For some reason I can't get the --manga2eng parameter working on my Windows machine at all. On the Mac, when you pass this parameter it fills up the speech bubbles properly and capitalises the text. On Windows it's not making any difference to the output from what I can tell. Doesn't switch to all caps and doesn't fill up the speech bubbles like it does on the Mac.

Checking the command prompt, I can see it saying "manga2eng=True" on startup, which suggests that it should work, except, it doesn't. I was thinking maybe it's just caps vs non-caps, so I tried it with --capitalize but it's obvious that the type-setting isn't working.

For reference, this is the exact command I'm using:
```python -m manga_translator -v --detection-size 4096 --mode batch --translator=sugoi -l ENG --manga2eng -i D:\Development\manga-image-translator\input_images```

What am I missing?

**Comment by thatDudo** [comment]
I have wired up something incorrectly when doing refactoring.

**Comment by raziel2001au** [comment]
Awesome, thanks for the update, can you let me know when it's fixed? Thanks!!!

**Comment by thatDudo** [comment]
Since the issue is already closed it should be fixed already...
