### ISSUE TITLE
Translation service based on language

### ISSUE THREAD

**Issue by JustFrederik** [zyddnys/manga-image-translator#267]
- [x] different translation services based on the language
Based on the detected language it uses another translation service.

I dont have much time right now, thats why i am not implementing this feature for now, but i might in a few weeks or month. Just wanted to suggest the feature.

**Comment by thatDudo** [comment]
We already have that for the offline translator. Usually all online translators support all languages with most of them being locked behind an api key requirement so I dont think it makes sense to use it for that..

**Comment by JustFrederik** [comment]
Thats not what i meant. I mean if the detected language is japanese it should use google translate. If it is chinese it uses deepl or whatever

**Comment by thatDudo** [comment]
No that is just chaining translators so that the output of one translator goes in the other. We dont have automatic translator assignment per language for online translator yet.

**Comment by JustFrederik** [comment]
Oh good to know.

**Comment by JustFrederik** [comment]
#269 implemented it
