### ISSUE TITLE
Can you share the compressed font files you have gathered?

### ISSUE THREAD

**Issue by qwopqwop200** [zyddnys/manga-image-translator#27]
I'm sorry, some fonts are not searched by name.I think the font name list is not enough.I'm sorry to bother you, but can you share the compressed font file?
I opened a new issue because I thought it was different from the existing dataset issue.

**Comment by zyddnys** [comment]
Some fonts are licensed so I can't share them publicly, is there a way I can send you data privately?

**Comment by qwopqwop200** [comment]
Can you email me the link after uploading the file to web drive? The email is "qwopqwop200@gmail.com".

**Comment by qwopqwop200** [comment]
Thank you very much. I think I can solve the difficult part thanks to you.
