### ISSUE TITLE
Request for adding new features. 添加新功能的请求

### ISSUE THREAD

**Issue by szsc233** [zyddnys/manga-image-translator#275]
The following content was translated using GPT. Please forgive any inaccuracies.

Can a feature be added to create a new file to store OCR-recognized text, image patch data, and translation data when processing images in bulk? Users can choose whether or not to translate, and can use the OCR function alone if they choose not to translate. This file can then be used to call a new translation API to translate the text, avoiding the need to process the OCR again, or manually modify the translation data in the file for better results. 

能否添加一个功能
在批量处理图片时新建一个文件来储存OCR识别的文字，图片修补数据以及翻译数据。（可以选择是否翻译，不翻译的话就只用OCR提取文字功能）
之后可以利用此文件来调用一个新的翻译API来翻译文本，避免再次使用OCR处理，或者手动修改文件中的翻译数据，达到更好的效果。

**Comment by thatDudo** [comment]
We already have --save-text-file
