### ISSUE TITLE
Rewrite in c++

### ISSUE THREAD

**Issue by JustFrederik** [zyddnys/manga-image-translator#276]
I noticed that you plan to rewrite the code in c++. Why not rust. The performence is similar, but you dont have to worry about memory safty, the error messages are better and it is way easier to setup the enviroment and install packages. Of course it is possible to run c code in rust, so it could be implemented as a combination of both. I dont recomment it, but it is possible

**Comment by thatDudo** [comment]
I assume that was only a rough idea. I personally think that the translator is not reliable enough yet to reimplement it in another language.

**Comment by JustFrederik** [comment]
I tried to run the project in rust using pyo3, but the performance was worse. I’d suggest that some parts of the code could be rewritten like the ocr. It didn’t got much changes for a while and could be imported as a python library. That would increase the performance and the could be used when the code is fully rewritten. I just asked, because it wouldn’t make sense to write/convert a module when you won’t use it in the future.

**Comment by thatDudo** [comment]
No, if someone who is knows how to do it we could add it as an additional upscaler with a name like "32px_ctc_rust" or sth.

**Comment by JustFrederik** [comment]
Wouldn’t that cause problems with fixing bugs. When there is a problem with 32px_ctc? When there are 2 implementations, that are basically the same and there is a problem Someone would fix it for one version, while the other changed unchanged. Additionally this would be redundant. 

But what I meant with the question, was that the project won’t stay in python in the future. You already have the goal on your roadmap to recode in c++. And when the project is this far you probably want to have all the code in the same language. Rust/c code can be imported into python without problem so the code written in another language could be used in python, but don’t need to be recoded when the project is using c++. That’s why I asked.

**Comment by thatDudo** [comment]
In the near future it will probably stay in python, because rewriting it would not only take a lot of effort, it would also influence the approachability of this project to contributers. Small parts can of course be rewritten, but I dont see why we should outright remove the old, stable python code right away. Thats why creating a newly named inpainter is preferable.
