### ISSUE TITLE
black list / skipping.

### ISSUE THREAD

**Issue by ethanfel** [zyddnys/manga-image-translator#279]
Hi, I've been using manga-image translator for a while and I'm quite happy with it, thank you.

I'm now using gpt3.5 api to translate, since the translation quality is pretty great. 

I've been searching the documentation, but I don't see anything related to this.

Would it be possible to add a blacklist regarding text detected by the OCR ? Allowing the software to inpaint over the text but skipping the translation (some chinese content have the same link on every image for example)? It would reduce the token usage.

**Comment by walruseg** [comment]
You can add an argument and filter the textboxes at line 284 in manga_translator.py
