### ISSUE TITLE
ChatGPT temperature value test/suggestions

### ISSUE THREAD

**Issue by JustFrederik** [zyddnys/manga-image-translator#280]
the temperature setting could be also defined as creativity setting. Thats why i was wondering why you use a value of 1 for chatgpt. 
This [paper](https://arxiv.org/pdf/2303.13780.pdf) says that the perfomence increases with lower temeratures.

**Comment by thatDudo** [comment]
I though that it would potentially improve the quality of the translation due to being more creative.

**Comment by JustFrederik** [comment]
I’d say so, but I would suggest to create an argument with the options precise=0.2, balanced0.5, creative=0.7 and verycreative=1. Also I would keep the issue open and print the link when Chatgpt is used, so we could decide which is the optimal value.

**Comment by JustFrederik** [comment]
@thatDudo should I close the issue or not?

**Comment by thatDudo** [comment]
We can leave it open until we make some tests regarding the temperature, i suppose.

**Comment by JustFrederik** [comment]
Openai has an example for gpttranslate. https://platform.openai.com/examples/default-translate
They are using .3 as temperature
