### ISSUE TITLE
Texts replacement are too small

### ISSUE THREAD

**Issue by Grachy** [zyddnys/manga-image-translator#283]
I am not sure if this happens only when translating from Japanese & Chinese to english or russian, basically when you do translation from hieroglyphs to letters, but thats where I encountered it the most. Here are some examples of how it turns out:

![npyeTFu](https://user-images.githubusercontent.com/80030830/229691188-f717fa43-683a-4f0e-be2a-192123537835.jpeg)
![vqhPVHv](https://user-images.githubusercontent.com/80030830/229691209-32df4950-9d72-44e0-9cc0-3752ed9ac7ab.jpeg)

**Comment by thatDudo** [comment]
Seems like you are using --manga2eng
There we have not implemented --font-size-minimum yet so that is probably what will have to be done...

**Comment by Grachy** [comment]
> Seems like you are using --manga2eng There we have not implemented --font-size-minimum yet so that is probably what will have to be done...

Nope, I don't use manga2eng, because I mostly translate to russian. I also tried this:
"--upscale-ratio=1 --font-size-offset=10 --unclip-ratio=2"

But it didn't help

**Comment by thatDudo** [comment]
I closed it but if the change didnt help feel free to reopen.
