### ISSUE TITLE
web模式，使用有点问题

### ISSUE THREAD

**Issue by 1439707509** [zyddnys/manga-image-translator#287]
web模式下，没有跨域设置

 web模式下 manga_translator.py 中使用
requests.post(f'http://{self.host}:{self.port}/get-translation-result-internal',
requests.get(f'http://{self.host}:{self.port}/task-internal?nonce={self.nonce}'

请求数据，当监听不是127.0.0.1，而是 0.0.0.0 时，这条请求会出错，导致无法使用

**Comment by thatDudo** [comment]
I cant reproduce this problem on my linux installation. If it wouldnt work we also wouldnt have https://touhou.ai/imgtrans/

**Comment by 1439707509** [comment]
> I cant reproduce this problem on my linux installation. If it wouldnt work we also wouldnt have https://touhou.ai/imgtrans/

我使用的是win10系统，不是linux

**Comment by thatDudo** [comment]
Can you check if it works now?

**Comment by jianchang512** [comment]
> 

win10 GPU 服务器，外部不可使用ip访问该服务器，只能使用GPU服务商家提供的一个域名访问

1.  当使用这条命令绑定127.0.0.1执行时
python -m manga_translator --verbose --mode web --use-cuda --host=127.0.0.1
通过域名无法连接  /   /run 等所有接口，处于网络不可连接状态。


2.  当使用这条命令绑定到 0.0.0.0 执行时
python -m manga_translator --verbose --mode web --use-cuda --host=0.0.0.0
通过域名可以连接 /  /run 等接口，也可以正常提交图片， cmd控制台也能显示接收到了新任务 New run task，但再无任何反应，不更新任务状态，也不显示翻译进度。

当将 manga_translator.py 中的 http://{self.host} 修改为 http://127.0.0.1 后一切正常

商家使用docker部署的环境，目测似乎是和 docker 网络 绑定域名等相关。

**Comment by jianchang512** [comment]
> Can you check if it works now?



> Can you check if it works now?

win10 GPU 服务器，外部不可使用ip访问该服务器，只能使用GPU服务商家提供的一个域名访问

1.  当使用这条命令绑定127.0.0.1执行时
python -m manga_translator --verbose --mode web --use-cuda --host=127.0.0.1
通过域名无法连接  /   /run 等所有接口，处于网络不可连接状态。


2.  当使用这条命令绑定到 0.0.0.0 执行时
python -m manga_translator --verbose --mode web --use-cuda --host=0.0.0.0
通过域名可以连接 /  /run 等接口，也可以正常提交图片， cmd控制台也能显示接收到了新任务 New run task，但再无任何反应，不更新任务状态，也不显示翻译进度。

当将 manga_translator.py 中的 http://{self.host} 修改为 http://127.0.0.1 后一切正常

商家使用docker部署的环境，目测似乎是和 docker 网络 绑定域名等相关。

**Comment by 1439707509** [comment]
> 你能检查它现在是否有效吗？



> Can you check if it works now?

win10 GPU 服务器，外部不可使用ip访问该服务器，只能使用GPU服务商家提供的一个域名访问

1.  当使用这条命令绑定127.0.0.1执行时
python -m manga_translator --verbose --mode web --use-cuda --host=127.0.0.1
通过域名无法连接  /   /run 等所有接口，处于网络不可连接状态。


2.  当使用这条命令绑定到 0.0.0.0 执行时
python -m manga_translator --verbose --mode web --use-cuda --host=0.0.0.0
通过域名可以连接 /  /run 等接口，也可以正常提交图片， cmd控制台也能显示接收到了新任务 New run task，但再无任何反应，不更新任务状态，也不显示翻译进度。

当将 manga_translator.py 中的 http://{self.host} 修改为 127.0.0.1 后一切正常

**Comment by zyddnys** [comment]
win10下绑定0.0.0.0会有问题，建议使用端口转发使得外部可以连接127.0.0.1:5003
