### ISSUE TITLE
During batch processing, the text is skipped.

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#289]
During batch processing, the text is skipped.
![2023-04-09_15-04-23](https://user-images.githubusercontent.com/49092250/230771496-9d96c51b-8faa-419e-8cdf-3a2f9c32e4bc.png)
![2023-04-09_15-06-48](https://user-images.githubusercontent.com/49092250/230771656-f29e5403-f598-4618-b5ec-86c1bb268f22.png)
`python -m manga_translator -v --mode batch --use-cuda --translator=google -l RUS --font-path=fonts/anime_ace.ttf -i`

**Comment by JustFrederik** [comment]
@My12123 can you try it without a custom font?

**Comment by My12123** [comment]
Without a custom font, everything is fine

**Comment by JustFrederik** [comment]
How are other custom fonts? Is the path correct?

**Comment by JustFrederik** [comment]
@My12123 im not sure about the syntax but try replacing the = with a space

**Comment by My12123** [comment]
but I need a custom font, I don't know how others are, but only it looks like a manga in Russian.

**Comment by JustFrederik** [comment]
Usually parsers use the -- as Argument and the values after that as the value. Like —Mode batch. My guess is that the argparser is registering an argument font-path=foo.ttf instead the argument font-path with a value foo.ttf. At least that’s how all the argparsers I ever used work. I could be wrong tho

**Comment by JustFrederik** [comment]
1. Try with space instead of =
2. Try absolute path
3. Try other ttf and check if it’s just this ttf file

**Comment by My12123** [comment]
Thanks for the answer until there was no more, so I will close this problem, but if it appears I will open the problem again.

**Comment by JustFrederik** [comment]
@My12123 what was the problem?

**Comment by My12123** [comment]
I don't know for sure, I'm not a developer or a programmer, it's better to ask @zyddnys or @thatDudo

**Comment by thatDudo** [comment]
Maybe it was a fluke..
