### ISSUE TITLE
DeepL translation error

### ISSUE THREAD

**Issue by Eidenz** [zyddnys/manga-image-translator#29]
Hello,

Translating using DeepL only results in "error" as the text results (see attachment).

I'm running on the free version of DeepL, but the python library works when I try running it by hand.
![e93f70744e935153116c82b0c1e662f5M](https://user-images.githubusercontent.com/27901016/145725125-b9581735-8564-4c73-9902-7469c0c445a5.png)

**Comment by zyddnys** [comment]
What is your target language?

**Comment by Eidenz** [comment]
Target language is English

**Comment by zyddnys** [comment]
Are you using `--target-lang ENG` in the command line?

**Comment by Eidenz** [comment]
I tried both with --target-lang ENG in console and without, still error. I forgot to mention I'm using the web version.

I modified the ui.html and web_main.py to add DeepL and Google as translation engines. It worked well for Google, but not for DeepL right now.

I'm using "ENG" as well in the web_main.py for the language array.

**Comment by Eidenz** [comment]
The error also occurs no matter the language actually, tried with Chinese and still "error" output.

**Comment by Eidenz** [comment]
Just as an update, running the image mode works, it only affects the web version.

**Comment by Eidenz** [comment]
Terribly sorry, I actually forgot to modify the "submit" part in web_main.py...

It works fine now :/
