### ISSUE TITLE
Model for English OCR

### ISSUE THREAD

**Issue by marcussacana** [zyddnys/manga-image-translator#3]
Can you provide a model to ocr english pages?
I had good results with japanese pages, but when I tried a english page...

![005](https://user-images.githubusercontent.com/10576957/115415125-050c6c80-a1cd-11eb-801a-c9ce6f55a29a.png)

Original:
![005](https://user-images.githubusercontent.com/10576957/115415879-a4c9fa80-a1cd-11eb-9376-5cc91502cd34.jpg)

Or at least add example how we can build our own model... But I will supose I don't will know how to handle even if I have a documentation (i'm not good with python)

**Comment by zyddnys** [comment]
I am currently training a new version to detect English text, it should be out in about a week.

**Comment by marcussacana** [comment]
Fuck man, I love you so much, thanks for this amazing program.

**Comment by marcussacana** [comment]
Take your time, to me if you take more even one month with better result it's better :)
