### ISSUE TITLE
[Bug]: I can’t upload the new photos

### ISSUE THREAD

**Issue by a27691914** [zyddnys/manga-image-translator#300]
### Issue

![image](https://user-images.githubusercontent.com/130690503/231832434-d513c1fa-c704-40d5-92a5-557628633cc3.png)

### Command Line Arguments

```Shell
I can’t upload the new picture. I have been trying different type of film can’t upload still.thanks
```

**Comment by zyddnys** [comment]
the service is back

**Comment by a27691914** [comment]
Thanks for help
