### ISSUE TITLE
能不能添加像 pp鸭 那样的压缩算法？

### ISSUE THREAD

**Issue by 1439707509** [zyddnys/manga-image-translator#304]
pp鸭官网 http://ppduck.com/

开源的压缩算法
https://github.com/topics/image-compression

我也不知道pp鸭具体用了那些算法

**Comment by QiroNT** [comment]
我的建议是自行使用适当工具压缩结果，嫌麻烦可以写个 bash 脚本。如果你需要在 web 内实现，欢迎 pr。

**Comment by My12123** [comment]
我是为了压缩而不损失质量.

**Comment by JustFrederik** [comment]
@My12123 How is that supposed to work. Enlighten me. There are file formats that are more efficient than others in storing lossless images. [Qoi ](https://github.com/phoboslab/qoi) comes to mind, but I wouldn’t call it compression even though the GitHub page calls it that. It’s just a new format that stores the data differently and does therefore take up less storage. But most formats are lossy in itself. Jpeg for example is lossy at quality 100. If you know something I don’t please suggest a algorithm/ library that is able to do that

**Comment by My12123** [comment]
@JustFrederik
For example https://github.com/Kudrik/image-optimizer
https://stackoverflow.com/questions/33077804/losslessly-compressing-images-on-django
