### ISSUE TITLE
manga_translator\server\web_main.py  里缺少了段，gpt3.5 代码

### ISSUE THREAD

**Issue by 1439707509** [zyddnys/manga-image-translator#305]
manga_translator\server\web_main.py 这个文件里，下面这段代码，少了gpt3.5

VALID_TRANSLATORS = set(['youdao', 'baidu', 'google', 'deepl', 'papago', 'offline', 'none', 'original'])   要改成

VALID_TRANSLATORS = set(['gpt3.5','youdao', 'baidu', 'google', 'deepl', 'papago', 'offline', 'none', 'original'])  才行

**Comment by QiroNT** [comment]
其实这个参数是为了照顾现有 demo 的，感觉该搬到 `.env` 合适。
不过这个参数是需要和 `ui.html` 同步的，所以大概还需要把 UI 换成模版…
