### ISSUE TITLE
本地运行出错

### ISSUE THREAD

**Issue by longij** [zyddnys/manga-image-translator#32]
运行后显示：

usage: translate_demo.py [-h] [--mode MODE] [--image IMAGE]
                         [--image-dst IMAGE_DST] [--size SIZE]
                         [--use-inpainting] [--use-cuda] [--force-horizontal]
                         [--inpainting-size INPAINTING_SIZE]
                         [--unclip-ratio UNCLIP_RATIO]
                         [--box-threshold BOX_THRESHOLD]
                         [--text-threshold TEXT_THRESHOLD]
                         [--text-mag-ratio TEXT_MAG_RATIO]
                         [--translator TRANSLATOR] [--target-lang TARGET_LANG]
                         [--verbose]
translate_demo.py: error: unrecognized arguments: [--verbose] [--translator=google] [--target-lang=CHS]

**Comment by Eidenz** [comment]
Remove the square brackets [] from arguments

--verbose --translator=google --target-lang=CHS

**Comment by longij** [comment]
> 

改了之后有新的报错：
![error](https://user-images.githubusercontent.com/97241873/148479627-59e415b5-4ddc-4eb7-bd03-a477c00b25c8.PNG)

**Comment by zyddnys** [comment]
Remove --use-cuda

**Comment by longij** [comment]
> Remove --use-cuda

谢谢，解决了！但是我只有百度翻译的api，而不提供有道或deepl的api密钥的话就会报错，这应该怎么办

**Comment by zyddnys** [comment]
把--translator=google换成--translator=baidu

**Comment by longij** [comment]
> 把--translator=google换成--translator=baidu

成功了！谢谢
