### ISSUE TITLE
web模式，只能输出 png 格式图片

### ISSUE THREAD

**Issue by 1439707509** [zyddnys/manga-image-translator#320]
web模式下， \manga_translator\server\web_main.py 代码中 result_async 方法写死了 只返回png格式图片，当转换为 jpg webp格式时，就会出错无法获取图片

@routes.get("/result/{taskid}")
async def result_async(request):
    im = Image.open("result/" + request.match_info.get('taskid') + "/final.png")
    stream = BytesIO()
    im.save(stream, "PNG")
    return web.Response(body=stream.getvalue(), content_type='image/png')

**Comment by zyddnys** [comment]
现在只输出jpg了 3c02ffd9285b92e15dcdd80cc7d4e6eea02b3585

**Comment by jianchang512** [comment]
> 

在

> 现在只输出jpg了 [3c02ffd](https://github.com/zyddnys/manga-image-translator/commit/3c02ffd9285b92e15dcdd80cc7d4e6eea02b3585)

这样不好吧，如果想输出 png 、webp格式怎么办呢，不还是出错吗，建议这里的输出根据 启动命令中的 -f 来设置
