### ISSUE TITLE
google 接口，代理有问题 

### ISSUE THREAD

**Issue by 1439707509** [zyddnys/manga-image-translator#321]
\manga_translator\translators\google.py 里代理限定只读取系统代理，导致出错，改为和 OpenAI 使用相同代理
	
#if 'http' in SYS_PROXY:
#if 'http' in SYS_PROXY:
#SYS_HTTP_PROXY = {}
#SYS_HTTP_PROXY['http'] = SYS_PROXY['http']
#SYS_HTTP_PROXY['https'] = SYS_PROXY['http']

我手动改成，下面这个可以了

from .keys import OPENAI_HTTP_PROXY
if OPENAI_HTTP_PROXY:
    SYS_HTTP_PROXY = {
                "http": "http://%s" % OPENAI_HTTP_PROXY,
                "https": "http://%s" % OPENAI_HTTP_PROXY
            }

**Comment by zyddnys** [comment]
376b21d7b09d1b17a132605993fe82cb2281a6ee 修了
