### ISSUE TITLE
OCR模型 那些东西，还会更新吗？需要帮忙 炼丹 啥的吗？

### ISSUE THREAD

**Issue by 1439707509** [zyddnys/manga-image-translator#323]
如题

**Comment by JustFrederik** [comment]
> Font/Background Color detection is the responsibility of the ocr and if the ocr is not very good at it the result wont be either.

In the short term I am trying to improve this by training a new model and maybe with some postprocessing like color clustering. In the long run something like [Editing Text in the Wild](https://arxiv.org/pdf/1908.03047.pdf) is needed.


> A good text bubble detector would also improve the textline merging.

A dedicated learning based algorithm would also work if one can find time to clean up manga109 dataset.

_Originally posted by @zyddnys in https://github.com/zyddnys/manga-image-translator/issues/312#issuecomment-1522320668_

**Comment by 1439707509** [comment]
> > Font/Background Color detection is the responsibility of the ocr and if the ocr is not very good at it the result wont be either.
> 
> A dedicated learning based algorithm would also work if one can find time to clean up manga109 dataset.
> 
> _Originally posted by @zyddnys in [#312 (comment)](https://github.com/zyddnys/manga-image-translator/issues/312#issuecomment-1522320668)_

具体需要怎样做？

**Comment by JustFrederik** [comment]
zyddnys asked if someone could clean up the manga109 dataset. If you want to do that and dont have the dataset just say so.

Google translate: 
zyddnys 问是否有人可以清理 manga109 数据集。 如果你想这样做并且没有数据集就这么说。

**Comment by 1439707509** [comment]
> zyddnys asked if someone could clean up the manga109 dataset. If you want to do that and dont have the dataset just say so.
> 
> Google translate: zyddnys 问是否有人可以清理 manga109 数据集。 如果你想这样做并且没有数据集就这么说。

那我要怎样才能 清理 manga109 数据集？
