### ISSUE TITLE
用不明白 能否出个详细点的使用说明

### ISSUE THREAD

**Issue by bic9527** [zyddnys/manga-image-translator#33]

**Comment by bic9527** [comment]
小白研究半天搞不懂   运行python translate_demo.py --image <图片文件路径> [--use-inpainting] [--use-cuda]   是运行后再输入代码还是先用记事本打开输入代码后再运行   如果是前者的话双击运行没反应

**Comment by bic9527** [comment]
后者的话研究了半天也弄不了

**Comment by zyddnys** [comment]
一般推荐用在线版，这个仓库是给有一定python经验的人用的

**Comment by yadoong** [comment]
请问能否添加一下对E绅士的支持

**Comment by QiroNT** [comment]
> 请问能否添加一下对E绅士的支持

@yadoong  我至今不知道 GreasyFork 的策略要怎么做合适，目前看来只能分两个版本发布（一个正常一个支持本子站），不过这么干会导致基本是双倍的维护量和反馈量，长久以来不是什么好方案。

再过两天我想不出方法再这么做吧，我本地先做着支持。

还有下次单开个 issue，回复没提醒，还是 zyddnys 叫得我。浏览器脚本也不在这个仓库，按理来说 issue 是要转过去的但是回复是没法转的。
