### ISSUE TITLE
[Feature Request]: Custome offline translation model

### ISSUE THREAD

**Issue by hieult0603** [zyddnys/manga-image-translator#332]
Hi! I have successfully deployed and translated some manga images using available translators (google translator). But since the quality of google translator work quite poor in ENG-VIN comp so i fine-tuned a new model using fairseq library. Is there a way for me to apply my custom model to replace existed translators?

**Comment by JustFrederik** [comment]
@hieult0603 no there isnt. Duplicate of #288

**Comment by thatDudo** [comment]
Do you mean you have improved an existing facebook model for Vietnamese? Ifit is better we can add it of course.

**Comment by JustFrederik** [comment]
@thatDudo is jparacrawl up to date? I noticed that the models on https://www.kecl.ntt.co.jp/icl/lirg/jparacrawl/ for the base variant have a size of 2GB while it is only 500mb here.

**Comment by thatDudo** [comment]
> @thatDudo is jparacrawl up to date? I noticed that the models on https://www.kecl.ntt.co.jp/icl/lirg/jparacrawl/ for the base variant have a size of 2GB while it is only 500mb here. I didnt find a comment if its v1,v2 or v3. The Sugoi translator has a comment which version it is and whats with jparacrawl small?

We have used ctranslate2 to compress the models and make it faster. https://opennmt.net/CTranslate2/conversion.html

**Comment by JustFrederik** [comment]
> > @thatDudo is jparacrawl up to date? I noticed that the models on https://www.kecl.ntt.co.jp/icl/lirg/jparacrawl/ for the base variant have a size of 2GB while it is only 500mb here. I didnt find a comment if its v1,v2 or v3. The Sugoi translator has a comment which version it is and whats with jparacrawl small?
> 
> We have used ctranslate2 to compress the models and make it faster. https://opennmt.net/CTranslate2/conversion.html

i have seen the conversion code, but there is no info about the converted version of the model so i asked.

**Comment by thatDudo** [comment]
I think we have the 3.0 (lastest) version as it was released before we have added it.
