### ISSUE TITLE
Can a feature be added? Copy and paste the text in Figure 1 to Figure 2

### ISSUE THREAD

**Issue by 1439707509** [zyddnys/manga-image-translator#336]
As shown in the picture, I mainly want to replace the black and white Chinese image source with color Japanese

![1](https://user-images.githubusercontent.com/128567416/236699359-20740891-a2d7-4d2c-b624-aafd47eb5252.png)
![2](https://user-images.githubusercontent.com/128567416/236699366-c363e56d-6e5e-45bd-a31f-542c17c3c8e2.jpg)

**Comment by thatDudo** [comment]
This is currently only possible through manual pasting. Perhaps we could implement some kind of caching or implement --load-text as a counterpart to --save-text in the future.. Not sure how to go about it.

**Comment by 1439707509** [comment]
> This is currently only possible through manual pasting of the text in manual web mode. Perhaps we could implement some kind of caching or implement --load-text as a counterpart to --save-text in the future.. Not sure how to go about it.

understand, wait for the future may appear
