### ISSUE TITLE
Issue running, 'pydensecrf'

### ISSUE THREAD

**Issue by VilotStar** [zyddnys/manga-image-translator#34]
I am trying to use this and keep getting this error: ModuleNotFoundError: No module named 'pydensecrf', I have tried installing cython and itself but nothing seems to work

**Comment by zyddnys** [comment]
What error message do you get after installing cython?

**Comment by Snowad14** [comment]
It's the same for me, I looked on their issues and on google and many people (see no one) can't install pydensecrf on a python version > 3.6. However, it seems to me that I had managed to install it but I really can't find the way to do it anymore. Tested with python 3.8.8 and 3.9.10 with anaconda or with no anaconda it doesn't work

I tested the command : 
- pip install pydensecrf
- pip install git+https://github.com/lucasb-eyer/pydensecrf.git

![image](https://user-images.githubusercontent.com/67842535/150658688-b0ee151d-871a-49e1-a274-f421f218b16c.png)

**Comment by dmMaze** [comment]
windows users can try precompiled wheels from [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pydensecrf)

**Comment by MaksymSofer** [comment]
I did overcome this issue in the following way on Ubuntu 20.04:
1. git clone https://github.com/lucasb-eyer/pydensecrf.git
2. sudo apt-get remove cython
3. sudo pip install -U cython
4. Execute **python setup.py build** from the directory to where you cloned this tool
5. Execute **sudo python setup.pu install**
