### ISSUE TITLE
gpt3.5 跑不了文字的图片

### ISSUE THREAD

**Issue by 1439707509** [zyddnys/manga-image-translator#352]
谷歌和有道可以跑

能不能加个，使用gpt 3.5在出现了 WARNING: [GPT35TurboTranslator] Restarting request due to timeout. Attempt: 3  或者 ERROR: [batch] Exception: openai servers did not respond quickly enough. 时，把文字分成多段，进行翻译

![1](https://github.com/zyddnys/manga-image-translator/assets/128567416/c571a1bf-39f3-4de4-abfe-a3e9da302889)
![2](https://github.com/zyddnys/manga-image-translator/assets/128567416/de2e2d6f-4b0e-4040-82e4-3c27dee2f969)
![3](https://github.com/zyddnys/manga-image-translator/assets/128567416/015438b6-bfae-4759-b36d-291444a2bfa0)
![5](https://github.com/zyddnys/manga-image-translator/assets/128567416/661f52ab-de8e-4212-9a32-6953632b421f)
![6](https://github.com/zyddnys/manga-image-translator/assets/128567416/bc5094dc-4e4d-42e5-86f8-73d2be62e0ae)

**Comment by thatDudo** [comment]
It seems that all that needed to be done was increase the timeout wait time but i have once again overcomplicated things and made the prompts split if there is too much text.

**Comment by thatDudo** [comment]
![final](https://github.com/zyddnys/manga-image-translator/assets/58403773/cf1955d8-d2a0-4b3d-b177-559f439da492)

**Comment by Mayonnaisu** [comment]
> It seems that all that needed to be done was increase the timeout wait time but i have once again overcomplicated things and made the prompts split if there is too much text.

@thatDudo Hello, how can I increase the timeout wait time?
