### ISSUE TITLE
[Bug]: craft一运行就报内存满了

### ISSUE THREAD

**Issue by AiYouWei** [zyddnys/manga-image-translator#354]
### Issue

 CUDA out of memory. Tried to allocate 288.00 MiB (GPU 0; 11.00 GiB total capacity; 9.24 GiB already allocated; 0 bytes free; 9.57 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting ma
x_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

### Command Line Arguments

```Shell
python  -m manga_translator --verbose --mode batch --use-cuda-limited --translator=papago --det-gamma-correct --det-auto-rotate --detector=craft --retries=10 --filter-text='.*送.*' --target-lang=KOR -f=jp
g -i
```

### Console logs

```Shell
CUDA out of memory. Tried to allocate 288.00 MiB (GPU 0; 11.00 GiB total capacity; 9.24 GiB already allocated; 0 bytes free; 9.57 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting ma
x_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by zyddnys** [comment]
fixed in dd1104d9da5968a4449e24b4e98ba359de380e00, try it

**Comment by zyddnys** [comment]
or you can try lowering detection resolution with `--detection-size 1024`

**Comment by PolicyChanges** [comment]
I kept getting this error after a pull and wasn't sure what changed.

bisected it to this changed in  manga_translator/config.py:
    `inpainter: Inpainter = Inpainter.none`
to
    `inpainter: Inpainter = Inpainter.lama_large`

I have a  lot of older/lower-end compute where individual cuda devices are vram constrained.  Good for mit's embarrassingly parallel job.
maybe put various use case example configurations in the examples folder. just a thought
