### ISSUE TITLE
[Bug]: list index out of range

### ISSUE THREAD

**Issue by AiYouWei** [zyddnys/manga-image-translator#355]
### Issue

list index out of range

### Command Line Arguments

```Shell
python  -m manga_translator --verbose --mode batch --use-cuda-limited --translator=papago --det-gamma-correct --det-auto-rotate --detector=default --retries=10 --filter-text='.*送.*' --target-lang=KOR -f=
jpg -i
```

### Console logs

```Shell
[GoogleTranslator] Translating into Korean
ERROR: [batch] IndexError: list index out of range
Traceback (most recent call last):
  File "D:\StudioProjects\manga-image-translator\manga_translator\manga_translator.py", line 246, in translate
    return await self._translate(ctx)
  File "D:\StudioProjects\manga-image-translator\manga_translator\manga_translator.py", line 329, in _translate
    ctx.text_regions = await self._run_text_translation(ctx)
  File "D:\StudioProjects\manga-image-translator\manga_translator\manga_translator.py", line 464, in _run_text_translation
    translated_sentences = await dispatch_translation(ctx.translator, [region.get_text() for region in ctx.text_regions], ctx.use_mtpe,
  File "D:\StudioProjects\manga-image-translator\manga_translator\translators\__init__.py", line 105, in dispatch
    queries = await translator.translate('auto', tgt_lang, queries, use_mtpe)
  File "D:\StudioProjects\manga-image-translator\manga_translator\translators\common.py", line 168, in translate
    _translations = await self._translate(*self.parse_language_codes(from_lang, to_lang, fatal=True), queries)
  File "D:\StudioProjects\manga-image-translator\manga_translator\translators\google.py", line 240, in _translate
    translation = await self._translate_query(from_lang, to_lang, '\n'.join(lang_queries))
  File "D:\StudioProjects\manga-image-translator\manga_translator\translators\google.py", line 308, in _translate_query
    for part in parsed[1][0][0][5]:
IndexError: list index out of range
```

**Comment by hongdatchy** [comment]
I don't know why there is this bug but I got rid of the error image (don't translate but just read and write back the original image) by editing the following code in the manga_translator.py function: 
    async def _translate_file(self, path: str, dest: str, params: dict):
        if not params.get('overwrite') and os.path.exists(dest):
            logger.info(f'Skipping as already translated: {dest}')
            await self._report_progress('saved', True)
            return True
        logger.info(f'Translating: {path} -> {dest}')

        try:
            img = Image.open(path)
        except Exception:
            return False

        translation_dict =None
        result = None
        try:
            translation_dict = await self.translate(img, params)
            if translation_dict.result is not None:
                result = translation_dict.result
            elif translation_dict.text_regions is not None:
                # If no text was found use original image 
                result = img
            if translation_dict.save_text or translation_dict.save_text_file or translation_dict.prep_manual:
                if translation_dict.prep_manual:
                    # Save original image next to translated
                    p, ext = os.path.splitext(dest)
                    img_filename = p + '-orig' + ext
                    img_path = os.path.join(os.path.dirname(dest), img_filename)
                    img.save(img_path, quality=translation_dict.save_quality)
                if translation_dict.text_regions:
                    self._save_text_to_file(dest, translation_dict)
        except:
            result = img


        # Save result
        if result:
            logger.info('Saving results')
            save_result(result, dest, translation_dict)
            await self._report_progress('saved', True)
        else:
            return False
        return True

**Comment by thatDudo** [comment]
Your commandline arguments are incorrect. It should be `--translator google`.
That said i cant seem to reproduce this bug, perhaps google is sometimes sending back invalid responses...
I could add some error catching.
