### ISSUE TITLE
我想训练 着色器，能否给个最新的训练代码或者项目

### ISSUE THREAD

**Issue by 1439707509** [zyddnys/manga-image-translator#365]
https://github.com/OValery16/Manga-colorization---cycle-gan

这个训练代码可能不可用了，已经是5年前的，框架早就更新n个版本了

或者说，网上有现成，更新更强的 着色器 模型？

**Comment by zyddnys** [comment]
上色找style2paints

**Comment by 1439707509** [comment]
> Deoldify 很可能是最佳选择，但需要对其进行培训

https://github.com/zyddnys/manga-image-translator/issues/365#issuecomment-1553373897

这个吗？里面是否有训练代码?

**Comment by 1439707509** [comment]
> Deoldify is most likely the best option, but it needs to be trained

https://github.com/zyddnys/manga-image-translator/issues/365#issuecomment-1553373897
