### ISSUE TITLE
[Feature Request]: Add Manga-colorization---cycle-gan

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#366]
### What would your feature do?

Even better if you add the ability to train a model to this repository.
@thatDudo
- [ ] Manga-colorization---cycle-gan https://github.com/OValery16/Manga-colorization---cycle-gan/
What version of python and dependencies do I need to install for windows?

**Comment by thatDudo** [comment]
This feature is out of scope, models should be trained externally.

**Comment by My12123** [comment]
Good. Then what version of python and dependencies do I need to install for Windows? For startup and training.

**Comment by thatDudo** [comment]
Related: #365

**Comment by 1439707509** [comment]
> > Good. Then what version of python and dependencies do I need to install for Windows? For startup and training.
> 
> It seems like that repository is using some deprecated dependencies so you would have to manually fix any errors thats might come up. Sadly the weights are currently not downloadable anyways [OValery16/Manga-colorization---cycle-gan#1](https://github.com/OValery16/Manga-colorization---cycle-gan/issues/1)

我看到了个差不多的项目，是否能用他的代码

https://github.com/MingwangLin/automatic-manga-colorization

https://cowtransfer.com/s/e1fe2095b2484c 点击链接查看 [ 1.zip ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 ipw080 查看；

http://www.styletransfer.tech/#/

**Comment by My12123** [comment]
> 
> https://cowtransfer.com/s/e1fe2095b2484c 点击链接查看 [ 1.zip ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 ipw080 查看；

@1439707509
这是什么？ 我需要为Windows安装哪个版本的python和依赖项？
