### ISSUE TITLE
Assistance in training manga-colorization.

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#378]
https://github.com/qweasdd/manga-colorization
```python
(manga-colorization) M:\manga-colorization>python train.py -g -p M:\manga-colorization\train
Traceback (most recent call last):
  File "train.py", line 281, in <module>
    train_dataloader, ft_dataloader = get_dataloaders(args.path, augmentations, config['batch_size'], args.fine_tuning, config['number_of_mults'])
  File "train.py", line 38, in get_dataloaders
    return train_dataloader, finetuning_dataloader
UnboundLocalError: local variable 'finetuning_dataloader' referenced before assignment
``` 
How to fix it?

Dependencies that I used:
albumentations==1.3.0
  - numpy [required: >=1.11.1, installed: 1.21.6]
  - opencv-python-headless [required: >=4.1.1, installed: 4.7.0.72]
    - numpy [required: >=1.17.0, installed: 1.21.6]
  - PyYAML [required: Any, installed: 6.0]
  - qudida [required: >=0.0.4, installed: 0.0.4]
    - numpy [required: >=0.18.0, installed: 1.21.6]
    - opencv-python-headless [required: >=4.0.1, installed: 4.7.0.72]
      - numpy [required: >=1.17.0, installed: 1.21.6]
    - scikit-learn [required: >=0.19.1, installed: 1.0.2]
      - joblib [required: >=0.11, installed: 1.2.0]
      - numpy [required: >=1.14.6, installed: 1.21.6]
      - scipy [required: >=1.1.0, installed: 1.7.3]
        - numpy [required: >=1.16.5,<1.23.0, installed: 1.21.6]
      - threadpoolctl [required: >=2.0.0, installed: 3.1.0]
    - typing-extensions [required: Any, installed: 4.6.2]
  - scikit-image [required: >=0.16.1, installed: 0.19.3]
    - imageio [required: >=2.4.1, installed: 2.29.0]
      - numpy [required: Any, installed: 1.21.6]
      - pillow [required: >=8.3.2, installed: 9.5.0]
    - networkx [required: >=2.2, installed: 2.6.3]
    - numpy [required: >=1.17.0, installed: 1.21.6]
    - packaging [required: >=20.0, installed: 23.1]
    - pillow [required: >=6.1.0,!=8.3.0,!=7.1.1,!=7.1.0, installed: 9.5.0]
    - PyWavelets [required: >=1.1.1, installed: 1.3.0]
      - numpy [required: >=1.17.3, installed: 1.21.6]
    - scipy [required: >=1.4.1, installed: 1.7.3]
      - numpy [required: >=1.16.5,<1.23.0, installed: 1.21.6]
    - tifffile [required: >=2019.7.26, installed: 2021.11.2]
      - numpy [required: >=1.15.1, installed: 1.21.6]
  - scipy [required: Any, installed: 1.7.3]
    - numpy [required: >=1.16.5,<1.23.0, installed: 1.21.6]
Flask-WTF==0.14.3
  - Flask [required: Any, installed: 1.1.1]
    - click [required: >=5.1, installed: 8.1.3]
      - colorama [required: Any, installed: 0.4.6]
      - importlib-metadata [required: Any, installed: 6.6.0]
        - typing-extensions [required: >=3.6.4, installed: 4.6.2]
        - zipp [required: >=0.5, installed: 3.15.0]
    - itsdangerous [required: >=0.24, installed: 2.1.2]
    - Jinja2 [required: >=2.10.1, installed: 3.1.2]
      - MarkupSafe [required: >=2.0, installed: 2.1.2]
    - Werkzeug [required: >=0.15, installed: 2.2.3]
      - MarkupSafe [required: >=2.1.1, installed: 2.1.2]
  - itsdangerous [required: Any, installed: 2.1.2]
  - WTForms [required: Any, installed: 3.0.1]
    - MarkupSafe [required: Any, installed: 2.1.2]
gunicorn==20.1.0
  - setuptools [required: >=3.0, installed: 67.7.2]
imutils==0.5.4
matplotlib==3.1.1
  - cycler [required: >=0.10, installed: 0.11.0]
  - kiwisolver [required: >=1.0.1, installed: 1.4.4]
    - typing-extensions [required: Any, installed: 4.6.2]
  - numpy [required: >=1.11, installed: 1.21.6]
  - pyparsing [required: >=2.0.1,!=2.1.6,!=2.1.2,!=2.0.4, installed: 3.0.9]
  - python-dateutil [required: >=2.1, installed: 2.8.2]
    - six [required: >=1.5, installed: 1.16.0]
opencv-python==4.5.5.64
  - numpy [required: >=1.14.5, installed: 1.21.6]
patool==1.12
pip==23.1.2
pipdeptree==2.7.1
snowy==0.0.9
  - imageio [required: >=2.3, installed: 2.29.0]
    - numpy [required: Any, installed: 1.21.6]
    - pillow [required: >=8.3.2, installed: 9.5.0]
  - numba [required: >=0.39, installed: 0.56.4]
    - importlib-metadata [required: Any, installed: 6.6.0]
      - typing-extensions [required: >=3.6.4, installed: 4.6.2]
      - zipp [required: >=0.5, installed: 3.15.0]
    - llvmlite [required: >=0.39.0dev0,<0.40, installed: 0.39.1]
    - numpy [required: >=1.18,<1.24, installed: 1.21.6]
    - setuptools [required: Any, installed: 67.7.2]
  - numpy [required: >=1.14, installed: 1.21.6]
  - scipy [required: >=0.16, installed: 1.7.3]
    - numpy [required: >=1.16.5,<1.23.0, installed: 1.21.6]
torchvision==0.7.0+cu101
  - numpy [required: Any, installed: 1.21.6]
  - pillow [required: >=4.1.1, installed: 9.5.0]
  - torch [required: ==1.6.0, installed: 1.6.0+cu101]
    - future [required: Any, installed: 0.18.3]
    - numpy [required: Any, installed: 1.21.6]
tqdm==4.65.0
  - colorama [required: Any, installed: 0.4.6]
wheel==0.40.0

**Comment by My12123** [comment]
```
(manga-colorization) M:\manga-colorization>python train.py -g -p M:\manga-colorization\train -ft
14:23:27.140696
Step : 0 Discr loss: 0.0000 Gen loss : 0.0000

14:23:29.842934
Epoch : 0 Discr loss: 1.3872 Gen loss : 0.0000

14:23:29.945935
Step : 0 Discr loss: 0.0000 Gen loss : 0.0000

14:23:30.525580
Epoch : 1 Discr loss: 0.0000 Gen loss : 17.9444

14:23:30.648579
Step : 0 Discr loss: 0.0000 Gen loss : 0.0000

14:23:31.069186
Epoch : 2 Discr loss: 1.3857 Gen loss : 0.0000

14:23:31.181184
Step : 0 Discr loss: 0.0000 Gen loss : 0.0000

14:23:31.699809
Epoch : 3 Discr loss: 0.0000 Gen loss : 17.6327
Traceback (most recent call last):
  File "train.py", line 294, in <module>
    torch.save(colorizer.generator.state_dict(), str(datetime.datetime.now().time()))
  File "F:\1\envs\manga-colorization\lib\site-packages\torch\serialization.py", line 361, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "F:\1\envs\manga-colorization\lib\site-packages\torch\serialization.py", line 229, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "F:\1\envs\manga-colorization\lib\site-packages\torch\serialization.py", line 210, in __init__
    super(_open_file, self).__init__(open(name, mode))
OSError: [Errno 22] Invalid argument: '14:45:12.292166'
```
How to fix it?

**Comment by Omicronlawful** [comment]
Use Linux or figure out what Windows file naming rules are.

**Comment by My12123** [comment]
OSError: [Errno 22] Invalid argument: '14:45:12.292166'
What needs to be changed to work on Windows?
```python
torch.save(colorizer.generator.state_dict(), str(datetime.datetime.now().time()))
```

**Comment by tak2hu** [comment]
> OSError: [Errno 22] Invalid argument: '14:45:12.292166'

This looks like coming from `datetime.datetime.now().time()` (probably idk haven’t tested it)

On Windows, `:` is an [illegal character for a filename](https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names) (again probably haven’t tested it myself)

Just change 
`torch.save(colorizer.generator.state_dict(), str(datetime.datetime.now().time()))` 
into something like `torch.save(colorizer.generator.state_dict(),str(whatever_for_a_checkpoint_filename))`

I just remembered about `:` in Windows filenames are data streams from [this YouTube video](https://youtu.be/3BWTo87oCwc). Also check out [this article](https://owasp.org/www-community/attacks/Windows_alternate_data_stream) and [this blog](https://blog.netwrix.com/2022/12/16/alternate_data_stream/).

**Comment by Omicronlawful** [comment]
I’m interested how you got the model from v1 working with [v2](https://github.com/qweasdd/manga-colorization-v2)

**Comment by My12123** [comment]
This is V1 https://github.com/qweasdd/manga-colorization

**Comment by Omicronlawful** [comment]
Noticed that, but this project is using v2 which is an improved version of v1

**Comment by My12123** [comment]
> > Ошибка: [Ошибка 22] Недопустимый аргумент: '14:45:12.292166'
> 
> Похоже, что это исходит от `datetime.datetime.now().time()` (вероятно, idk это не тестировали)
> 
> В Windows `:` является [недопустимым символом для имени файла](https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names) (опять же, вероятно, я сам его не тестировал)
> 
> Просто измените `torch.save(colorizer.generator.state_dict(), str(datetime.datetime.now().time()))` во что-то вроде `torch.save(colorizer.generator.state_dict(),str(whatever_for_a_checkpoint_filename))`
> 
> Я только что вспомнил о том, что `:` в Windows имена файлов - это потоки данных из [этого видео на YouTube](https://youtu.be/3BWTo87oCwc). Также ознакомьтесь с [этой статьей](https://owasp.org/www-community/attacks/Windows_alternate_data_stream) и [этим блогом](https://blog.netwrix.com/2022/12/16/alternate_data_stream/).

@tak2hu
It didn't help.
```python
(manga-colorization) F:\manga-colorization>python train.py -g -p ./train -ft
19:32:30.383301
Step : 0 Discr loss: 0.0000 Gen loss : 0.0000

19:32:42.473506
Epoch : 0 Discr loss: 1.3900 Gen loss : 0.0000

19:32:42.684518
Step : 0 Discr loss: 0.0000 Gen loss : 0.0000

19:32:43.494637
Epoch : 1 Discr loss: 0.0000 Gen loss : 14.8941

19:32:43.727758
Step : 0 Discr loss: 0.0000 Gen loss : 0.0000

19:32:44.158929
Epoch : 2 Discr loss: 1.3888 Gen loss : 0.0000

19:32:44.365930
Step : 0 Discr loss: 0.0000 Gen loss : 0.0000

19:32:45.108161
Epoch : 3 Discr loss: 0.0000 Gen loss : 18.3954

19:32:45.346162
Step : 0 Discr loss: 0.0000 Gen loss : 0.0000
19:32:51.401488
Epoch : 11 Discr loss: 0.0000 Gen loss : 20.1612

19:32:51.605481
Step : 0 Discr loss: 0.0000 Gen loss : 0.0000

19:32:52.024559
Epoch : 12 Discr loss: 1.3793 Gen loss : 0.0000

19:32:52.237559
Step : 0 Discr loss: 0.0000 Gen loss : 0.0000

19:32:52.806716
Epoch : 13 Discr loss: 0.0000 Gen loss : 15.1746

19:32:53.026233
Step : 0 Discr loss: 0.0000 Gen loss : 0.0000

19:32:53.423234
Epoch : 14 Discr loss: 1.3789 Gen loss : 0.0000

Traceback (most recent call last):
  File "train.py", line 294, in <module>
    torch.save(colorizer.generator.state_dict(),str(whatever_for_a_checkpoint_filename))
NameError: name 'whatever_for_a_checkpoint_filename' is not defined
```

**Comment by Omicronlawful** [comment]
Variables need to be defined before usage. Btw why are you training this?

**Comment by My12123** [comment]
To make a better coloring model, but I don't know if it will work.

**Comment by Omicronlawful** [comment]
Training will work, but you should try using the improved version and training a model for that, cuz improved == better.

**Comment by My12123** [comment]
In version V2, learning is impossible.

**Comment by My12123** [comment]
@tak2hu
Will there be an answer to this?

> > OSError: [Errno 22] Invalid argument: '14:45:12.292166'
> > This looks like coming from datetime.datetime.now().time() (probably idk haven’t tested it)
> > On Windows, : is an [illegal character for a filename](https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names) (again probably haven’t tested it myself)
> > Just change torch.save(colorizer.generator.state_dict(), str(datetime.datetime.now().time())) into something like torch.save(colorizer.generator.state_dict(),str(whatever_for_a_checkpoint_filename))
> > I just remembered about : in Windows filenames are data streams from [this YouTube video](https://youtu.be/3BWTo87oCwc). Also check out [this article](https://owasp.org/www-community/attacks/Windows_alternate_data_stream) and [this blog](https://blog.netwrix.com/2022/12/16/alternate_data_stream/).
> 
> @tak2hu It didn't help.
> 
> ```python
> (manga-colorization) F:\manga-colorization>python train.py -g -p ./train -ft
> 19:32:30.383301
> Step : 0 Discr loss: 0.0000 Gen loss : 0.0000
> 
> 19:32:42.473506
> Epoch : 0 Discr loss: 1.3900 Gen loss : 0.0000
> 
> 19:32:42.684518
> Step : 0 Discr loss: 0.0000 Gen loss : 0.0000
> 
> 19:32:43.494637
> Epoch : 1 Discr loss: 0.0000 Gen loss : 14.8941
> 
> 19:32:43.727758
> Step : 0 Discr loss: 0.0000 Gen loss : 0.0000
> 
> 19:32:44.158929
> Epoch : 2 Discr loss: 1.3888 Gen loss : 0.0000
> 
> 19:32:44.365930
> Step : 0 Discr loss: 0.0000 Gen loss : 0.0000
> 
> 19:32:45.108161
> Epoch : 3 Discr loss: 0.0000 Gen loss : 18.3954
> 
> 19:32:45.346162
> Step : 0 Discr loss: 0.0000 Gen loss : 0.0000
> 19:32:51.401488
> Epoch : 11 Discr loss: 0.0000 Gen loss : 20.1612
> 
> 19:32:51.605481
> Step : 0 Discr loss: 0.0000 Gen loss : 0.0000
> 
> 19:32:52.024559
> Epoch : 12 Discr loss: 1.3793 Gen loss : 0.0000
> 
> 19:32:52.237559
> Step : 0 Discr loss: 0.0000 Gen loss : 0.0000
> 
> 19:32:52.806716
> Epoch : 13 Discr loss: 0.0000 Gen loss : 15.1746
> 
> 19:32:53.026233
> Step : 0 Discr loss: 0.0000 Gen loss : 0.0000
> 
> 19:32:53.423234
> Epoch : 14 Discr loss: 1.3789 Gen loss : 0.0000
> 
> Traceback (most recent call last):
>   File "train.py", line 294, in <module>
>     torch.save(colorizer.generator.state_dict(),str(whatever_for_a_checkpoint_filename))
> NameError: name 'whatever_for_a_checkpoint_filename' is not defined
> ```

**Comment by Omicronlawful** [comment]
@My12123 v2 is based on v1 so the model would work with minor changes. Look at the generators. He changed the python encoder blocks and the feature_conv got removed while an encoder was added instead. The rest is the same.

variables still need to be defined before usage to work

https://github.com/qweasdd/manga-colorization-v2/blob/master/networks/models.py#L185
https://github.com/qweasdd/manga-colorization/blob/master/model/models.py#L183

**Comment by Omicronlawful** [comment]
Btw why aren’t you trying to train deoldify as suggested in #360

**Comment by My12123** [comment]
@Omicronlawful 
https://github.com/Dakini/AnimeColorDeOldify
An error occurred while working
https://github.com/Dakini/AnimeColorDeOldify/issues/9

**Comment by Omicronlawful** [comment]
That’s a 2 year old fork of deoldify. With nogan of courses

**Comment by tak2hu** [comment]
> @tak2hu It didn't help.

Bruh define that variable yourself or just use a string like “mysavedmodel.pth” in place of str(whatever_for_a_checkpoint_filename).

I advise you to learn more (on how to modify someone else’s) python (project to suit your needs and environment). One step at a time.

**Comment by My12123** [comment]
@Omicronlawful 
I managed to run AnimeColorDeOldify.
https://colab.research.google.com/drive/1V2ld_pGiIGfKYDWRrDl2oAiNV-hLPf2C?usp=sharing

**Comment by Omicronlawful** [comment]
But it sucks so why would you run it. If you want good results you need to train the newer architecture with Nogan.

**Comment by Keiser04** [comment]
how do you can train?

**Comment by My12123** [comment]
@Keiser04 It is not possible to complete the training specifically to save the model.

**Comment by Keiser04** [comment]
but how did you get there? it's just that this bw thing I mentioned before is a problem and I can't investigate further so if you could help me (I'm working on collab) @My12123

**Comment by My12123** [comment]
@Keiser04 
I installed on windows. 
Run the following commands to install
```batchfile
python -m venv venv
call .\venv\Scripts\activate
pip install -r requirements.txt
``` 
The instruction is not complete

**Comment by My12123** [comment]
@Keiser04 
Can you describe the error in more detail?

**Comment by Keiser04** [comment]
i use your requeriments but i can't create a build due to matplotlib error
![imagen](https://github.com/zyddnys/manga-image-translator/assets/146493916/1db4f5e8-ad7c-427d-bc8c-d58010d6f8ce)

**Comment by My12123** [comment]
@Keiser04
https://github.com/qweasdd/manga-colorization/issues/2#issuecomment-1777182817
You need to create color and black and white yourself. see the link.  I do this when I had python 3.6 and it's better to use anaconda then there will be fewer possible errors.
datasets does not make significant changes, it only renames the color and black-and-white photo files and puts them in a special folder.
Today or Thursday I will try to build Wednesday on my PC. Then I can write in more detail.

**Comment by Keiser04** [comment]
![imagen](https://github.com/zyddnys/manga-image-translator/assets/146493916/0a43b4f0-d807-41d2-a78e-2b15e47d2b95)
this is my error. it is as if it was looking for the files in bw, but it adds for example "_0" to the file name. the problem is that it is random, now I will try with the first version of the training.

**Comment by Keiser04** [comment]
do you know what i can do? i try so much but still serching for an archive whit wrong name

**Comment by My12123** [comment]
@Keiser04 
```
Traceback (most recent call last):
  File "F:\manga-colorization\dataset\datasets.py", line 7, in <module>
    from utils.utils import generate_mask
ModuleNotFoundError: No module named 'utils.utils'
```

**Comment by Keiser04** [comment]
I got it too, it's a problem when trying to import the folder, you can do it by deleting untils.untils and leaving it as untils in training or specify the location.

**Comment by Keiser04** [comment]
@My12123 this are the versions of the program
https://github.com/qweasdd/manga-colorization/commits/master

**Comment by Keiser04** [comment]
This is my error, it comes from dataset.py
```
Train Dataset Length: 8
FineTuning Dataset Length: 8
Traceback (most recent call last):
  File "/content/manga-colorization/train.py", line 292, in <module>
    train(colorizer, discriminator, content, train_dataloader, config['epochs'], gen_optimizer, disc_optimizer, config['lr_decrease_epoch'], device)
  File "/content/manga-colorization/train.py", line 174, in train
    for n, inputs in enumerate(dataloader):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 674, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/manga-colorization/dataset/datasets.py", line 37, in __getitem__
    bw_img =  np.expand_dims(plt.imread(os.path.join(self.data_path, 'bw', bw_name)), 2)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/pyplot.py", line 2389, in imread
    return matplotlib.image.imread(fname, format)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/image.py", line 1525, in imread
    with img_open(fname) as image:
  File "/usr/local/lib/python3.10/dist-packages/PIL/ImageFile.py", line 105, in __init__
    self.fp = open(fp, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/content/manga-colorization/dataset/train/bw/a (6)_2.png'
```

**Comment by My12123** [comment]
I have.
```
(Manga_Colorization) F:\manga-colorization>python F:\manga-colorization\dataset\datasets.py
Traceback (most recent call last):
  File "F:\manga-colorization\dataset\datasets.py", line 7, in <module>
    from utils import generate_mask
ImportError: cannot import name 'generate_mask'
``` 
 Do you know how to fix something I don't remember anymore?

**Comment by Keiser04** [comment]
Type, it doesn't matter if you create the file or not or rename it, because the number after the "_" is a random one. I mean I tried it and at least in my case it was like that. That said, what name do you have the main folder with?  
@My12123

**Comment by Keiser04** [comment]
Or in the training file delete the untils.untils and replace it by untils

OR

import sys
sys.path.append('path_of_the_folder_untils')

**Comment by Keiser04** [comment]
Do you still have the dataset? the training is more or less working for me. @My12123

**Comment by My12123** [comment]
@Keiser04 
Not anymore, but it can be created. If you need help in creating, write.

**Comment by Keiser04** [comment]
Yes, if you can.... i have this error, the error that looks for more images is due to the fact that the configs file clarifies how many examples there are of each image, just change it from 1 to 3. I changed an image processor for a more current one and it worked but it stays there.
![imagen](https://github.com/zyddnys/manga-image-translator/assets/146493916/691135c2-225b-40c5-895a-ab4a069b54aa)

**Comment by Keiser04** [comment]
is that a local web app? I know more or less how to train a pix model although I never tried it, I have the collab if you want it. @My12123

**Comment by My12123** [comment]
@Keiser04 
Yes I do.

**Comment by Keiser04** [comment]
Can you sendme a exemple of dataset please??? My mail is sae89413@gmail.com. Or send me the link here

This is the git of the training
https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix

And this the colab
https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/pix2pix.ipynb

But we need to see what model it uses for it
