### ISSUE TITLE
做了个界面，你看能不能用？

### ISSUE THREAD

**Issue by 1439707509** [zyddnys/manga-image-translator#379]
https://github.com/1439707509/pygui

**Comment by zyddnys** [comment]
你完全用不着做成私人仓库，开源出来大家一起开发

**Comment by Omicronlawful** [comment]
It’s a private repo

**Comment by 1439707509** [comment]
> 你完全用不着做成私人仓库，开源出来大家一起开发

开源了

**Comment by Omicronlawful** [comment]
Translated:
@1439707509 这难道不只是一个没有与项目集成的命令行接口的包装器吗？它只适用于Windows，并且GPU参数似乎是硬编码的。更好的尝试将是一个调用外部服务器并使用API或直接使用Translator类的图形用户界面。目前，这只是一个用于构建CLI命令的工具。

**Comment by 1439707509** [comment]
> 翻译： @1439707509这难道不只是一个没有与项目集的指令行接口的封装器吗？它只适用于Windows，而GPU参数似乎是硬编码的。更好的尝试将是一个调用外部服务器并使用API​​或直接使用翻译器类的图形用户界面。目前，这只是一个用于构建CLI命令的工具。

我也只在 Windows 上用

**Comment by Omicronlawful** [comment]
为什么当它是专门为你设计的时候，你还想要合并它呢？

**Comment by 1439707509** [comment]
> 为什么当它是专为你设计的时候，你还想合并呢？

因为我不能一直维护和更新，所以想提交上去
