### ISSUE TITLE
want to add a function

### ISSUE THREAD

**Issue by 1439707509** [zyddnys/manga-image-translator#385]
Stack the two pictures together, the top picture only ocr bubbles, and then embed the ocr bubbles into the bottom picture

Only need ocr bubbles

Do not need the text inside the ocr bubble

![1](https://github.com/zyddnys/manga-image-translator/assets/128567416/7b1d744e-92d7-4d0b-948c-6a3a9792094b)
![2](https://github.com/zyddnys/manga-image-translator/assets/128567416/689b66b7-bf8e-4def-a353-8e1810f10263)
![3](https://github.com/zyddnys/manga-image-translator/assets/128567416/320b799c-ced4-4749-9f5f-8096311d9727)
![4](https://github.com/zyddnys/manga-image-translator/assets/128567416/6f6c4a17-b466-4713-a382-c247bc85f467)
![5](https://github.com/zyddnys/manga-image-translator/assets/128567416/81ff49c3-6cf1-4015-a844-99bd691e48a2)

https://github.com/zyddnys/manga-image-translator/assets/128567416/fdf0cb67-98fe-4d24-82ec-47ca025482c1

**Comment by zyddnys** [comment]
I will try adding this once i am available, i have been busy recently

**Comment by 1439707509** [comment]
> 我会在有空时尝试添加这个，我最近很忙

https://github.com/zyddnys/manga-image-translator/issues/386
