### ISSUE TITLE
[Bug]: When using manual translation, --force-horizontal is not applied. 

### ISSUE THREAD

**Issue by dnr111222** [zyddnys/manga-image-translator#391]
### Issue

When using manual translation (http://127.0.0.1:5003/manual), --force-horizontal is not applied. 
Example I used) python -m manga_translator -v --mode web --translator=papago -l KOR --force-horizontal

What should I do
![image](https://github.com/zyddnys/manga-image-translator/assets/42793507/c870a12b-910e-4433-9ac8-3a23289a3cfb)

**Comment by JustFrederik** [comment]
Install the missing module
