### ISSUE TITLE
Wrong clean region

### ISSUE THREAD

**Issue by marcussacana** [zyddnys/manga-image-translator#4]
First, thanks for the english optimizations, I hope this tool continue becaming better.
Anyway, I found that the tool tried to redraw the wrong region to clean the text,
![image](https://user-images.githubusercontent.com/10576957/117518390-e8ff1e00-af75-11eb-8e11-7b883b83accd.png)
This happened to me when I used `--size 3000`

**Comment by zyddnys** [comment]
Thank you for finding the problem.
The current text mask generation refinement involves a lot of hand craft method designed for lower resolution images(e.g. dilation kernel size), which leads to such erroneous text mask.
I am currently training a new model with better initial text mask proposal(ViT model) and better refinement(using CRF), improvements are to be expected.
No timeline for new model release as of now.
