### ISSUE TITLE
how to use the inpainter?

### ISSUE THREAD

**Issue by becktrack** [zyddnys/manga-image-translator#40]
i want to use the inpainter only for it to make all bubbles inside the manga i have blank so i can manually translate them
but the code is soo big and complex can you guide me or tell me hoe to use the inpainting only?

Thanks in advance.

**Comment by Eidenz** [comment]
This repo is focused for automated manga translation.

You're looking for something like SickZil Machine (https://github.com/KUR-creative/SickZil-Machine).

**Comment by zyddnys** [comment]
You can checkout code in `inpainting` folder, the `dispatch` function is what you want. All you need is the image data and a mask.
