### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by autumewater** [zyddnys/manga-image-translator#406]
### Issue

![image](https://github.com/zyddnys/manga-image-translator/assets/91417715/f72cf97d-431a-405c-99e6-d27b7d6e8e36)
 CUDA compatible device could not be found whilst --use-cuda args was set...

**Comment by zyddnys** [comment]
remove `--use-cuda` from your arguments

**Comment by thatDudo** [comment]
To use cuda on windows you have to first install cuda and second the correct pytorch version. We have some help regarding that in the installation section of the readme but google is your friend.
