### ISSUE TITLE
代码有问题

### ISSUE THREAD

**Issue by 1439707509** [zyddnys/manga-image-translator#407]
没有填写 openai key 时，即使没有使用 gpt，也会报错

chatgpt.py 188 行改成这样 就可以了

def chat_sample(self):#-> dict[str, List[str]]:

这个是执行的命令

python -m manga_translator -f jpg --translator=offline   --verbose --mode web --use-cuda --host=0.0.0.0

**Comment by zyddnys** [comment]
什么错误

**Comment by thatDudo** [comment]
Cant reproduce either. If you have an error message it would be helpful.

**Comment by 1439707509** [comment]
是在web模式下出现的，闪退的太快，截不了图

**Comment by 1439707509** [comment]
截到了，你们看看，错误是这样
![QQ截图20230617150319](https://github.com/zyddnys/manga-image-translator/assets/128567416/16f2049e-a997-4ea2-aa1d-439e3e81d1ef)
正常是这样的
![QQ截图20230617150406](https://github.com/zyddnys/manga-image-translator/assets/128567416/cabbcda2-b1d9-458f-8328-6e8e4ab5037b)

**Comment by 1439707509** [comment]
改了后，正常运行是这样的
![QQ截图20230617160647](https://github.com/zyddnys/manga-image-translator/assets/128567416/07cf7139-a82f-4162-abe1-d04e0b99db27)
