### ISSUE TITLE
Add sugoi translator offline support please!

### ISSUE THREAD

**Issue by bregassa** [zyddnys/manga-image-translator#41]
Hi,

I can't create API with DeepL because they won't accept my credit card.
Sugoi Translator translation quality is going on par with deepL currently
I hope you can add Sugoi Translator Offline integration.

Thanks for your tool, great work!

**Comment by bregassa** [comment]
So I  wrote it by myself at the end, I try to add wordwrap to the string, but it give me bunch of error from the other script. I wonder if there is a way to apply wordwrapping?
```
import requests
import hashlib
import urllib.parse
import random
import traceback
import json
import time
import textwrap

import aiohttp

class Translator(object):
	def __init__(self):
		pass

	async def translate(self, from_lang, to_lang, query_text):
		headers = {'Content-type': 'application/json'}
		data = {"content":query_text, "message":"translate sentences"}
		async with aiohttp.ClientSession() as session:
			async with session.post('http://localhost:14366', json=data, headers=headers) as resp:
				result = await resp.json(content_type=None)
		print(result)
		#lines = textwrap.wrap(result, 70, break_long_words=False)
		result_list = [result] #"is used to create a new line. When inserted in a string all the characters is used to create a new line. When inserted in a string all the characters"
		#for ret in result[0:5]
		#	result_list.extend(ret.split('\n'))
		return result_list


```

**Comment by zyddnys** [comment]
Translated texts must be the same number of lines (or same list length) as the input text, wrapping is done at rendering stage based on the size of region available.

**Comment by bregassa** [comment]
> Translated texts must be the same number of lines (or same list length) as the input text, wrapping is done at rendering stage based on the size of region available.

I wanna ask about this code in baidu 
So, the code I wrote only work if there's only one line in the image. If there's 2+ line, the inpaint will only typset in the first line box.

I can't undertand how this code work
```
		for ret in result["trans_result"]:
			for v in ret["dst"].split('\n') :
				result_list.append(v)
```
If I use this, I'll get TypeError: string indices must be integers.
Can you give me some insight about this?

**Comment by zyddnys** [comment]
Each text region can contain only one line. For most translators they will produce the same number of lines as the input text, so I can perform batch translation by simply concatenating all texts in an image to a single paragraph and later split them after translation.

**Comment by mspykerez** [comment]
@zyddnys  does your approach suffer from the issue mentioned here https://github.com/xulihang/ImageTrans-docs/issues/147 ?

**Comment by zyddnys** [comment]
In short, kind of.
The mantra paper's mentioning of order of text is mostly because they train their own translator. 
However this project uses existing translators which I assume are all based on NMT now which makes the order of texts matter to some extend. I don't have experience in building commercial NMT solution so I can't say how much.
As for the ordering of texts in this project, they are in scan line order.

**Comment by ryanolee** [comment]
^ This can probably be closed @zyddnys after https://github.com/zyddnys/manga-image-translator/pull/97 was merged
