### ISSUE TITLE
[Feature Request]: Do you support customizing the third-party OpenAI API address using the BASE_URL variable?

### ISSUE THREAD

**Issue by daiaji** [zyddnys/manga-image-translator#412]
### What would your feature do?

Like this
https://shadowwrite.com/v1/chat/completions

**Comment by greatxin** [comment]
use env like OPENAI_API_BASE=https://shadowwrite.com/v1 
顺带你有好的模型用来翻译吗，我用的Chinese-LLaMA-Alpaca部分内容会变成归纳而不是翻译

**Comment by greatxin** [comment]
顺带如果自建gpt的话建议将/manga_translator/translators/chatgpt.py 的121行的超时时间调高，默认的30秒在低端硬件上可能不够用

**Comment by thatDudo** [comment]
Yes we do support `OPENAI_API_BASE`. It should work if you put it into your .env file if you prefer that.

**Comment by thatDudo** [comment]
> 顺带如果自建gpt的话建议将/manga_translator/translators/chatgpt.py 的121行的超时时间调高，默认的30秒在低端硬件上可能不够用

I think this depends on the current server load but youre right. I increased it in a recent commit.
