### ISSUE TITLE
Upload Failed & Access is denies error

### ISSUE THREAD

**Issue by bregassa** [zyddnys/manga-image-translator#42]
I cloned the repo and install all the required module, but I get upload failed error with web mode

F:\Offline\Manga\[MTL] Machine Translation tool\manga-image-translator-main>python translate_demo.py --mode web --use-inpainting --verbose --translator=google --target-lang=ENG
Namespace(mode='web', image='', image_dst='', size=1536, use_inpainting=True, use_cuda=False, force_horizontal=False, inpainting_size=2048, unclip_ratio=2.3, box_threshold=0.7, text_threshold=0.5, text_mag_ratio=1, translator='google', target_lang='ENG', use_ctd=False, verbose=True)
 -- Loading models
 -- Running in web service mode
 -- Waiting for translation tasks
fail to initialize deepl :
auth_key must not be empty
switch to google translator
Serving up app on 127.0.0.1:5003

![image](https://user-images.githubusercontent.com/22976574/151701723-bbf4e0a5-028f-40db-b4f6-d68a70603e32.png)

Also, when I try to run batch translation, I get access denied error like this
F:\Offline\Manga\[MTL] Machine Translation tool\manga-image-translator-main>python translate_demo.py --image <F:\Offline\Manga\Sousaku Kanojo\lime message> --use-inpainting --verbose --translator=google --target-lang=ENG
Access is denied.

Anyone know the solution or maybe somethings is wrong with my command?

**Comment by zyddnys** [comment]
First problem fixed in 7e160cb574860579e49cafa22c58ff77203cef3b
The second problem is because you have <> around your file path.

**Comment by bregassa** [comment]
> First problem fixed in [7e160cb](https://github.com/zyddnys/manga-image-translator/commit/7e160cb574860579e49cafa22c58ff77203cef3b) The second problem is because you have <> around your file path.

I got another error with batch translation, it's working when I specify one png file, but I need the batch translation.

F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main>python translate_demo.py --image F:\lime_message\ --use-inpainting --verbose --translator=google --target-lang=ENG

Namespace(mode='demo', image='F:\\lime_message\\', image_dst='', size=1536, use_inpainting=True, use_cuda=False, force_horizontal=False, inpainting_size=2048, unclip_ratio=2.3, box_threshold=0.7, text_threshold=0.5, text_mag_ratio=1, translator='google', target_lang='ENG', use_ctd=False, verbose=True)
 -- Loading models
 -- Running in single image demo mode
[ WARN:0@4.347] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('F:\lime_message\'): can't open/read file: check file path/integrity
 -- Detection resolution 1536
 -- Detector using default
 -- Render text direction is auto
Traceback (most recent call last):
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 292, in <module>
    loop.run_until_complete(main(args.mode))
  File "C:\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 233, in main
    await infer(img, mode, '')
  File "F:\Offline\Visual Novel\[MTL] Machine Translation tool\manga-image-translator-main\translate_demo.py", line 96, in infer
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

**Comment by zyddnys** [comment]
You are supplying a directory to single image demo mode, that's why you are getting this error. You need `--mode batch` for batch translation.

**Comment by zyddnys** [comment]
I fixed this doc problem in bd874196bdb80f27e6c0285c6d59800267e71d4c

**Comment by bregassa** [comment]
> You are supplying a directory to single image demo mode, that's why you are getting this error. You need `--mode batch` for batch translation.

this work nicely
but for some reason the result from your demo and the result in my pc is different
here's the demo result
![final](https://user-images.githubusercontent.com/22976574/151707541-f8484b6c-9642-4434-811c-6732213d27c7.png)

and here's my result
![lime02_2_01](https://user-images.githubusercontent.com/22976574/151707550-5df312f7-8bc6-4919-8d11-bda75cba39a0.png)

can you tell me how to make the result become similar with the demo?

**Comment by bregassa** [comment]
and it will be nice if it can retain the transparent background in future update if it's possible..

**Comment by zyddnys** [comment]
Can you share an example image so I can take a look?

**Comment by bregassa** [comment]
> Can you share an example image so I can take a look?

here's the PNGs I need to translate
https://siasky.net/AABDEIUf1S8C5Xt07t1KIlpvwSJDwQPLZ053Pe80Qx8hxQ

**Comment by zyddnys** [comment]
fixed in 7bca49b987475382837dc75ce5f72bd95d8f4ed5

**Comment by bregassa** [comment]
> fixed in [7bca49b](https://github.com/zyddnys/manga-image-translator/commit/7bca49b987475382837dc75ce5f72bd95d8f4ed5)

great.. gray color issue is no more,
but is it possible to retain background transparency instead of giving it white background?

**Comment by zyddnys** [comment]
added in 04377f0500d1a03d7044e2be2648d5df14340dfe

**Comment by bregassa** [comment]
Awesome job.. thanks for the fix!
