### ISSUE TITLE
[Bug]: unusual memory usage 

### ISSUE THREAD

**Issue by purpleraven** [zyddnys/manga-image-translator#420]
### Issue

After upgrade to newest version of docker image I see unusual memory usage

![image](https://github.com/zyddnys/manga-image-translator/assets/20344446/289635ec-c86e-4595-857d-8e7dd5607249)

On the picture the container use 41Gb of memory

provious version of container has no the issue

**Comment by zyddnys** [comment]
do you know the version you were using before?

**Comment by purpleraven** [comment]
@zyddnys  no, something from March

**Comment by purpleraven** [comment]
@zyddnys you are not using versions for docker images. That makes life litle bit more complex

**Comment by purpleraven** [comment]
```
command: --verbose --translator=deepl --mode web --host=0.0.0.0 --port=5055 --upscale-ratio=1 --font-size-offset=10 --unclip-ratio=2

```

**Comment by zyddnys** [comment]
can you share the image you used? the memory used is heavily dependent on the image

**Comment by thatDudo** [comment]
The latest docker version was pushed two months ago https://hub.docker.com/r/zyddnys/manga-image-translator/tags

I tried to run the github workflow for docker but it failed to some weird reason.

**Comment by purpleraven** [comment]
@zyddnys I have updated to that version couple weeks ago and got a problem. 
I have used a previous version build in Aprile. 
I can't share the image. As can see memory growing continiusly. During that time many images processed (but not many).

**Comment by purpleraven** [comment]
@zyddnys thats happace periodically 
![image](https://github.com/zyddnys/manga-image-translator/assets/20344446/98d476f0-55bb-457a-aea4-1bba5835fc14)

Memory released without restart.
Maybe the image has possibility to limit the memory?

**Comment by purpleraven** [comment]
don't see it anymore in the logs
