### ISSUE TITLE
[Feature Request]: 能否设置对识别到的字符数少于一定长度不进行翻译

### ISSUE THREAD

**Issue by SoranoIkaros** [zyddnys/manga-image-translator#422]
### What would your feature do?

大部分翻译模型和api在面对语气词、单个单词没前后文的情况下，很难翻译正确。能否提供一个设置，当识别到的字符少于一定数量时不进行翻译

**Comment by zyddnys** [comment]
e2e5c1d9d7cd4d5270163084b4b643a9098f33dc 加了，参数里加上--min-text-length 4设置文本长度至少为4，也可以换成其他数值
