### ISSUE TITLE
[Feature Request]: 求助，文字的颜色识别是在什么地方做的啊？

### ISSUE THREAD

**Issue by yangmiemie99** [zyddnys/manga-image-translator#424]
### What would your feature do?

文字的颜色识别是在什么地方做的啊？ocr识别的时候会直接识别出文字的颜色？

**Comment by zyddnys** [comment]
OCR会给出文字和文字颜色

**Comment by zyddnys** [comment]
https://github.com/zyddnys/manga-image-translator/tree/main/training/ocr OCR训练用的模块，CTC返回文字概率以及6个实数，分别为文字和文本边框的RGB值

**Comment by ReynardLin** [comment]
请教一下，现在OCR出来的文字颜色准确率有统计吗，可用吗？
