### ISSUE TITLE
[Bug]: Unable to install pydensecrf in Colab

### ISSUE THREAD

**Issue by AChangAZha** [zyddnys/manga-image-translator#427]
### Issue

https://github.com/zyddnys/manga-image-translator/blob/e2e5c1d9d7cd4d5270163084b4b643a9098f33dc/run_as_colab.ipynb#L20
![Snipaste_2023-07-18_12-05-26](https://github.com/zyddnys/manga-image-translator/assets/80208659/b2adea0d-ff66-4259-a6ca-fb862cfcde9c)

### Console logs

```Shell
Collecting git+https://github.com/lucasb-eyer/pydensecrf.git
  Cloning https://github.com/lucasb-eyer/pydensecrf.git to /tmp/pip-req-build-_pra3iaz
  Running command git clone --filter=blob:none --quiet https://github.com/lucasb-eyer/pydensecrf.git /tmp/pip-req-build-_pra3iaz
  Resolved https://github.com/lucasb-eyer/pydensecrf.git to commit 0d53acbcf5123d4c88040fe68fbb9805fc5b2fb9
  Installing build dependencies ... done
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by http403** [comment]
Since PyDenseCRF is unmaintained and the developer is not responsive, should this project move to use other library instead?

**Comment by zyddnys** [comment]
Please refer to this issue https://github.com/lucasb-eyer/pydensecrf/issues/123
I will later fork and fix pydensecrf on new version of cython

**Comment by monolit** [comment]
is that fixed ?

> Please refer to this issue [lucasb-eyer/pydensecrf#123](https://github.com/lucasb-eyer/pydensecrf/issues/123) I will later fork and fix pydensecrf on new version of cython
