### ISSUE TITLE
[Bug]: Oops! We experienced an issue while translating your image.

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#436]
### Issue

![2023-08-04_18-08-20](https://github.com/zyddnys/manga-image-translator/assets/49092250/91ae3939-e094-4142-a12d-b462e38295ed)
Oops!
We experienced an issue while translating your image.
Task ID: lsw7e4tr454kb2fvj4ylrggf
Error ID: undefined

**Comment by zyddnys** [comment]
retry
