### ISSUE TITLE
[Bug]: It is outdated run_as_colab.ipynb

### ISSUE THREAD

**Issue by Juan-Cruz-Iturrioz** [zyddnys/manga-image-translator#439]
### Issue

You have to change the
!python -m pip install https://github.com/lucasb-eyer/pydensecrf.git -> https://github.com/kodalli/pydensecrf.git

And I have a personal question

How can I use the colab with https://greasyfork.org/en/scripts/374903-comicread
to be able to translate via a url or something like that

**Comment by mugnimaestra** [comment]
The Colab notebook has been fully updated in #1129 — fixes the outdated CLI flags, wrong port, and CUDA dependency issues. See #1130 for details.
