### ISSUE TITLE
There is no guide on how to use this. Does in work on browser ?

### ISSUE THREAD

**Issue by nguyenbh295** [zyddnys/manga-image-translator#442]
Hi, 
I've looked into you projects for couple days now but I still can firgure it out how to use it on manga/hentai. 

For example if I have this image url : https://exhentai.org/s/318d2d78e2/2643356-3

How can I use this tools to translate imapge in this url ?

**Comment by QiroNT** [comment]
Integration is not in the scope of this project.
I might pull i18n into [ComicRead](https://sleazyfork.org/scripts/374903) in the future, but I can't guarantee.
If you have a downloader script in hand, just download the manga and use `--mode batch` to translate the folder, it's not that complicated.
