### ISSUE TITLE
[Bug]: result file has been change from png to jpg 

### ISSUE THREAD

**Issue by purpleraven** [zyddnys/manga-image-translator#452]
### Issue

I see, that now result written to fina.jpg  and before it was final.png
is it configurable? 
Why it was changed?

Thx!

**Comment by thatDudo** [comment]
I assume you are talking about the web mode. If so you can change the format through `-f png`.

**Comment by purpleraven** [comment]
@thatDudo   yes, in the web
should I use it in the compose? 
> --f png

**Comment by thatDudo** [comment]
You can add `-f png` to the docker compose yml file you use.
For example if you use `docker-compose -f demo/doc/docker-compose-web-with-cpu.yml up` you can open the file "demo/doc/docker-compose-web-with-cpu.yml "
and replace: `command: --verbose --log-web --mode web --use-inpainting --host=0.0.0.0 --port=5003`
with: `command: --verbose --log-web --mode web --use-inpainting --host=0.0.0.0 --port=5003 -f png`

**Comment by purpleraven** [comment]
thx!
