### ISSUE TITLE
[Feature Request]: Split tall images before translate

### ISSUE THREAD

**Issue by Kolyada** [zyddnys/manga-image-translator#459]
### What would your feature do?

I worked with above mentioned image. Size is 771x13719.
And demo translator https://cotrans.touhou.ai/ ignore text trying to translate to russian.
After I split image to small parts (1k height or higher) and translate each one by one - almost all were translated.
Attached archive with original file, splitted parts and their translated results.

I have divided files with python script 
[split.py.txt](https://github.com/zyddnys/manga-image-translator/files/12602462/split.py.txt)
It should cut the images into small pieces but leave the text clouds intact.
It requires python3+pillow.
to call it: python3 split.py 2000 test_tall.jpeg
where 2000 is a min height to cut.

Is it possible to include into translator the slicing of tall images and collecting results into one image in the end?

[test_tall.zip](https://github.com/zyddnys/manga-image-translator/files/12602428/test_tall.zip)

**Comment by zyddnys** [comment]
i think it's already supported
