### ISSUE TITLE
[Bug]: 程序入口在哪里

### ISSUE THREAD

**Issue by zzisbeauty** [zyddnys/manga-image-translator#462]
### Issue

我想知道程序入口在哪里，我想debug看看代码的过程，但是代码好复杂。我找不到入口，我只是找到了基类的位置manga_translator.py，但是我不知道我该如何从入口处运行代码。希望得到指点与帮助。

**Comment by AI-confused** [comment]
https://blog.csdn.net/sunjw_2017/article/details/120996874
可以参考这个链接，入口文件应该是manga_translator/__main__.py
