### ISSUE TITLE
[Bug]: Does not work with INPUT argument

### ISSUE THREAD

**Issue by Kolyada** [zyddnys/manga-image-translator#469]
### Issue

Wanted to run translator via docker in batch mode.
Current command `sudo docker run -p 5003:5003 -v /home/user/Docker/result:/app/result --ipc=host --rm zyddnys/manga-image-translator:main -l ENG --manga2eng -v --mode web --host=0.0.0.0 --port=5003` works fine

But when I run `sudo docker run -p 5003:5003 -v /home/user/Docker/result:/app/result --ipc=host --rm zyddnys/manga-image-translator:main -l ENG --manga2eng -v --mode batch --host=0.0.0.0 --port=5003 -i /home/test`

I got an error `manga_translator: error: argument -i/--input: No such file or directory: "/home/test"`

But `/home/test` exists and contains image files to translate. I tried with another directories and same error.

**Comment by zyddnys** [comment]
you are running docker, did you map location in your host machine to one inside docker container?
