### ISSUE TITLE
[Bug]: error-translating when processing image with only target language texts

### ISSUE THREAD

**Issue by Dar9586** [zyddnys/manga-image-translator#472]
### Issue

While I was translating a folder in batch mode using one of the latest version of this program (3c4bf721fb84593147a5613a4b0529a957f07211) I noted some images have been skipped (they were processed but the output file was not generated). I noted the problem was it only contained an english word in the entire image and that word was in English (my target language).
I created this minimal image which also triggers the same behaviour if translated to english:
![ghost](https://github.com/zyddnys/manga-image-translator/assets/11708347/ffe93db0-8e51-4297-b64f-d3fe28ec0eb6)

When this image is processed this line causes the region to be skipped:
https://github.com/zyddnys/manga-image-translator/blob/3c4bf721fb84593147a5613a4b0529a957f07211/manga_translator/manga_translator.py#L468
since this is the only region the function `_run_text_translation` returns an empty array. 
The check in this line then generates a `error-translating` state which skips the generation of the output file:
https://github.com/zyddnys/manga-image-translator/blob/3c4bf721fb84593147a5613a4b0529a957f07211/manga_translator/manga_translator.py#L366-L368

### Expected behaviour
This case should have the same behaviour as an image without text. for example when processing this empty image
![white](https://github.com/zyddnys/manga-image-translator/assets/11708347/6e128608-5f9d-4293-8a26-2d3fa4fd096b)
The state `skip-no-text` is used instead and an image equal to the original is generated as output.

### Command Line Arguments

```Shell
-i "ghost.png" --verbose -l ENG --translator=deepl
```

### Console logs

```Shell
[demo] Namespace(mode='demo', input=['ghost.png'], dest='', target_lang='ENG', verbose=True, format=None, detector='default', ocr='48px_ctc', inpainter='lama_mpe', upscaler='esrgan', upscale_ratio=None, colorizer=None, translator='deepl', translator_chain=None, selective_translation=None, use_cuda=False, use_cuda_limited=False, model_dir=None, attempts=0, ignore_errors=False, overwrite=False, revert_upscaling=False, detection_size=1536, det_rotate=False, det_auto_rotate=False, det_invert=False, det_gamma_correct=False, unclip_ratio=2.3, box_threshold=0.7, text_threshold=0.5, min_text_length=0, inpainting_size=2048, colorization_size=576, denoise_sigma=30, font_size=None, font_size_offset=0, font_size_minimum=-1, font_color=None, force_horizontal=False, force_vertical=False, align_left=False, align_center=False, align_right=False, uppercase=False, lowercase=False, no_hyphenation=False, manga2eng=False, gpt_config=None, mtpe=False, save_text=False, save_text_file='', filter_text=None, prep_manual=False, font_path='', gimp_font='Sans-serif', host='127.0.0.1', port=5003, nonce='', ws_url='ws://localhost:5000', save_quality=100, ignore_bubble=0)
[demo] Running in demo mode
[demo] Translating: "/home/user/Git/manga-image-translator/ghost.png"
[demo] Loading models
[demo] Running text detection
[DefaultDetector] Adding border
[DefaultDetector] Detection resolution: 1536x1536
[demo] Running ocr
[Model48pxCTCOCR] prob: 0.9996917860694716 GHOST fg: (3, 4, 4) bg: (2, 2, 3)
[demo] Running text translation
[DeeplTranslator] Translating into English
[DeeplTranslator] 0: GHOST => GHOST
[demo] Filtered out: GHOST
WARNING: [demo] Text translator returned empty queries
```

**Comment by thatDudo** [comment]
It seems I have forgotten to assign the `ctx.result` value there.
Im not sure anymore but perhaps this is because I expected that in that case there must have been some kind of error and not that it would get filtered out. Maybe we should rather throw an exception from inside the translator if there is that kind of problem with translating.

Thanks for taking the time for writing the report.
