### ISSUE TITLE
[Feature Request]:  Adding contributors section to the README.md file.

### ISSUE THREAD

**Issue by Kalyanimhala** [zyddnys/manga-image-translator#491]
### What would your feature do?

There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
![contributors](https://github.com/zyddnys/manga-image-translator/assets/147402107/6be26a33-c397-4254-a318-0df90d5a5825)

**Comment by Kalyanimhala** [comment]
@thatDudo Kindly assign me this issue, I want to work on it. Thank You!!

**Comment by zyddnys** [comment]
you can work on it now
