### ISSUE TITLE
[Bug]: 48px ocr error: TransformerEncoderLayer._sa_block() got an unexpected keyword argument 'is_causal'

### ISSUE THREAD

**Issue by 1439707509** [zyddnys/manga-image-translator#503]
### Issue

cmd=D:\trans\Scripts\python.exe -m manga_translator --mode batch --target-lang=CHS   -i C:/Users/zero/Desktop/1 -o C:/Users/zero/Desktop/1-translated  -f jpg --translator=gpt3.5 --detector default    --ocr 48px   --use-cuda

[batch] Running in batch mode
[batch] Translating: "C:\Users\zero\Desktop\1\008.jpg"
[batch] Loading models
[batch] Running text detection
[DefaultDetector] Detection resolution: 1024x1536
[batch] Running ocr
ERROR: [batch] TypeError: TransformerEncoderLayer._sa_block() got an unexpected keyword argument 'is_causal'

### Command Line Arguments

```Shell
D:\trans\Scripts\python.exe -m manga_translator --mode batch --target-lang=CHS   -i C:/Users/zero/Desktop/1 -o C:/Users/zero/Desktop/1-translated  -f jpg --translator=gpt3.5 --detector default    --ocr 48px   --use-cuda
```

**Comment by zyddnys** [comment]
fixed
