### ISSUE TITLE
[Feature Request]: Why is the accuracy not improved by the new OCR model, but increased time and resource consumption?

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#505]
### What would your feature do?

[Model48pxOCR] prob: 0.8959104418754578
[Model48pxOCR] prob: 0.5768305063247681
Model48pxOCR] prob: 0.29753056168556213
![2023-11-13_20-25-54](https://github.com/zyddnys/manga-image-translator/assets/49092250/b448d210-93f9-4803-9dcc-61d86862888e)

- [ ] Add the ability to set accuracy.
- [ ] Add fast OCR and slow OCR of choice.

**Comment by zyddnys** [comment]
you can just use `--ocr 48px_ctc` to switch back to old OCR
