### ISSUE TITLE
[Bug]: 各位大佬救救孩子吧

### ISSUE THREAD

**Issue by xiaowarxx** [zyddnys/manga-image-translator#510]
### Issue

我用的是docker搭建的，为什么用不了chatgpt的api呢，搞了好久没没弄明白
![c5c5c6e3da5dca97e73a17239c1ff79](https://github.com/zyddnys/manga-image-translator/assets/150873620/358f3f9c-bbab-4cf9-8ecf-8d22cc778c28)
![7bbff45b7ca46b571dc830196f9afd4](https://github.com/zyddnys/manga-image-translator/assets/150873620/4734d377-4f92-4c6f-879e-0175a2798631)

**Comment by jianchang512** [comment]
使用的第三方api接口吧，接口地址不对，试试分别 加末尾 /v1和不加。

**Comment by xiaowarxx** [comment]
nb，谢谢大佬，加了/v1就好了。
________________________________
发件人: okaymyworld ***@***.***>
发送时间: 2023年11月15日 16:38
收件人: zyddnys/manga-image-translator ***@***.***>
抄送: xiaowarxx ***@***.***>; State change ***@***.***>
主题: Re: [zyddnys/manga-image-translator] [Bug]: 各位大佬救救孩子吧 (Issue #510)


使用的第三方api接口吧，接口地址不对，试试分别 加末尾 /v1和不加。

―
