### ISSUE TITLE
Errno 111 & Errno 99和无法输出翻译后的图片

### ISSUE THREAD

**Issue by 1071974393** [zyddnys/manga-image-translator#511]
该如何修复
无法输出图片的问题同
https://github.com/zyddnys/manga-image-translator/issues/511

`manga_image_translator_cpu  | New `submit` task de6ee5468b91189a1d5a122d93d6f52256aa3edcc95e3b01ba99d72452a7f0a1-1536-google-CHS-default-auto
manga_image_translator_cpu  | [web_client] Processing task de6ee5468b91189a1d5a122d93d6f52256aa3edcc95e3b01ba99d72452a7f0a1-1536-google-CHS-default-auto
manga_image_translator_cpu  | [web_client] Translating: "/app/result/de6ee5468b91189a1d5a122d93d6f52256aa3edcc95e3b01ba99d72452a7f0a1-1536-google-CHS-default-auto/input.jpg"
manga_image_translator_cpu  | [web_client] Loading models
manga_image_translator_cpu  | [web_client] Running text detection
manga_image_translator_cpu  | Task state de6ee5468b91189a1d5a122d93d6f52256aa3edcc95e3b01ba99d72452a7f0a1-1536-google-CHS-default-auto to {'info': 'detection', 'finished': False}
manga_image_translator_cpu  | [DefaultDetector] Detection resolution: 1280x1536
manga_image_translator_cpu  | [web_client] Running ocr
manga_image_translator_cpu  | Task state de6ee5468b91189a1d5a122d93d6f52256aa3edcc95e3b01ba99d72452a7f0a1-1536-google-CHS-default-auto to {'info': 'ocr', 'finished': False}
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.8310220837593079 TU fg: (2, 0, 0) bg: (2, 0, 0)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9313901662826538 OK fg: (5, 6, 4) bg: (5, 6, 4)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9994528889656067 iME fg: (4, 3, 0) bg: (4, 3, 0)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.8125967979431152 .LAS fg: (3, 3, 0) bg: (3, 3, 0)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9710354208946228 VE Y fg: (2, 4, 1) bg: (3, 5, 2)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9034749865531921 SOLO fg: (6, 8, 3) bg: (6, 8, 3)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9627550840377808 i¿DE fg: (0, 1, 3) bg: (0, 1, 3)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9999679327011108 EN EL fg: (1, 3, 1) bg: (2, 4, 2)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9996346831321716 AH, NO fg: (4, 2, 0) bg: (4, 3, 1)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.33076462149620056 SOFAY fg: (6, 7, 3) bg: (7, 7, 3)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9999271631240845 NTATE fg: (0, 0, 0) bg: (0, 0, 0)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9999594688415527 YA QUE fg: (5, 7, 1) bg: (6, 8, 1)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9999011754989624 VAMOS A fg: (6, 6, 1) bg: (6, 6, 2)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9846951365470886 PRESÉ- fg: (0, 1, 0) bg: (0, 1, 0)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9999009370803833 ESTO ES fg: (0, 0, 0) bg: (0, 0, 0)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9998419880867004 EN UNA fg: (0, 0, 0) bg: (1, 1, 0)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9999328255653381 PROBAR fg: (3, 4, 0) bg: (3, 4, 0)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9993935227394104 SIENTATE fg: (0, 0, 0) bg: (0, 0, 0)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9999549984931946 MATERIAL fg: (5, 6, 0) bg: (5, 6, 0)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9999269843101501 VAMOS A fg: (8, 11, 2) bg: (9, 11, 2)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.6072721481323242 POR HOY fg: (5, 3, 0) bg: (5, 4, 0)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9998502135276794 PARA QUE fg: (1, 4, 0) bg: (1, 4, 0)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9992972612380981 SUBIR ESTE fg: (0, 0, 0) bg: (1, 1, 0)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.4078536927700043 VERDAD⁈ fg: (2, 4, 1) bg: (2, 4, 1)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9889658093452454 CÁMARAS fg: (3, 5, 2) bg: (3, 5, 2)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9828805923461914 iLO HARE! fg: (3, 3, 0) bg: (3, 4, 1)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9996858239173889 PRACTIQUES. fg: (2, 2, 0) bg: (2, 2, 0)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9904360175132751 CONVERTIRÉ fg: (1, 2, 0) bg: (1, 2, 0)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9999209642410278 NEW-TUBER! fg: (0, 0, 0) bg: (0, 0, 0)
manga_image_translator_cpu  | Task state de6ee5468b91189a1d5a122d93d6f52256aa3edcc95e3b01ba99d72452a7f0a1-1536-google-CHS-default-auto to {'info': 'textline_merge', 'finished': False}
manga_image_translator_cpu  | [web_client] Running text translation
manga_image_translator_cpu  | Task state de6ee5468b91189a1d5a122d93d6f52256aa3edcc95e3b01ba99d72452a7f0a1-1536-google-CHS-default-auto to {'info': 'translating', 'finished': False}
manga_image_translator_cpu  | [GoogleTranslator] Translating into Chinese (Simplified)
manga_image_translator_cpu  | Task state de6ee5468b91189a1d5a122d93d6f52256aa3edcc95e3b01ba99d72452a7f0a1-1536-google-CHS-default-auto to {'info': 'error', 'finished': True}
manga_image_translator_cpu  | ERROR: [web_client] ConnectError: Multiple exceptions: [Errno 111] Connect call failed ('127.0.0.1', 443), [Errno 111] Connect call failed ('0.0.0.0', 443), [Errno 99] Cannot assign requested address, [Errno 99] Cannot assign requested address
manga_image_translator_cpu  | Traceback (most recent call last):
manga_image_translator_cpu  |   File "/app/manga_translator/__main__.py", line 73, in <module>
manga_image_translator_cpu  |     loop.run_until_complete(dispatch(args))
manga_image_translator_cpu  |   File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_completemanga_image_translator_cpu  |     return future.result()
manga_image_translator_cpu  |   File "/app/manga_translator/__main__.py", line 50, in dispatch
manga_image_translator_cpu  |     await translator.listen(args_dict)
manga_image_translator_cpu  |   File "/app/manga_translator/manga_translator.py", line 727, in listen
manga_image_translator_cpu  |     await self.translate_path(self._result_path('input.jpg'), self._result_path('final.jpg'),
manga_image_translator_cpu  |   File "/app/manga_translator/manga_translator.py", line 151, in translate_path
manga_image_translator_cpu  |     await self.translate_file(path, _dest, params)
manga_image_translator_cpu  |   File "/app/manga_translator/manga_translator.py", line 202, in translate_file
manga_image_translator_cpu  |     return await self._translate_file(path, dest, ctx)
manga_image_translator_cpu  |   File "/app/manga_translator/manga_translator.py", line 245, in _translate_file
manga_image_translator_cpu  |     ctx = await self.translate(img, ctx)
manga_image_translator_cpu  |   File "/app/manga_translator/manga_translator.py", line 303, in translate
manga_image_translator_cpu  |     return await self._translate(ctx)
manga_image_translator_cpu  |   File "/app/manga_translator/manga_translator.py", line 409, in _translate
manga_image_translator_cpu  |     ctx.text_regions = await self._run_text_translation(ctx)
manga_image_translator_cpu  |   File "/app/manga_translator/manga_translator.py", line 739, in _run_text_translation
manga_image_translator_cpu  |     text_regions = await super()._run_text_translation(ctx)
manga_image_translator_cpu  |   File "/app/manga_translator/manga_translator.py", line 504, in _run_text_translation
manga_image_translator_cpu  |     translated_sentences = await dispatch_translation(ctx.translator,
manga_image_translator_cpu  |   File "/app/manga_translator/translators/__init__.py", line 119, in dispatch
manga_image_translator_cpu  |     queries = await translator.translate('auto', tgt_lang, queries, use_mtpe)
manga_image_translator_cpu  |   File "/app/manga_translator/translators/common.py", line 181, in translate
manga_image_translator_cpu  |     _translations = await self._translate(*self.parse_language_codes(from_lang, to_lang, fatal=True), queries)
manga_image_translator_cpu  |   File "/app/manga_translator/translators/google.py", line 156, in _translate
manga_image_translator_cpu  |     translation = await self._translate_query(from_lang, to_lang, '\n'.join(lang_queries))manga_image_translator_cpu  |   File "/app/manga_translator/translators/google.py", line 199, in _translate_query
manga_image_translator_cpu  |     raise encountered_exception
manga_image_translator_cpu  |   File "/app/manga_translator/translators/google.py", line 193, in _translate_query
manga_image_translator_cpu  |     return await self._request_and_parse_translation(query, to_lang, from_lang)
manga_image_translator_cpu  |   File "/app/manga_translator/translators/google.py", line 203, in _request_and_parse_translation
manga_image_translator_cpu  |     data, response = await self._request_translation(query, to_lang, from_lang)
manga_image_translator_cpu  |   File "/app/manga_translator/translators/google.py", line 311, in _request_translation
manga_image_translator_cpu  |     r = await self.client.post(url, params=params, data=data)
manga_image_translator_cpu  |   File "/opt/conda/lib/python3.10/site-packages/httpx/_client.py", line 1374, in post
manga_image_translator_cpu  |     return await self.request(
manga_image_translator_cpu  |   File "/opt/conda/lib/python3.10/site-packages/httpx/_client.py", line 1147, in request
manga_image_translator_cpu  |     response = await self.send(
manga_image_translator_cpu  |   File "/opt/conda/lib/python3.10/site-packages/httpx/_client.py", line 1168, in send
manga_image_translator_cpu  |     response = await self.send_handling_redirects(
manga_image_translator_cpu  |   File "/opt/conda/lib/python3.10/site-packages/httpx/_client.py", line 1195, in send_handling_redirects
manga_image_translator_cpu  |     response = await self.send_handling_auth(
manga_image_translator_cpu  |   File "/opt/conda/lib/python3.10/site-packages/httpx/_client.py", line 1232, in send_handling_auth
manga_image_translator_cpu  |     response = await self.send_single_request(request, timeout)
manga_image_translator_cpu  |   File "/opt/conda/lib/python3.10/site-packages/httpx/_client.py", line 1264, in send_single_request
manga_image_translator_cpu  |     ) = await transport.request(
manga_image_translator_cpu  |   File "/opt/conda/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 152, in request
manga_image_translator_cpu  |     response = await connection.request(
manga_image_translator_cpu  |   File "/opt/conda/lib/python3.10/site-packages/httpcore/_async/connection.py", line 65, in request
manga_image_translator_cpu  |     self.socket = await self._open_socket(timeout)
manga_image_translator_cpu  |   File "/opt/conda/lib/python3.10/site-packages/httpcore/_async/connection.py", line 85, in _open_socket
manga_image_translator_cpu  |     return await self.backend.open_tcp_stream(
manga_image_translator_cpu  |   File "/opt/conda/lib/python3.10/site-packages/httpcore/_backends/auto.py", line 38, in open_tcp_stream
manga_image_translator_cpu  |     return await self.backend.open_tcp_stream(hostname, port, ssl_context, timeout)
manga_image_translator_cpu  |   File "/opt/conda/lib/python3.10/site-packages/httpcore/_backends/asyncio.py", line 229, in open_tcp_stream
manga_image_translator_cpu  |     with map_exceptions(exc_map):
manga_image_translator_cpu  |   File "/opt/conda/lib/python3.10/contextlib.py", line 153, in __exit__
manga_image_translator_cpu  |     self.gen.throw(typ, value, traceback)
manga_image_translator_cpu  |   File "/opt/conda/lib/python3.10/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
manga_image_translator_cpu  |     raise to_exc(exc) from None
manga_image_translator_cpu  | httpcore._exceptions.ConnectError: Multiple exceptions: [Errno 111] Connect call failed ('127.0.0.1', 443), [Errno 111] Connect call failed ('0.0.0.0', 443), [Errno 99] Cannot assign requested address, [Errno 99] Cannot assign requested address
manga_image_translator_cpu  | Restarting translator process
manga_image_translator_cpu  | [web_client] Namespace(mode='web_client', input=None, dest='', target_lang='CHS', verbose=True, format=None, attempts=0, ignore_errors=False, overwrite=False, skip_no_text=False, model_dir=None, use_cuda=False, use_cuda_limited=False, detector='default', ocr='48px', inpainter='lama_large', upscaler='esrgan', upscale_ratio=None, colorizer=None, translator='google', translator_chain=None, selective_translation=None, revert_upscaling=False, detection_size=1536, det_rotate=False, det_auto_rotate=False, det_invert=False, det_gamma_correct=False, unclip_ratio=2.3, box_threshold=0.7, text_threshold=0.5, min_text_length=0, inpainting_size=2048, inpainting_precision='fp32', colorization_size=576, denoise_sigma=30, mask_dilation_offset=0, font_size=None, font_size_offset=0, font_size_minimum=-1, font_color=None, line_spacing=None, force_horizontal=False, force_vertical=False, align_left=False, align_center=False, align_right=False, uppercase=False, lowercase=False, no_hyphenation=False, manga2eng=False, gpt_config=None, use_mtpe=False, save_text=False, save_text_file='', filter_text=None, prep_manual=False, font_path='', gimp_font='Sans-serif', host='0.0.0.0', port=5003, nonce='900890122aa89be0bc0aed9456568413', ws_url='ws://localhost:5000', save_quality=100, ignore_bubble=0)
`

**Comment by zyddnys** [comment]
你是什么参数启动的

**Comment by 1071974393** [comment]
> 你是什么参数启动的

我是用Docker安的，按照此流程走，所有步骤都已完成，ChatGPT api是买的，OPENAI_API_BASE 也已填写购买站要求的内容，于其他地方成功调用此api。但在此运行就出现以上报错，抱歉本人不懂代码
https://github.com/hymbz/ComicReadScript/blob/master/docs/manga-image-translator.md

**Comment by 1071974393** [comment]
> 你是什么参数启动的

启动参数应该是上面链接内的内容，用docker启动的，`docker-compose up`拉起的镜像，下面这应该是配置

`manga_image_translator_cpu  | [web_client] Namespace(mode='web_client', input=None, dest='', target_lang='CHS', verbose=True, format=None, attempts=0, ignore_errors=False, overwrite=False, skip_no_text=False, model_dir=None, use_cuda=False, use_cuda_limited=False, detector='default', ocr='48px', inpainter='lama_large', upscaler='esrgan', upscale_ratio=None, colorizer=None, translator='google', translator_chain=None, selective_translation=None, revert_upscaling=False, detection_size=1536, det_rotate=False, det_auto_rotate=False, det_invert=False, det_gamma_correct=False, unclip_ratio=2.3, box_threshold=0.7, text_threshold=0.5, min_text_length=0, inpainting_size=2048, inpainting_precision='fp32', colorization_size=576, denoise_sigma=30, mask_dilation_offset=0, font_size=None, font_size_offset=0, font_size_minimum=-1, font_color=None, line_spacing=None, force_horizontal=False, force_vertical=False, align_left=False, align_center=False, align_right=False, uppercase=False, lowercase=False, no_hyphenation=False, manga2eng=False, gpt_config=None, use_mtpe=False, save_text=False, save_text_file='', filter_text=None, prep_manual=False, font_path='', gimp_font='Sans-serif', host='0.0.0.0', port=5003, nonce='b450c1f27dedf58d1b1ad0ec290f82e6', ws_url='ws://localhost:5000', save_quality=100, ignore_bubble=0)`

用chatgptAPI无法完成翻译发现是api请求超时，随即换成谷歌翻译，可以翻译，但是无法输出翻译后的图片，那么用chatgptAPI即使api请求正常，翻译完成也无法正常输出图片，因此想要优先解决此无法输出翻译后图片的问题。以下是用谷歌翻译的运行代码

`manga_image_translator_cpu  | [web_client] Running in web_client mode
manga_image_translator_cpu  | [web_client] Waiting for translation tasks
manga_image_translator_cpu  | New `submit` task fef3e156830477085cf3a38a957d468278f04b87e30ac62637d874e9cc19079f-2560-google-CHS-ctd-auto
manga_image_translator_cpu  | [web_client] Processing task fef3e156830477085cf3a38a957d468278f04b87e30ac62637d874e9cc19079f-2560-google-CHS-ctd-auto
manga_image_translator_cpu  | [web_client] Translating: "/app/result/fef3e156830477085cf3a38a957d468278f04b87e30ac62637d874e9cc19079f-2560-google-CHS-ctd-auto/input.jpg"
manga_image_translator_cpu  | [web_client] Loading models
manga_image_translator_cpu  | [web_client] Running text detection
manga_image_translator_cpu  | Task state fef3e156830477085cf3a38a957d468278f04b87e30ac62637d874e9cc19079f-2560-google-CHS-ctd-auto to {'info': 'detection', 'finished': False}
manga_image_translator_cpu  | [web_client] Running ocr
manga_image_translator_cpu  | Task state fef3e156830477085cf3a38a957d468278f04b87e30ac62637d874e9cc19079f-2560-google-CHS-ctd-auto to {'info': 'ocr', 'finished': False}
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.7905890941619873 わ fg: (0, 1, 2) bg: (0, 1, 2)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.38937705755233765 Q fg: (241, 238, 239) bg: (241, 238, 239)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.8459981083869934 リ ーなア fg: (6, 10, 3) bg: (6, 10, 3)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.8978748917579651 ー てよ」 fg: (5, 11, 7) bg: (5, 11, 7)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9134405255317688 メ さんに fg: (2, 3, 0) bg: (2, 3, 0)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9992300271987915 悠 斗んち fg: (4, 4, 2) bg: (4, 4, 2)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9986869096755981 ホ ント？ fg: (0, 2, 1) bg: (0, 2, 1)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9991863965988159 小 児病棟で fg: (4, 3, 3) bg: (4, 3, 3)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9996863007545471 悠 斗だった fg: (4, 5, 2) bg: (4, 5, 2)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9999767541885376 俺 は隠し子 fg: (5, 4, 1) bg: (5, 4, 1)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9996418952941895 遊 び人だけど fg: (9, 8, 6) bg: (9, 8, 6)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9842078685760498 人 に見えたー fg: (5, 5, 3) bg: (5, 5, 3)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9999759793281555 お 金持ちって fg: (0, 1, 0) bg: (0, 1, 0)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9997668266296387 親 父に養って fg: (1, 2, 0) bg: (1, 2, 0)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9442508816719055 も らうかなヱ fg: (1, 3, 0) bg: (1, 3, 0)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9999672174453735 か ら卒業したら fg: (3, 3, 1) bg: (3, 3, 1)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9999423027038574 会 社経営してて fg: (0, 3, 1) bg: (0, 3, 1)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9999669194221497 金 払いだけはいい fg: (2, 5, 2) bg: (2, 5, 2)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9998766183853149 私 とは別世界の fg: (6, 7, 4) bg: (6, 7, 4)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9999216794967651 逆 境を隠しもせず fg: (5, 6, 3) bg: (5, 6, 3)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9998205900192261 う ちってか親父が fg: (1, 2, 0) bg: (1, 2, 0)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.997757077217102 絵本の読みきかせ？ fg: (1, 3, 3) bg: (1, 3, 3)
manga_image_translator_cpu  | [Model48pxOCR] prob: 0.9981608390808105 悠 々と生きる姿が fg: (5, 5, 3) bg: (5, 5, 3)
manga_image_translator_cpu  | Task state fef3e156830477085cf3a38a957d468278f04b87e30ac62637d874e9cc19079f-2560-google-CHS-ctd-auto to {'info': 'textline_merge', 'finished': False}
manga_image_translator_cpu  | [web_client] Running text translation
manga_image_translator_cpu  | Task state fef3e156830477085cf3a38a957d468278f04b87e30ac62637d874e9cc19079f-2560-google-CHS-ctd-auto to {'info': 'translating', 'finished': False}
manga_image_translator_cpu  | [GoogleTranslator] Translating into Chinese (Simplified)
manga_image_translator_cpu  | [GoogleTranslator] 0: 悠斗だった => 是你的
manga_image_translator_cpu  | [GoogleTranslator] 1: 俺は隠し子 => 我是个 隐藏的孩子
manga_image_translator_cpu  | [GoogleTranslator] 2: うちってか親父が 会社経営してて => 父亲经营公司
manga_image_translator_cpu  | [GoogleTranslator] 3: わ 悠斗んち お金持ち って ホント？ => Yuto Yuto Chichi真的有钱吗？
manga_image_translator_cpu  | [GoogleTranslator] 4: 金払いだけはいい から卒業したら 親父に養って もらうかなヱ => 仅付款还可以，所以如果我毕业，我 想知道父亲是否会喂它。
manga_image_translator_cpu  | [GoogleTranslator] 5: リーなア メさんに ー てよ」 => 到Lee Ame -San。”
manga_image_translator_cpu  | [GoogleTranslator] 6: 小児病棟で 絵本の読みきかせ？ => 在小儿病房里阅读图画书？
manga_image_translator_cpu  | [GoogleTranslator] 7: Q => 问
manga_image_translator_cpu  | [GoogleTranslator] 8: 悠々と生きる姿が 私とは別世界の 人に見えたー => 活着的生活似乎是与我不同的世界中的人们
manga_image_translator_cpu  | [GoogleTranslator] 9: 遊び人だけど 逆境を隠しもせず => 我是一名球员，但我不隐藏逆境
manga_image_translator_cpu  | Task state fef3e156830477085cf3a38a957d468278f04b87e30ac62637d874e9cc19079f-2560-google-CHS-ctd-auto to {'info': 'after-translating', 'finished': False}
manga_image_translator_cpu  | [web_client] Running mask refinement
manga_image_translator_cpu  | Task state fef3e156830477085cf3a38a957d468278f04b87e30ac62637d874e9cc19079f-2560-google-CHS-ctd-auto to {'info': 'mask-generation', 'finished': False}
[mask]:   0%|                                           | 0/23 [00:00<?, [mask]:  83%|███████████████████████████▎     | 19/23 [00:00<00:00, 180.4[mask]: 100%|█████████████████████████████████| 23/23 [00:00<00:00, 168.27it/s]
manga_image_translator_cpu  | Task state fef3e156830477085cf3a38a957d468278f04b87e30ac62637d874e9cc19079f-2560-google-CHS-ctd-auto to {'info': 'inpainting', 'finished': False}
manga_image_translator_cpu  | [LamaLargeInpainter] Inpainting resolution: 1280x1864
manga_image_translator_cpu  | Restarting translator process`
[url=https://freeimage.host/i/JncYLut][img]https://iili.io/JncYLut.md.png[/img][/url]
去文字也同样无法输出图片
[url=https://freeimage.host/i/JncE6cG][img]https://iili.io/JncE6cG.md.png[/img][/url]

**Comment by 1071974393** [comment]
https://github.com/zyddnys/manga-image-translator/issues/483
类似输出问题，已解决，原因：OOM
--inpainting-size INPAINTING_SIZE            Size of image used for inpainting (too large will
                                             result in OOM)
