### ISSUE TITLE
[Feature Request]: Security Improvements

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#516]
### What would your feature do?
Addition to #509
![2023-11-20_16-08-06](https://github.com/zyddnys/manga-image-translator/assets/49092250/1f30e29e-68b0-47b9-b94a-f26bdb52dc43)
![2023-11-20_16-09-03](https://github.com/zyddnys/manga-image-translator/assets/49092250/c74a2cd8-59a6-4e7a-813b-239111f3033b)
![2023-11-20_16-10-52](https://github.com/zyddnys/manga-image-translator/assets/49092250/d383ec4d-08c2-4e37-a3fd-ff1fa7d8d1f4)

**Comment by singersbalm** [comment]
1) the performance is still good. It’s not like it’s checking thousands of chars
2) will break the api & it’s not sensitive
3) that’s most likely a default defect query found on the internet. Bett er pro change it

**Comment by zyddnys** [comment]
is_url removed
