### ISSUE TITLE
[Feature Request]: Using Metal programming framework for high-performance inference

### ISSUE THREAD

**Issue by allegro0132** [zyddnys/manga-image-translator#521]
### What would your feature do?

Hi, thanks for your great work! I would like to request a new feature, and I already wrote some code to realize it. 

This project already has `--use-cuda` option for accelerating with compatible NVIDIA GPU, but we still have different accelerator cards. For example, using Metal makes the computation run on the GPU, the frameworks like `Pytorch` and `llama.cpp` could harness those FLOPS.

I propose to add a new option `--use-mps` to enable Apple's GPU accelerator, and have implemented some steps with mps support.

- [x] Detection
- [x] OCR
- [x] Translation by LLM inference
- [ ] Inpainting

The GPU-CPU history figure shows OCR and LLM steps offload to GPU, and Inpainting still runs in CPU (Pytorch does not implement some math operator). 
![1700901905962](https://github.com/zyddnys/manga-image-translator/assets/34514398/b8604778-a5b1-4c6a-9dbb-0a49f815e817)

Related commit: https://github.com/allegro0132/manga-image-translator/commit/a8e47e729b2c19ab695149d1b4a0384fde81547c

**Comment by BigEmperor26** [comment]
I found the same issue. I found it the speed improvement is not amazing (M1 Pro) by moving detection and OCR to MPS. I found some issues moving Inpainting because of missing complex handling of use cuda flag. Probably we could keep MPS temporarly as -use-cuda-limited.

**Comment by BigEmperor26** [comment]
I created a PR

https://github.com/zyddnys/manga-image-translator/pull/533

The operation unsupported flag can be skipped by setting the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1`

**Comment by allegro0132** [comment]
Thanks for your contribution~ I will close this issue soon.
