### ISSUE TITLE
[Feature Request]: hugging face被墙，希望能把模型放到墙里一份

### ISSUE THREAD

**Issue by 975765132** [zyddnys/manga-image-translator#527]
### What would your feature do?

诸如https://huggingface.co/zyddnys/manga-image-translator/resolve/main/ocr_ar_48px.ckpt
这种自动下载的模型都没法直接获取，希望能添加一个墙里能访问(GitHub、Gitee、网盘...)的链接

考虑下呗，梯子扛不住那么大流量（小声）

**Comment by zyddnys** [comment]
a143e385bfe1effc5b2b2fc2a28a06d12a764520 改了

**Comment by 975765132** [comment]
感动~
