### ISSUE TITLE
GPT settings

### ISSUE THREAD

**Issue by buriburix5** [zyddnys/manga-image-translator#540]
Just a stupid question. I got GPT API but keep getting "Restarting request due to ratelimiting by openai servers" and "openai.error.RateLimitError: You exceeded your current quota", I also tried download fixed file from a certain issue topic. Did I miss something or do I have to change anything in GPT config or do I have to go one by one instead of batch or do I need to have GPT Plus?

**Comment by Grachy** [comment]
You not only need GPT Plus, you need to buy tokens for API use.

**Comment by buriburix5** [comment]
So that's the problem, tks. I thought it was bc i sent too many requests
