### ISSUE TITLE
[Bug]: 在web模式下gui中无法正常上传原图

### ISSUE THREAD

**Issue by wyyyz1937365497** [zyddnys/manga-image-translator#556]
### Issue

![image](https://github.com/zyddnys/manga-image-translator/assets/140365984/482afaa8-0c42-4da1-a65c-d6d8476df3e2)
![image](https://github.com/zyddnys/manga-image-translator/assets/140365984/1c46ca0f-f4c4-4944-8a0d-9be198eb82f6)
![image](https://github.com/zyddnys/manga-image-translator/assets/140365984/65726e16-c867-44eb-96e9-322408013d34)
cmd里面一直没有响应，但是deom和batch模式都可以正常使用。api的test可以正常通过，但是用comic read调用本地api无响应
![image](https://github.com/zyddnys/manga-image-translator/assets/140365984/f3a6b6e1-362c-4ddf-8765-8ce480a95f74)
直接访问api的响应
谢谢大佬的指教

**Comment by wyyyz1937365497** [comment]
全过程中没有任何的报错

**Comment by zyddnys** [comment]
你是什么参数启动的，我这里没有问题

**Comment by wyyyz1937365497** [comment]
谢谢您的帮助，是我自己的问题，清华源的有些依赖版本太老了，vs里面更新就好了
😊😊👌

**Comment by wyyyz1937365497** [comment]
> 你是什么参数启动的，我这里没有问题

谢谢您的帮助，是我自己的问题，清华源的有些依赖版本太老了，vs里面更新就好了
😊😊👌
