### ISSUE TITLE
May I know how to use deepl in python ?

### ISSUE THREAD

**Issue by freezingyip** [zyddnys/manga-image-translator#565]
Sorry, I don't know how to set DEEPL_AUTH_KEY in python. Could you help me ?

**Comment by freezingyip** [comment]
how to set a env variable?

**Comment by singersbalm** [comment]
On Mac and any other Unix based operating system its "export". More infos here: https://www.man7.org/linux/man-pages/man1/export.1p.html

docker has  --env to pass in env variables

**Comment by freezingyip** [comment]
thank you! problem solved

export  DEEPL_AUTH_KEY=xxxx
