### ISSUE TITLE
freetype.ft_errors.FT_Exception: FT_Exception:  (cannot open resource)

### ISSUE THREAD

**Issue by Ben0981** [zyddnys/manga-image-translator#57]
When i try to have something translated i get always get the error stated in the name of the issue. I simply took the commands from the usage section and adjusted the path for the translate_demo.py file and of course the images. I get the error when using batch mode or single image mode so it's not limited to just one mode. Here ist the full error message i get:
Traceback (most recent call last):
  _File "D:\manga-image-translator-main\translate_demo.py", line 334, in <module>
    loop.run_until_complete(main(args.mode))
  File "C:\Users\Strah\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "D:\manga-image-translator-main\translate_demo.py", line 237, in main
    text_render.prepare_renderer()
  File "D:\manga-image-translator-main\text_rendering\text_render.py", line 481, in prepare_renderer
    CACHED_FONT_FACE.append(freetype.Face(font_filename))
  File "C:\Users\Strah\AppData\Local\Programs\Python\Python310\lib\site-packages\freetype\__init__.py", line 1101, in __init__
    raise FT_Exception(error)
 freetype.ft_errors.FT_Exception: FT_Exception:  (cannot open resource)_

**Comment by zyddnys** [comment]
Can you make sure all 4 font files are present in `fonts/`?

**Comment by Ben0981** [comment]
One was missing but i get the same error after adding it so that doesn't seem to cause it.

**Comment by zyddnys** [comment]
Try changing `['fonts/Arial-Unicode-Regular.ttf', 'fonts/msyh.ttc', 'fonts/msgothic.ttc']` in https://github.com/zyddnys/manga-image-translator/blob/main/text_rendering/text_render.py#L478 to `['fonts\\Arial-Unicode-Regular.ttf', 'fonts\\msyh.ttc', 'fonts\\msgothic.ttc']`

**Comment by Ben0981** [comment]
I changed it everywhere in the file but i still get the exact same error as both times before.

**Comment by zyddnys** [comment]
Can you try removing freetype-py and reinstall it?

**Comment by Ben0981** [comment]
The issue still remains except that it is now in line 340 instead of 334

**Comment by alb-ctrl** [comment]
I ran with the same issue
I am using a MacBook and running the script in CLI from the root directory. 
It fixed by cd to the project folder.
I guess it has to do with relative and absolute paths

**Comment by zyddnys** [comment]
Try fix proposed by @alb-ctrl

**Comment by AhnafS** [comment]
i tried that, it didnt work. didnt have this problem before so kinda confused

**Comment by thatDudo** [comment]
I have added a commit that turns the default font paths into absolute paths.
