### ISSUE TITLE
Question about the accuracy of the ocr_48px_ctc model.

### ISSUE THREAD

**Issue by stringie** [zyddnys/manga-image-translator#570]
I love accuracy of the new 48px ocr model but it's too slow for me, so I checked out the other version, the 48px_ctc model.
It is much faster, which is awesome, but for some reason it is much less accurate, which is very unfortunate. I don't know if that's just how the model is or if I'm doing something wrong with it. Here is an example image which I used for testing: 

![2](https://github.com/zyddnys/manga-image-translator/assets/23170702/d5aff0c8-cf22-4db7-b78d-70ec23e5a346)

When I run it locally, the 48px_ctc ocr model seems to skip characters from certain sentences or even entire lines ...

Please help me with this issue, I really need a fast and reliable model. Why is the ctc model so unreliable? I must be doing something wrong. Thank you!

**Comment by zyddnys** [comment]
the reason i trained new 48px is because the old 48px_ctc is not very accurate, so there's not much one can do to improve 48px_ctc now
