### ISSUE TITLE
There is a difference between the new code and the old code in using none to process the text in the picture. The new code cannot process the text in the picture.

### ISSUE THREAD

**Issue by 1439707509** [zyddnys/manga-image-translator#573]
新代码和老代码，在用none处理图片里文字上，有区别，新代码不能处理图片里的文字

There is a difference between the new code and the old code in using none to process the text in the picture. The new code cannot process the text in the picture.

原图
![013](https://github.com/zyddnys/manga-image-translator/assets/128567416/27dafc24-ae13-4e5a-ad28-5e14ec0d84c8)
新代码
![013](https://github.com/zyddnys/manga-image-translator/assets/128567416/92661344-a3a7-4058-81d0-d11461d33567)
老代码
![013](https://github.com/zyddnys/manga-image-translator/assets/128567416/78261f86-86a9-4e6c-b6aa-9cf7f1699452)

**Comment by jianchang512** [comment]
![final](https://github.com/zyddnys/manga-image-translator/assets/3378335/a21cbd65-8d3f-4e24-b1c5-e86d1b8b597f)

新代码处理后

**Comment by 1439707509** [comment]
> ![最终的](https://private-user-images.githubusercontent.com/3378335/304350847-a21cbd65-8d3f-4e24-b1c5-e86d1b8b597f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4ODY4MTgsIm5iZiI6MTcwNzg4NjUxOCwicGF0aCI6Ii8zMzc4MzM1LzMwNDM1MDg0Ny1hMjFjYmQ2NS04ZDNmLTRlMjQtYjFjNS1lODZkMWI4YjU5N2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTRUMDQ1NTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDJjZTI5ZDA1YWJlYzAzY2U1YjllNDQ5YmRhZjU4MzFmZTU5YWVhMTU2ZmM3ODQyMGFjYzhkZDA5Njg1ODJhNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.x53N8FEvBjWtKFdanJtY1CD1HayOIFu61jTJtm4glnc)
> 
> 新代码处理后

这样看来，新代码的none效果，不如老代码好，我还是用回老代码吧
