### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 3079848852** [zyddnys/manga-image-translator#576]
### Issue

请问我创建的文件是在F盘，为啥启动PowerShell安装的依赖项和模型会被安装在c盘，导致我c盘爆满了。。。

**Comment by zyddnys** [comment]
因为python的库会装在python在的位置，默认是c盘

**Comment by 3079848852** [comment]
> 因为python的库会装在python在的位置，默认是c盘

没法改路径吗？
