### ISSUE TITLE
Cannot open include file: 'mecab.h': No such file or directory for fugashi

### ISSUE THREAD

**Issue by Vortexakhaj** [zyddnys/manga-image-translator#582]
### Issue

OS- Windows 11
py - 3.12.2
![D24 02 25_T20 28 50 772_WindowsTerminal_064](https://github.com/zyddnys/manga-image-translator/assets/21369699/89fedb48-2ce8-479a-89d8-ec740f586e4a)

**Comment by memputate** [comment]
Currently experiencing the same issue on Windows 10.

**Comment by zyddnys** [comment]
use python 3.11

**Comment by Vortexakhaj** [comment]
Thanks that seems to have solved the issue.
Would be good to mention that **py 3.12** still doesn't work with this.

**Comment by zyddnys** [comment]
there's no pre built wheel of fugashi for py 3.12, so unless fugashi's author release one there's no fixing this
