### ISSUE TITLE
请问在哪里配置翻译服务（API key） Where can I configure the translation service (API key)

### ISSUE THREAD

**Issue by sssman234** [zyddnys/manga-image-translator#592]
费尽千辛万苦终于配置好了环境，请问在哪个界面配置翻译服务（powershell cmd dockers）？

After putting in a lot of effort, the environment has finally been configured. May I ask which interface to configure the translation service (powershell cmd dockers) on?

**Comment by zyddnys** [comment]
manga_translator/translators/keys.py
