### ISSUE TITLE
[Bug]: Api Mode error

### ISSUE THREAD

**Issue by paul0728** [zyddnys/manga-image-translator#593]
### Issue

{"error": "Internal Server Error", "status": 500}
![螢幕擷取畫面 2024-03-22 164411](https://github.com/zyddnys/manga-image-translator/assets/44644609/ca8f8296-2d9b-44f5-bfe8-2be6533284a3)

![螢幕擷取畫面 2024-03-22 164401](https://github.com/zyddnys/manga-image-translator/assets/44644609/46767703-fb75-48c7-923a-f5d150d88d26)

### Command Line Arguments

python -m manga_translator -v --mode api --use-gpu --port 5004

**Comment by zyddnys** [comment]
API mode is not meant to be opened in browser, please read the documentation https://github.com/zyddnys/manga-image-translator?tab=readme-ov-file#api-documentation

**Comment by starise-wg** [comment]
我也遇到同样的问题，使用命令python -m manga_translator -v --mode api --use-gpu 后正常启动，使用postman进行接口测试时报错{
    "error": "Internal Server Error",
    "status": 500
}
![error](https://github.com/zyddnys/manga-image-translator/assets/30431507/5b17bf77-af7e-4678-96c5-4131f1b6db70)
