### ISSUE TITLE
[Bug]: Segmentation Fault (Core Dumped)

### ISSUE THREAD

**Issue by Wired-cell** [zyddnys/manga-image-translator#601]
### Issue

Translator Gives Segmentation Fault (Core Dumped) when using sugoi with argument --use-gpu . The argument works fine with google as translator. When the argument is removed, the sugoi translator takes a long time but works fine. Using this on an older gpu with 2 gb vram. 
![Screenshot from 2024-04-07 11-10-55](https://github.com/zyddnys/manga-image-translator/assets/149601494/ce86d7b4-1590-42a8-aca3-b9442446ee3f)

### Command Line Arguments

```Shell
python -m manga_translator -v --use-gpu --translator=sugoi -l ENG -i /home/user/Downloads/Folder
```

**Comment by zyddnys** [comment]
2gb is not enough vram, you can remove --use-gpu to use CPU

**Comment by Wired-cell** [comment]
Yeah I figured that out when it worked on gtx 1080. But wanted to use it on my home server pc .Well , Thanks for clearing my doubt
