### ISSUE TITLE
[Bug]: rendering takes forever

### ISSUE THREAD

**Issue by rhve** [zyddnys/manga-image-translator#625]
### Issue

i ran the code in colab and it would be fine yesterday, but when i ran the same code again today, the rendering couldn't complete.

### Command Line Arguments

```Shell
!python -m manga_translator -v --translator=papago --use-gpu -l ENG -i "/content/drive/MyDrive/png/2225306"
```

### Console logs

```Shell
[mask]: 100% 6/6 [00:00<00:00, 121.12it/s]
[LamaLargeInpainter] Inpainting resolution: 1280x960
[batch] Running rendering
[render] font_size_minimum 11
[render]:   0% 0/2 [01:13<?, ?it/s]
```

**Comment by zyddnys** [comment]
try again

**Comment by rotarzen** [comment]
This occurs due to the slowness of the cgit.freedesktop.org repository used in hyphen.dictools upstream.

You can patch hyphenator to source .dic files via GitHub to resolve this. The following diff will work for en_US:

```diff
diff --git a/manga_translator/rendering/text_render.py b/manga_translator/rendering/text_render.py
index a3f2797..51170d9 100644
--- a/manga_translator/rendering/text_render.py
+++ b/manga_translator/rendering/text_render.py
@@ -6,7 +6,7 @@ import freetype
 import functools
 from pathlib import Path
 from typing import Tuple, Optional, List
-from hyphen import Hyphenator
+from hyphen import Hyphenator as Horig
 from hyphen.dictools import LANGUAGES as HYPHENATOR_LANGUAGES
 from langcodes import standardize_tag
 
@@ -18,6 +18,24 @@ try:
 except Exception:
     pass
 
+
+def Hyphenator(l: str="en_US"):
+    assert l == "en_US", "other languages not supported yet"
+    import requests
+    from pathlib import Path
+    from hyphen.dictools import Dictionaries
+
+    HYPHEN_PATH = Path('./dictools')
+    HYPHEN_PATH.mkdir(exist_ok=True)
+    DIC_PATH = HYPHEN_PATH / "hyph_{l}.dic"
+    URL = f'https://github.com/LibreOffice/dictionaries/raw/master/en/hyph_{l}.dic'
+    if not DIC_PATH.exists():
+        res = requests.get(URL)
+        DIC_PATH.write_bytes(res.content)
+
+    Dictionaries("dictools").add(l, DIC_PATH.read_bytes(), [l], URL)
+    return Horig(l, directory=str(HYPHEN_PATH), use_description=False)
+
 CJK_H2V = {
     "‥": "︰",
     "—": "︱",
```
On my machine this makes rendering instantaneous again.

**Comment by pt-boop** [comment]
> This occurs due to the slowness of the cgit.freedesktop.org repository used in hyphen.dictools upstream.
> 
> You can patch hyphenator to source .dic files via GitHub to resolve this. The following diff will work for en_US:
> 
> ```diff
> diff --git a/manga_translator/rendering/text_render.py b/manga_translator/rendering/text_render.py
> index a3f2797..51170d9 100644
> --- a/manga_translator/rendering/text_render.py
> +++ b/manga_translator/rendering/text_render.py
> @@ -6,7 +6,7 @@ import freetype
>  import functools
>  from pathlib import Path
>  from typing import Tuple, Optional, List
> -from hyphen import Hyphenator
> +from hyphen import Hyphenator as Horig
>  from hyphen.dictools import LANGUAGES as HYPHENATOR_LANGUAGES
>  from langcodes import standardize_tag
>  
> @@ -18,6 +18,24 @@ try:
>  except Exception:
>      pass
>  
> +
> +def Hyphenator(l: str="en_US"):
> +    assert l == "en_US", "other languages not supported yet"
> +    import requests
> +    from pathlib import Path
> +    from hyphen.dictools import Dictionaries
> +
> +    HYPHEN_PATH = Path('./dictools')
> +    HYPHEN_PATH.mkdir(exist_ok=True)
> +    DIC_PATH = HYPHEN_PATH / "hyph_{l}.dic"
> +    URL = f'https://github.com/LibreOffice/dictionaries/raw/master/en/hyph_{l}.dic'
> +    if not DIC_PATH.exists():
> +        res = requests.get(URL)
> +        DIC_PATH.write_bytes(res.content)
> +
> +    Dictionaries("dictools").add(l, DIC_PATH.read_bytes(), [l], URL)
> +    return Horig(l, directory=str(HYPHEN_PATH), use_description=False)
> +
>  CJK_H2V = {
>      "‥": "︰",
>      "—": "︱",
> ```
> 
> On my machine this makes rendering instantaneous again.

thank you very much you really save me to
