### ISSUE TITLE
[Feature Request]: Local LLM Server tranlation support

### ISSUE THREAD

**Issue by eren-ay** [zyddnys/manga-image-translator#626]
### What would your feature do?

LMStudio support for various llm translation llama3 etc

**Comment by DoomedSouls** [comment]
Or [ollama](https://github.com/ollama/ollama) here is a list of models that can translate Japanese to English.
[Aya-23-8B](https://huggingface.co/CohereForAI/aya-23-8B)
[Aya-23-35B](https://huggingface.co/CohereForAI/aya-23-35B)
[Meta-Llama-3-8B](https://huggingface.co/meta-llama/Meta-Llama-3-8B)
[Meta-Llama-3-70B](https://huggingface.co/meta-llama/Meta-Llama-3-70B)
[Qwen2-7B](https://huggingface.co/Qwen/Qwen2-7B)
[Qwen2-72B](https://huggingface.co/Qwen/Qwen2-72B)
