### ISSUE TITLE
[Bug]: "After starting with Docker, it prompts: FileNotFoundError."

### ISSUE THREAD

**Issue by shineforever** [zyddnys/manga-image-translator#633]
### Issue

Hello, developer.
This project is excellent, but I encountered a file not found issue while running Docker. Could you please help me take a look?

docker compose file:
version: "3.8"
services:
  manga_image_translator:
    image: zyddnys/manga-image-translator:main
    container_name: manga_image_translator_cpu
    command: --verbose --mode web --host=0.0.0.0 --port=5003
    #command: --verbose --mode web  --host=0.0.0.0 --port=5003
    volumes:
      - ./../../result:/app/result
    ports:
      - 5003:5003
    ipc: host

After successfully starting up, when I try to upload an image for translation, the backend throws an error:
![image](https://github.com/zyddnys/manga-image-translator/assets/1472799/4cce6da7-974b-4383-ba58-7ad63eba9623)

Upon checking the corresponding directory, I found that the image actually exists, but its extension is ".png".

![image](https://github.com/zyddnys/manga-image-translator/assets/1472799/7b126428-e1b3-4719-be13-db1890019aec)

How can I solve this issue? Looking forward to your response.

### Console logs

```Shell
manga_image_translator_cpu  | [web_client] Running in web_client mode
manga_image_translator_cpu  | [web_client] Waiting for translation tasks
manga_image_translator_cpu  | [SakuraTranslator] 您当前选择了Sakura 0.9版本，暂不支持术语表
manga_image_translator_cpu  | New `submit` task faa6354b87cb6b743926962bc2d9c394b12f9639d2d081c8c3bdc4e598c8ea5c-1024-google-CHS-default-auto
manga_image_translator_cpu  | [web_client] Processing task faa6354b87cb6b743926962bc2d9c394b12f9639d2d081c8c3bdc4e598c8ea5c-1024-google-CHS-default-auto
manga_image_translator_cpu  | ERROR: [web_client] FileNotFoundError: /app/result/faa6354b87cb6b743926962bc2d9c394b12f9639d2d081c8c3bdc4e598c8ea5c-1024-google-CHS-default-auto/input.jpg
manga_image_translator_cpu  | Traceback (most recent call last):
manga_image_translator_cpu  |   File "/app/manga_translator/__main__.py", line 73, in <module>
manga_image_translator_cpu  |     loop.run_until_complete(dispatch(args))
manga_image_translator_cpu  |   File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
manga_image_translator_cpu  |     return future.result()
manga_image_translator_cpu  |   File "/app/manga_translator/__main__.py", line 50, in dispatch
manga_image_translator_cpu  |     await translator.listen(args_dict)
manga_image_translator_cpu  |   File "/app/manga_translator/manga_translator.py", line 750, in listen
manga_image_translator_cpu  |     await self.translate_path(self._result_path('input.jpg'), self._result_path('final.jpg'),
manga_image_translator_cpu  |   File "/app/manga_translator/manga_translator.py", line 125, in translate_path
manga_image_translator_cpu  |     raise FileNotFoundError(path)
manga_image_translator_cpu  | FileNotFoundError: /app/result/faa6354b87cb6b743926962bc2d9c394b12f9639d2d081c8c3bdc4e598c8ea5c-1024-google-CHS-default-auto/input.jpg
manga_image_translator_cpu  | Restarting translator process
```

**Comment by Aikin-Ai** [comment]
It's probably the same error as #627. For now, you can look at the commit that broke it, c101755, and modify the files to change the extensions in the code back to .jpg. It fixed the problem for me.

**Comment by zyddnys** [comment]
fixed
