### ISSUE TITLE
请问SyntaxError: invalid syntax怎么解决

### ISSUE THREAD

**Issue by blacklein** [zyddnys/manga-image-translator#65]
<img width="701" alt="截屏2022-06-15 12 40 33" src="https://user-images.githubusercontent.com/69177971/173738125-7b6c4459-3880-49ee-8cc6-f8ac57bc9380.png">

如上图所示，谢谢！

**Comment by QiroNT** [comment]
截图一下 `python -V` 的输出？

**Comment by blacklein** [comment]
我是macbook pro M1 pro，python指向2.x，python改成python3后没有跳错，但也没其他反应
python3 translate_demo.py --verbose --use-inpainting --use-cuda --translator=google --target-lang=ENG --image </Users/xxx/Downloads/manga-image-translator/input.jpeg>
跳出错误：
zsh: parse error near `\n'

**Comment by QiroNT** [comment]
文件名不用带 `<>`，只是提示你是个参数而已

**Comment by blacklein** [comment]
`❯ python3 translate_demo.py --verbose --use-inpainting --use-cuda --translator=baidu --target-lang=CHS --image /Users/chenzhiyu/Downloads/manga-image-translator/input.jpeg
Traceback (most recent call last):
  File "/Users/chenzhiyu/Downloads/manga-image-translator/translate_demo.py", line 15, in <module>
    from text_mask import dispatch as dispatch_mask_refinement
  File "/Users/chenzhiyu/Downloads/manga-image-translator/text_mask/__init__.py", line 8, in <module>
    from .text_mask_utils import complete_mask_fill, filter_masks, complete_mask
  File "/Users/chenzhiyu/Downloads/manga-image-translator/text_mask/text_mask_utils.py", line 94, in <module>
    from pydensecrf.utils import compute_unary, unary_from_softmax
ModuleNotFoundError: No module named 'pydensecrf'`

这次跳出上面的错误

**Comment by QiroNT** [comment]
`pydensecrf` 需要手动装一下，我没有 mac 不知道该跑什么，可以搜搜去。
中文文档貌似没写 `pydensecrf` 相关的那段，我等会补上。

**Comment by blacklein** [comment]
macbook pro 用pip3 install pydensecrf 安装报错，readme里面的binary是windows的，请问有mac的版本吗？

**Comment by QiroNT** [comment]
用 `pip3 install git+https://github.com/lucasb-eyer/pydensecrf.git` 什么的试试。
App 的话可以算是[已经有了](https://github.com/dmMaze/BallonsTranslator)，之前其实还有个在线编辑器的日程，不过感觉太忙了排不上了。
Electron 太拉跨了，写也不会用，这也不是 js 项目，不过感谢建议。

**Comment by blacklein** [comment]
按照上面的命令行成功安装pydensecrf，mac 运行python3 translate_demo.py --verbose --mode web --use-inpainting --use-cuda 报错，把--use-cude删除后serving成功

mac安装pydensecrf需要运行：pip3 install git+https://github.com/lucasb-eyer/pydensecrf.git
mac用浏览器打开demo需要运行：python3 translate_demo.py --verbose --mode web --use-inpainting

给碰到相同问题的同学留个笔记，谢谢作者解惑！
