### ISSUE TITLE
[Feature Request]: Can multiple GPUs be supported?

### ISSUE THREAD

**Issue by chou18194766xx** [zyddnys/manga-image-translator#655]
### What would your feature do?

It seems that multi-GPU support is not available, or maybe I missed something. How can I enable the multi-GPU working mode? This is quite important on platforms like Kaggle or Colab.

**Comment by zyddnys** [comment]
do you need multiple GPU because a single one doesn't have enough VRAM?

**Comment by chou18194766xx** [comment]
> do you need multiple GPU because a single one doesn't have enough VRAM?

Thank you for your reply.
Most of the time it is sufficient, but sometimes I have to deal with tens of thousands of high-resolution pictures and I want to speed it up. Looking at the idle GPU, I wonder if I can use it and double the processing speed.

**Comment by zyddnys** [comment]
you can start multiple processes and use CUDA_VISIBLE_DEVICES  to select a GPU

**Comment by chou18194766xx** [comment]
> you can start multiple processes and use CUDA_VISIBLE_DEVICES to select a GPU你可以启动多个进程，并使用 CUDA_VISIBLE_DEVICES 来选择 GPU

Thank you
