### ISSUE TITLE
是否能出个精简版的模型 或者分离下

### ISSUE THREAD

**Issue by mutsumi63** [zyddnys/manga-image-translator#66]
beta 0.2 的时候和之前好像4g显存就能跑，beta 0.3就要6g才行

**Comment by zyddnys** [comment]
模型用的是默认选项吗？

**Comment by mutsumi63** [comment]
> 模型用的是默认选项吗？

是的 默认的
python translate_demo.py --mode batch --image "Z:\manga" --use-inpainting --use-cuda --verbose --translator=baidu

**Comment by zyddnys** [comment]
你可以把inpainting的分辨率降下去，默认是2048，可以使用`--inpainting-size 1024`调整这个分辨率。

**Comment by mutsumi63** [comment]
> 你可以把inpainting的分辨率降下去，默认是2048，可以使用`--inpainting-size 1024`调整这个分辨率。

可以运行了 谢谢解答
