### ISSUE TITLE
[Bug]: windows系统openai库0.28版本没有AsyncOpenAI模块导致不能使用chatgpt、sakura等进行翻译

### ISSUE THREAD

**Issue by a1084278809** [zyddnys/manga-image-translator#665]
### Issue

 windows系统openai库0.28版本没有AsyncOpenAI模块，更新到1.+的版本之后会出现googletrans 4.0.0rc1 requires httpx==0.13.3, but you have httpx 0.27.0 which is incompatible的依赖错误导致google翻译又变的不可用，不更新的话又不能使用sakura等翻译

**Comment by a1084278809** [comment]
你说的这个我也会，我也可以升级openai库版本，这样的话chatgpt和sakura能用，然后google用不了了，但是还是希望能有一个google、chatgpt、sakura直接就都能共存的版本

**Comment by Ctory-Nily** [comment]
测试后发现环境变量必须给到一个OPENAI_API_KEY
但是chatgpt.py中不会接收到这个OPENAI_API_KEY仍然是空值,此时我直接把将key写到了 keys.py中
这时候chatgpt.py直接读取了keys.py中的key，至少能读取到了
但是此时 仍然会显示 AttributeError: module 'openai' has no attribute 'AsyncOpenAI' 的报错
我使用pip install openai --upgrade将openai的版本号提升到最新版，之后就不会报错了



这是测试结果 google、chatgpt、sakura共存都可选
![image](https://github.com/zyddnys/manga-image-translator/assets/157185454/b11dae48-acf7-4764-8a4c-1cc0a7698376)

**Comment by ldqrecord** [comment]
![image](https://github.com/zyddnys/manga-image-translator/assets/75522836/b0aa9ad4-4f4e-42d2-bd64-a93b297d78a8)
更新以后又会报这个错

**Comment by Ctory-Nily** [comment]
> ![图像](https://private-user-images.githubusercontent.com/75522836/346269334-b0aa9ad4-4f4e-42d2-bd64-a93b297d78a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyNjk2NTEsIm5iZiI6MTcyMDI2OTM1MSwicGF0aCI6Ii83NTUyMjgzNi8zNDYyNjkzMzQtYjBhYTlhZDQtNGY0ZS00MmQyLWJkNjQtYTkzYjI5N2Q3OGE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDEyMzU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwOTczZGJmNGZkNjUwODQ2MWYxMzI5M2UyNWE2ODY0YjM5YWU2NDk2ZGY0MWY1NmEyYmM2MDNiOGYxNjk1MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ITKLuhelo3IhmLnjWbLAeyue2xAJhVVq2Rxfu2IF-Mw) 更新以后又会报告这个错误

OPENAI_API_BASE 的问题吧 你看看有没有加https://
以及有没有给到环境变量

**Comment by ldqrecord** [comment]
![image](https://github.com/zyddnys/manga-image-translator/assets/75522836/39178e8a-03ee-44f6-b4e2-b9cd5cecb854)
这样正常吗，httpx重装httpx==0.13.3不报这个错，但是AsyncOpenAI报错，只能按照653用本地模型

**Comment by ldqrecord** [comment]
![image](https://github.com/zyddnys/manga-image-translator/assets/75522836/7c26fefe-23ef-4afa-adfe-373c86800f08)
还有个疑问，为什么这里没有SAKURA的选项呢

**Comment by 253701** [comment]
> ![image](https://private-user-images.githubusercontent.com/75522836/346293482-7c26fefe-23ef-4afa-adfe-373c86800f08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMjk3MzMsIm5iZiI6MTcyMDMyOTQzMywicGF0aCI6Ii83NTUyMjgzNi8zNDYyOTM0ODItN2MyNmZlZmUtMjNlZi00YWZhLWFkZmUtMzczYzg2ODAwZjA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDA1MTcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3MDUyODg2NDQ1Mzk4MGJhNjZiMDVjYTUyYWM1ODQxNDY5ZjU5MzA3Y2Y5YWY2ZTg3ZjBmNzQzOTQ3YTdlM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._43mKUf4i_ZiEWrcfUj1jJnHgKUy-ewF4yQNf6cJ69g) 还有个疑问，为什么这里没有SAKURA的选项呢

我也是遇到这个问题，按教程部署的不知道哪里出错

**Comment by da1995** [comment]
表示完全用不了，哎

**Comment by Ctory-Nily** [comment]
> ![image](https://private-user-images.githubusercontent.com/75522836/346293178-39178e8a-03ee-44f6-b4e2-b9cd5cecb854.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MDE2MTgsIm5iZiI6MTcyMDYwMTMxOCwicGF0aCI6Ii83NTUyMjgzNi8zNDYyOTMxNzgtMzkxNzhlOGEtMDNlZS00NGY2LWI0ZTItYjljZDVjZWNiODU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDA4NDgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxZTEyNTIxN2VhNDY3ODAxMzcwZDRlOTIwMGE2ZGVhZDlmMjdkMTM1Y2E1YzcyNmE5ZGYxM2FkZjc1NTg4YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7en_JYLx4ItnQ8OMdeR6abXVTNXbtCbSecaEK7SM6_8) 这样正常吗，httpx重装httpx==0.13.3不报这个错，但是AsyncOpenAI报错，只能按照653用本地模型

你把OPENAI_API_BASE  的https的s去掉啊

**Comment by zyddnys** [comment]
pip uninstall openai
pip install openai --upgrade
不要用谷歌翻译，反正谷歌翻译质量差的一批

**Comment by jokester** [comment]
https://github.com/zyddnys/manga-image-translator/pull/666 此PR之後 pip會安裝新版的openai包
