### ISSUE TITLE
[Dev request]: propose to remove poetry

### ISSUE THREAD

**Issue by jokester** [zyddnys/manga-image-translator#667]
### Issue

This repo manages 2 sets of deps in parallel, with pip+requirements.txt *and* poetry.

AFAIK the poetry one is not really being used. The release image is built with pip. A CI workflow tries `poetry install` but has been failing for months, and no body seems to care.

I don't think we are in poetry's sweet spot. It *may* be advantageous but certainly require more knowledge to use, which I feel hard to expect from people.

**Comment by jokester** [comment]
if this seems fine I can create a PR for this

**Comment by zyddnys** [comment]
sure
