### ISSUE TITLE
[Feature Request]: 能设置或添加不要字体白包边或者黑色包边吗

### ISSUE THREAD

**Issue by findingwch** [zyddnys/manga-image-translator#671]
### What would your feature do?

<img width="742" alt="image" src="https://github.com/zyddnys/manga-image-translator/assets/92368727/780b24f5-7d05-4ac4-b78e-6966b41f8808">

**Comment by zyddnys** [comment]
新增`--disable-font-border`参数，可以关闭字体描边

**Comment by findingwch** [comment]
谢谢作者能够及时更新。我添加了--disable-font-border参数 运行项目但是效果与上图一样

**Comment by zyddnys** [comment]
给张图看看

**Comment by findingwch** [comment]
效果和上图一样

**Comment by findingwch** [comment]
您好能留个联系方式详细聊聊吗

**Comment by zyddnys** [comment]
修了，记得git pull

**Comment by findingwch** [comment]
pull 了，但是和之前一样的看看是不是遗漏什么地方

**Comment by zyddnys** [comment]
不使用web模式

**Comment by findingwch** [comment]
好的我试试

**Comment by findingwch** [comment]
好像还是不行，使用的命令：python -m manga_translator -v --translator=baidu --inpainting-precision=fp32 --upscaler=esrgan --disable-font-border  --overwrite  -l ENG -i /Users/fi

**Comment by zyddnys** [comment]
![image](https://github.com/user-attachments/assets/7a5c9c8c-0b84-4e20-b5f2-4b348d92dede)
我跑的

**Comment by zyddnys** [comment]
python -m manga_translator --use-gpu --translator gpt3.5 --inpainter lama_large  --detection-size 1536 --overwrite -v -i "349322630-ee534aab-dc1d-4b70-a058-aa593c60f29f.png"  -l ENG --disable-font-border

**Comment by findingwch** [comment]
我没有使用--use-gpu参数，效果和您不一样。我不知道是不是会存在缓存或者参数--use-gpu 会存在影响输出结果

**Comment by findingwch** [comment]
我跑的：
![WX20240717-092201@2x-translated](https://github.com/user-attachments/assets/cc18a29c-707a-4622-8a20-0300733fe0db)

**Comment by pt-boop** [comment]
activate google trans please 😥

**Comment by findingwch** [comment]
我尝试用您的运行还是没有效果。希望能够指导一下

**Comment by zyddnys** [comment]
git log输出是什么

**Comment by findingwch** [comment]
<img width="723" alt="image" src="https://github.com/user-attachments/assets/564fb33d-7beb-464b-9084-cde401074a8a">

**Comment by zyddnys** [comment]
看起来是最新的，那我不知道怎么搞了
