### ISSUE TITLE
[Feature Request]: gp4o mini 來了

### ISSUE THREAD

**Issue by gesen2egee** [zyddnys/manga-image-translator#674]
### What would your feature do?

價格大概是 4o的1/30、速度更快
https://www.inside.com.tw/article/35660-gpt-40-mini-release
測試可以翻譯色色效果很流暢、後果自負

修改這邊就好了
![image](https://github.com/user-attachments/assets/78f6bdb7-5d12-4f4d-b72d-1f19b10bd662)

**Comment by zyddnys** [comment]
added in 6a00f74ffc224575319cd276e724c79d7c8b7c2d

**Comment by fyxc** [comment]
更新下image呗也，本地跑，windows老是报些莫名其妙的错

**Comment by zyddnys** [comment]
什么错误

**Comment by fyxc** [comment]
解决了，之前有个包冲突，安装过后还是不行，重启了下，work了，说起来config在哪改，还是首页只是给了个config的例子，需要自己创建个config file输入，有些十八家图片前后页会出现重复语句，目前gpt翻译会用在前后页不同的词，看起来有点奇怪，得指定下
