### ISSUE TITLE
[Bug]: Translator invalid

### ISSUE THREAD

**Issue by eren-ay** [zyddnys/manga-image-translator#687]
### Issue

Has the google translate option been removed? When I used the default run command, it gave an invalid error. When I selected the sugoi option, it worked. At least it is necessary to edit the readme.

### Command Line Arguments

```Shell
python -m manga_translator -v --translator=google -l ENG -i ./manga_translator/manga-img
```

### Console logs

```Shell
manga_translator: error: argument --translator: invalid choice: 'google' (choose from 'youdao', 'baidu', 'deepl', 'papago', 'caiyun', 'gpt3', 'gpt3.5', 'gpt4', 'none', 'original', 'sakura', 'offline', 'nllb', 'nllb_big', 'sugoi', 'jparacrawl', 'jparacrawl_big', 'm2m100', 'm2m100_big', 'mbart50')
```

**Comment by zyddnys** [comment]
google translator is indeed disabled, readme updated to reflect that
