### ISSUE TITLE
[Bug]: OCR识别相连气泡会将其合并

### ISSUE THREAD

**Issue by popcion** [zyddnys/manga-image-translator#699]
### Issue

![image](https://github.com/user-attachments/assets/98a5e021-57e1-4645-b2d6-04bf51a6c4b9)
是否有避免OCR合并气泡的参数，设置识别间距，以防止相连气泡合并

**Comment by lhj5426** [comment]
这个图 看着眼熟 仔细一看 这tm不是我写的发在E站上的教程里的图么

**Comment by zyddnys** [comment]
能给个原图吗，我好测试

**Comment by lhj5426** [comment]
> 能给个原图吗，我好测试

他的图片来自 我发在E站画廊里的
https://exhentai.org/s/e07effc924/2857507-5

而原图来自画廊
https://exhentai.org/s/908a361c31/2533822-14

然后这种我用我自己标注了5万7千张图的 yoloV11训练的模型 解决了

https://github.com/user-attachments/assets/f5ed3c09-abad-4dd8-91ba-ca7e45353b7a

**Comment by popcion** [comment]
尝试调小textline_merge中的sigma和gamma参数即可分离，对竖排文字效果明显，对横排文字效果较小。

**Comment by popcion** [comment]
`if bboxes[connected_region_indices[0]].distance(bboxes[connected_region_indices[1]]) < (1 + gamma) * fs \
        and abs(bboxes[connected_region_indices[0]].angle - bboxes[connected_region_indices[1]].angle) < 0.1 * np.pi:  # 这还有一个调整文字框框弧度差异的阈值，小于此弧度可参与合并
    return [set(connected_region_indices)]
else:
    return [set([connected_region_indices[0]]), set([connected_region_indices[1]])]`
