### ISSUE TITLE
[Bug]: official demo

### ISSUE THREAD

**Issue by ash-ketsup** [zyddnys/manga-image-translator#700]
### Issue

I don't know a lick of japanese but I think the official demo is broken:

Original
![232265329-6a560438-e887-4f7f-b6a1-a61b8648f781](https://github.com/user-attachments/assets/8c908772-7be5-4e1a-a7bb-dd6180db7f51)

"Translated"
![translation- object Object](https://github.com/user-attachments/assets/6b074233-9036-40ba-ab75-55a807791615)

**Comment by zyddnys** [comment]
what did you do to get that?

**Comment by ash-ketsup** [comment]
Nothing special. Just uploaded the image into it.
![Screenshot_20240829_013926](https://github.com/user-attachments/assets/3900d9cf-7a9b-4d3e-b0f8-837adc0efe1f)

If I f around with settings it just gives me different colors. Same "broken gpu" pattern though.

**Comment by zyddnys** [comment]
use the local version, the demo site has cache issues
