### ISSUE TITLE
[Bug]: poetry install failed

### ISSUE THREAD

**Issue by vipcxj** [zyddnys/manga-image-translator#705]
### Issue

poetry say:
Installing dependencies from lock file
Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.

Because manga-image-translator depends on langdetect (>=1.0.0) which doesn't match any versions, version solving failed.

python的依赖管理还是一如既往的糟糕。github上的python就没几个安装依赖不出问题的~ 其他语言就没这些破事

### Command Line Arguments

```Shell
poetry shell
poetry install
```

### Console logs

```Shell
Installing dependencies from lock file
Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.

Because manga-image-translator depends on langdetect (>=1.0.0) which doesn't match any versions, version solving failed.
```

**Comment by yilinjuang** [comment]
We should drop requirements.txt or at least never edit it manually and always export from poetry.

```shell
poetry export -f requirements.txt --output requirements.txt
```

https://python-poetry.org/docs/cli/#export

**Comment by jokester** [comment]
poetry got removed in https://github.com/zyddnys/manga-image-translator/pull/708
