### ISSUE TITLE
怎么回事

### ISSUE THREAD

**Issue by buiawpkgew1** [zyddnys/manga-image-translator#71]
>Traceback (most recent call last):
  File "G:\GitHub\image-translator\manga-image-translator\translate_demo.py", line 15, in <module>
    from text_mask import dispatch as dispatch_mask_refinement
  File "G:\GitHub\image-translator\manga-image-translator\text_mask\__init__.py", line 8, in <module>
    from .text_mask_utils import complete_mask_fill, filter_masks, complete_mask
  File "G:\GitHub\image-translator\manga-image-translator\text_mask\text_mask_utils.py", line 94, in <module>
    from pydensecrf.utils import compute_unary, unary_from_softmax
ModuleNotFoundError: No module named 'pydensecrf'

**Comment by Snowad14** [comment]
Just read the readme
![image](https://user-images.githubusercontent.com/67842535/180209741-25e4e671-514d-4596-92c2-eae7b584778b.png)

**Comment by buiawpkgew1** [comment]
安装 PyDenseCRF 失败
![image](https://user-images.githubusercontent.com/71136405/180343098-d001ea7f-5cc6-45cb-8326-6001077996ac.png)

**Comment by Snowad14** [comment]
Read the error : You need to install Microsoft Visual C++ 14.0 or greater

**Comment by buiawpkgew1** [comment]
>Collecting PyDenseCRF
  Using cached pydensecrf-1.0rc3.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for PyDenseCRF, since package 'wheel' is not installed.
Installing collected packages: PyDenseCRF
  Running setup.py install for PyDenseCRF ... error
  error: subprocess-exited-with-error

>  × Running setup.py install for PyDenseCRF did not run successfully.
  │ exit code: 1
  ╰─> [83 lines of output]
      WARNING: The wheel package is not available.
      running install
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.10
      creating build\lib.win-amd64-3.10\pydensecrf
      copying pydensecrf\utils.py -> build\lib.win-amd64-3.10\pydensecrf
      copying pydensecrf\__init__.py -> build\lib.win-amd64-3.10\pydensecrf
      running build_ext
      building 'pydensecrf/eigen' extension
      creating build\temp.win-amd64-3.10
      creating build\temp.win-amd64-3.10\Release
      creating build\temp.win-amd64-3.10\Release\pydensecrf
      C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ipydensecrf/densecrf/include -IG:\Program Files\Python310\include -IG:\Program Files\Python310\Include -IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE -IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt -IC:\Program Files (x86)\Windows Kits\8.1\include\shared -IC:\Program Files (x86)\Windows Kits\8.1\include\um -IC:\Program Files (x86)\Windows Kits\8.1\include\winrt /EHsc /Tppydensecrf/eigen.cpp /Fobuild\temp.win-amd64-3.10\Release\pydensecrf/eigen.obj
      eigen.cpp
      pydensecrf/eigen.cpp(14316): error C2105: '++' needs l-value
      pydensecrf/eigen.cpp(14318): error C2105: '--' needs l-value
      pydensecrf/eigen.cpp(14600): error C2105: '++' needs l-value
      pydensecrf/eigen.cpp(14602): error C2105: '--' needs l-value
      pydensecrf/eigen.cpp(14837): error C2105: '++' needs l-value
      pydensecrf/eigen.cpp(14839): error C2105: '--' needs l-value
      pydensecrf/eigen.cpp(15393): error C2039: 'tp_print': is not a member of '_typeobject'
      g:\program files\python310\include\cpython/object.h(191): note: see declaration of '_typeobject'
      pydensecrf/eigen.cpp(15400): error C2039: 'tp_print': is not a member of '_typeobject'
      g:\program files\python310\include\cpython/object.h(191): note: see declaration of '_typeobject'
      pydensecrf/eigen.cpp(15407): error C2039: 'tp_print': is not a member of '_typeobject'
      g:\program files\python310\include\cpython/object.h(191): note: see declaration of '_typeobject'
      pydensecrf/eigen.cpp(15411): error C2039: 'tp_print': is not a member of '_typeobject'
      g:\program files\python310\include\cpython/object.h(191): note: see declaration of '_typeobject'
      pydensecrf/eigen.cpp(15422): error C2039: 'tp_print': is not a member of '_typeobject'
      g:\program files\python310\include\cpython/object.h(191): note: see declaration of '_typeobject'
      pydensecrf/eigen.cpp(15431): error C2039: 'tp_print': is not a member of '_typeobject'
      g:\program files\python310\include\cpython/object.h(191): note: see declaration of '_typeobject'
      pydensecrf/eigen.cpp(16565): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
      g:\program files\python310\include\cpython/unicodeobject.h(446): note: see declaration of '_PyUnicode_get_wstr_length'
      pydensecrf/eigen.cpp(16581): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
      g:\program files\python310\include\cpython/unicodeobject.h(446): note: see declaration of '_PyUnicode_get_wstr_length'
      pydensecrf/eigen.cpp(16989): warning C4996: 'PyUnicode_FromUnicode': deprecated in 3.3
      g:\program files\python310\include\cpython/unicodeobject.h(551): note: see declaration of 'PyUnicode_FromUnicode'
      pydensecrf/eigen.cpp(17032): error C2039: 'exc_type': is not a member of '_ts'
      g:\program files\python310\include\cpython/pystate.h(60): note: see declaration of '_ts'
      pydensecrf/eigen.cpp(17033): error C2039: 'exc_value': is not a member of '_ts'
      g:\program files\python310\include\cpython/pystate.h(60): note: see declaration of '_ts'
      pydensecrf/eigen.cpp(17034): error C2039: 'exc_traceback': is not a member of '_ts'
      g:\program files\python310\include\cpython/pystate.h(60): note: see declaration of '_ts'
      pydensecrf/eigen.cpp(17041): error C2039: 'exc_type': is not a member of '_ts'
      g:\program files\python310\include\cpython/pystate.h(60): note: see declaration of '_ts'
      pydensecrf/eigen.cpp(17042): error C2039: 'exc_value': is not a member of '_ts'
      g:\program files\python310\include\cpython/pystate.h(60): note: see declaration of '_ts'
      pydensecrf/eigen.cpp(17043): error C2039: 'exc_traceback': is not a member of '_ts'
      g:\program files\python310\include\cpython/pystate.h(60): note: see declaration of '_ts'
      pydensecrf/eigen.cpp(17044): error C2039: 'exc_type': is not a member of '_ts'
      g:\program files\python310\include\cpython/pystate.h(60): note: see declaration of '_ts'
      pydensecrf/eigen.cpp(17045): error C2039: 'exc_value': is not a member of '_ts'
      g:\program files\python310\include\cpython/pystate.h(60): note: see declaration of '_ts'
      pydensecrf/eigen.cpp(17046): error C2039: 'exc_traceback': is not a member of '_ts'
      g:\program files\python310\include\cpython/pystate.h(60): note: see declaration of '_ts'
      pydensecrf/eigen.cpp(17101): error C2039: 'exc_type': is not a member of '_ts'
      g:\program files\python310\include\cpython/pystate.h(60): note: see declaration of '_ts'
      pydensecrf/eigen.cpp(17102): error C2039: 'exc_value': is not a member of '_ts'
      g:\program files\python310\include\cpython/pystate.h(60): note: see declaration of '_ts'
      pydensecrf/eigen.cpp(17103): error C2039: 'exc_traceback': is not a member of '_ts'
      g:\program files\python310\include\cpython/pystate.h(60): note: see declaration of '_ts'
      pydensecrf/eigen.cpp(17104): error C2039: 'exc_type': is not a member of '_ts'
      g:\program files\python310\include\cpython/pystate.h(60): note: see declaration of '_ts'
      pydensecrf/eigen.cpp(17105): error C2039: 'exc_value': is not a member of '_ts'
      g:\program files\python310\include\cpython/pystate.h(60): note: see declaration of '_ts'
      pydensecrf/eigen.cpp(17106): error C2039: 'exc_traceback': is not a member of '_ts'
      g:\program files\python310\include\cpython/pystate.h(60): note: see declaration of '_ts'
      pydensecrf/eigen.cpp(17128): error C2039: 'exc_type': is not a member of '_ts'
      g:\program files\python310\include\cpython/pystate.h(60): note: see declaration of '_ts'
      pydensecrf/eigen.cpp(17129): error C2039: 'exc_value': is not a member of '_ts'
      g:\program files\python310\include\cpython/pystate.h(60): note: see declaration of '_ts'
      pydensecrf/eigen.cpp(17130): error C2039: 'exc_traceback': is not a member of '_ts'
      g:\program files\python310\include\cpython/pystate.h(60): note: see declaration of '_ts'
      pydensecrf/eigen.cpp(17131): error C2039: 'exc_type': is not a member of '_ts'
      g:\program files\python310\include\cpython/pystate.h(60): note: see declaration of '_ts'
      pydensecrf/eigen.cpp(17132): error C2039: 'exc_value': is not a member of '_ts'
      g:\program files\python310\include\cpython/pystate.h(60): note: see declaration of '_ts'
      pydensecrf/eigen.cpp(17133): error C2039: 'exc_traceback': is not a member of '_ts'
      g:\program files\python310\include\cpython/pystate.h(60): note: see declaration of '_ts'
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit code 2
      [end of output]

>  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

>× Encountered error while trying to install package.
╰─> PyDenseCRF

**Comment by Snowad14** [comment]
pip install wheel and make sure you install _pydensecrf from https://www.lfd.uci.edu/~gohlke/pythonlibs/#_pydensecrf
