### ISSUE TITLE
[Bug]: 关于参数是怎么写的？

### ISSUE THREAD

**Issue by Qyyxzz** [zyddnys/manga-image-translator#722]
### Issue

用web指定参数但是看日志貌似没有用上？
![91e3c3a938ac7ba4fd215d8203d78165](https://github.com/user-attachments/assets/56cb3f5c-5ef0-4c39-9404-ae0444a2ce0d)
![01a80fd44572216266f47f918e67f03a](https://github.com/user-attachments/assets/885dff1d-f473-45f2-b9a4-f064b4860c64)

### Command Line Arguments

```Shell
python -m manga_translator --mode web --target-lang CHT --inpainting-precision bf16 --ocr 48px_ctc --inpainter lama_large --translator gpt4 --verbose --detection-size 1536 --inpainting-size 2048 --save-quality 100

python -m manga_translator --mode web --target-lang=CHT --inpainting-precision=bf16 --ocr=48px_ctc --inpainter=lama_large --translator=gpt4 --verbose --detection-size=1536 --inpainting-size=2048 --save-quality=100
```

**Comment by popcion** [comment]
不用管，我之前也有这个问题，但是实际上web这个日志上的都是默认的参数，而命令行中的改了会变，自己改了就应该生效了

**Comment by MIUKUKANO** [comment]
> > 不用管，我之前也有这个问题，但是实际上web这个日志上的都是默认的参数，而batch中的改了会变，自己改了就应该生效了
> 
> 那要改web的默认参数的话哪个文件可以改吗

佬解决了吗 ？我也遇到了

**Comment by popcion** [comment]
可能是参数没传过去把，手动把chatgpt.py的{to_lang}全部替换成CHT就完了
