### ISSUE TITLE
how do i start the program after successfully install the requirements?

### ISSUE THREAD

**Issue by yeartwothousandfive** [zyddnys/manga-image-translator#727]
newbie here. i got an assistance from ai  in installing/set up but after installing the requirements.txt what to do nxt? I tried to use the python main.py command and it doesnt work. help please.

```
`(venv)` C:\Projects\manga-image-translator>python main
.py
C:\Users\kierj\AppData\Local\Programs\Python\Python311\python.exe: can't open file 'C:\\Projects\\manga-image-translator\\main.py': [Errno 2] No such file or directory
```

**Comment by Armaqanal** [comment]
I think you are not in the correct directory, so main.py doesn't exist in your current directory. Also, check your virtual environment and make sure it's activated

**Comment by yeartwothousandfive** [comment]
btw is Gemini available as translator? I don't have the deepL API
