### ISSUE TITLE
[Bug]: unknown arg overlay_type

### ISSUE THREAD

**Issue by eren-ay** [zyddnys/manga-image-translator#743]
### Issue

in the README api v2 documentation There is an argument called overlay_type, but I could not find a field where this argument is used. 

### Console logs

```Shell
{'overlay_type': ['unknown field.']}
```

**Comment by JustFrederik** [comment]
It was changed to overlay_ext. What it means is that the overlay is converted to a base64 encoded image. It could be a jpeg/png/…
