### ISSUE TITLE
[Feature Request]: How do I change the translation language and model for local translation?

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#781]
### What would your feature do?

How do I change the translation language and model for local translation?

- [ ] Update README.md

**Comment by popcion** [comment]
use config file
https://github.com/zyddnys/manga-image-translator/blob/main/examples/config-example.json

**Comment by My12123** [comment]
Это не сработало 
![image](https://github.com/user-attachments/assets/456aae04-fc53-403c-9af3-b04ce4ca3533)
 
![2024-12-18_13-47-15](https://github.com/user-attachments/assets/7602d2d1-e93c-427e-8db9-873fb3e27eba)

**Comment by My12123** [comment]
@popcion
It didn't help.

**Comment by popcion** [comment]
ser path
--config-file PATH
