### ISSUE TITLE
大佬， readme的图片能换换不，工作场合不宜打开

### ISSUE THREAD

**Issue by YaoFANGUK** [zyddnys/manga-image-translator#8]

**Comment by lllyasviel** [comment]
反对。我觉得这些图片没问题。不需要换。



---原始邮件---
发件人: "Yao ***@***.***&gt;
发送时间: 2021年6月2日(周三) 下午5:15
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zyddnys/manga-image-translator] 大佬， readme的图片能换换不，工作场合不宜打开 (#8)
