### ISSUE TITLE
Crashes related to findHomography 

### ISSUE THREAD

**Issue by crotron** [zyddnys/manga-image-translator#82]
I am encountering two different types of crashes that seem to be related to cv2.findHomography in Quadrilateral.get_transformed_region.

The first of these crashes is:
`The size of tensor a (791) must match the size of tensor b (768) at non-singleton dimension 1`

The problem appears to be that the region outputted by cv2.findHomography/cv2.warpPerspective can be too wide. In the specific run that caused this error, one of the regions processed by run_ocr_48px_ctc is of width 3034, which results in a max_width of 3169. The size of this dimension is then reduced to 791 in self.backbone(img). Finally, the code "x + self.pe[:, offset: offset + x.size(1), :]" crashes because self.pe only has a length of 768, while x has a length of 791. It seems like in most other cases the max_width value is a lot smaller and so does not cause this to occur. 

The second of these crashes is:
`OpenCV(4.2.0) /io/opencv/modules/imgproc/src/imgwarp.cpp:3167: error: (-215:Assertion failed) (M0.type() == CV_32F || M0.type() == CV_64F) && M0.rows == 3 && M0.cols == 3 in function 'warpPerspective'`

The problem appears to be that the M output of cv2.findHomography could be None (which seems to be mentioned in the docs, https://docs.opencv.org/4.6.0/d9/d0c/group__calib3d.html#ga4abc2ece9fab9398f2e560d53c8c9780). In this scenario feeding a null M into cv2.warpPerspective causes the crash. 

In order to see whether it was an issue on my end due to differences in environment/changes in the code, I went and tried it on the online demo, which caused it to tell me "Something went wrong (maybe your language is not supported), please try again", whereas other images didn't seem to have any issues. I would be happy to attempt a fix if these are indeed actual problems, but I don't know what the best way to approach this would be.

**Comment by zyddnys** [comment]
Can you share the image that is causing this issue and the command line argument you are using?

**Comment by crotron** [comment]
@zyddnys Sure, here are some examples:
![image 1](https://user-images.githubusercontent.com/34594223/190883457-ebac63a5-2734-4050-876a-aeba4631a110.jpg)
`python translate_demo.py --verbose --image 1.jpg`
![image 2](https://user-images.githubusercontent.com/34594223/190883459-bac2c49f-ea7e-4638-80b0-914bf4081eb9.jpg)
`python translate_demo.py --verbose --image 2.jpg`
