### ISSUE TITLE
Can create manhua translation chorme extension ?

### ISSUE THREAD

**Issue by kaiter999** [zyddnys/manga-image-translator#85]
can create manhua translation chorme extension from ac.qq.com or more ?

**Comment by ryanolee** [comment]
There should already be support for image translation from the browser using this user script in conjunction with tamper monkey extension: https://greasyfork.org/en/scripts/437569-touhou-ai-manga-translator-regular-edition :thinking:

**Comment by hcharbonnier** [comment]
I developed a Chrome extension available at https://github.com/hcharbonnier/manga-image-translator-chrome-extension However, it requires your own instance of manga-image-translator, accessible via HTTPS with a valid certificate.

Please note that I created this extension on whim, so its future evolution is uncertain.
