### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled. how to fix it?

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#87]
how to fix it?
![2022-09-30_14-46-22](https://user-images.githubusercontent.com/49092250/193262944-25845544-56c5-45bb-8b42-cdb2c87bc2ca.png)

**Comment by zyddnys** [comment]
If you don't want to use CUDA (say you have an nvidia GPU) you can remove the `--use-cuda` flag, if you want to use cuda you need to follow the instruction at https://pytorch.org/ on how to install pytorch with cuda support.

**Comment by My12123** [comment]
Which version of cuda is better to install?
![2022-10-01_10-11-01](https://user-images.githubusercontent.com/49092250/193397712-f296406c-39ef-4c1f-baff-ec5223c502ac.png)

**Comment by My12123** [comment]
![2022-10-01_10-35-53](https://user-images.githubusercontent.com/49092250/193398581-e7ffd737-1e0c-4892-9166-07323992d78a.png)
![2022-10-01_10-36-24](https://user-images.githubusercontent.com/49092250/193398587-61248c23-8a08-40d9-9262-6c028c3aefdc.png)
how to fix it?

**Comment by zyddnys** [comment]
uninstall old pytorch first, then install cuda version

**Comment by My12123** [comment]
Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
![2022-10-02_12-06-03](https://user-images.githubusercontent.com/49092250/193446688-40d7d3f4-f81b-47e8-8376-09142a71c58f.png)

**Comment by zyddnys** [comment]
try setting KMP_DUPLICATE_LIB_OK=TRUE by using `set "KMP_DUPLICATE_LIB_OK=TRUE"` before the python command

**Comment by My12123** [comment]
![2022-10-03_17-30-20](https://user-images.githubusercontent.com/49092250/193603192-b3ad0bca-b70c-4511-877c-227120a9d915.png)
![2022-10-03_17-30-29](https://user-images.githubusercontent.com/49092250/193603211-b37f0fbc-e442-4757-adc0-bb3e8165501d.png)
how to fix it?

**Comment by zyddnys** [comment]
No you can't. With only 2G of VRAM I believe you can only use it with cuda disabeld, by removing `--use-cuda`.
