### ISSUE TITLE
impossible to get a horizontal translation

### ISSUE THREAD

**Issue by LeChanceuxEnchante** [zyddnys/manga-image-translator#89]
It's pretty difficult to read sentences in Latin script vertically, isn't there a way to fix that?

**Comment by thatDudo** [comment]
If you have a computer capable of running this you can add the `--manga2eng` flag.

**Comment by LeChanceuxEnchante** [comment]
thank you, it works well with English, unfortunately when I want to translate into other languages ​​like French it stays vertical

**Comment by thatDudo** [comment]
The problem is that `--manga2eng` only runs when the target language is English - for no reason what so ever...
I will can fix that but you will have to wait until the owner of the repository will merge it.

**Comment by Snowad14** [comment]
You need to add : **--force-horizontal** or replace "ENG" of [this line](https://github.com/zyddnys/manga-image-translator/blob/7308a274136574782d99350d14d09e2577495978/translate_demo.py#L218) to "FRA"

**Comment by LeChanceuxEnchante** [comment]
Thank you for your answers, I don't know much about programming, is it possible to change this line of code so that it works for both ENG and FRA?

**Comment by thatDudo** [comment]
You can replace it with
```py
if args.target_lang in ['ENG', 'FRA'] and args.manga2eng:
 ```
just keep that whitespace before the text.
