### ISSUE TITLE
图片无法翻译

### ISSUE THREAD

**Issue by haofanwang** [zyddnys/manga-image-translator#9]
是因为渲染的原因？

**Comment by zyddnys** [comment]
图片发给我下是怎么回事.在线版为最初版本,可能处理不了一些图片

**Comment by haofanwang** [comment]
@zyddnys 

好像不是图片的问题。即使使用你提供的样例图片，也会出现线条，而且每一次跑结果不太一样（impainting是没问题，但往图片上写文本有点问题），下面是同一份代码跑出的结果。可以幸苦检查一下么？

![final](https://user-images.githubusercontent.com/18741068/124958594-e8a20280-e04c-11eb-8df9-0c4b31149f9f.png)

![final (1)](https://user-images.githubusercontent.com/18741068/124958821-29018080-e04d-11eb-88ae-7c9016709481.png)

**Comment by zyddnys** [comment]
不加inpainting确实会这样,先用inpainting,之后我去修
