### ISSUE TITLE
？

### ISSUE THREAD

**Issue by shkds** [zyddnys/manga-image-translator#98]
Unable to find image 'zyddnys/manga-image-translator:latest' locally
docker: Error response from daemon: manifest for zyddnys/manga-image-translator:latest not found: manifest unknown: manifest unknown.

**Comment by moisesvmr** [comment]
same problem it seems that the docker image does not exist ?

**Comment by Just-A-Goblin** [comment]
if you run a `docker images` command you'll see your locally generated images.  for mine it lacks the zyddnys/ prefix, so when running the run docker command I replaced "zyddnys/manga-image-translator" with "manga-image-translator" and it ran properly.

**Comment by zyddnys** [comment]
THE DOCKER IMAGE EXISTS NOW. https://hub.docker.com/r/zyddnys/manga-image-translator
